### ISSUE TITLE
Linux executable file is encoded in ANSI instead of UTF-8

### ISSUE THREAD

**Issue by lgvr123** [fvarrui/JavaPackager#101]
I'm a building a Linux packaging of an app in a Window environment.
After deployment and execution in a Linux VM, Linux complains that the exe file is not UTF-8. And indeed, on my Windows machine, it is encoded in ANSI.

The exe file is made of the concatenation of the ```startup.sh``` file and the "runnable" jar. 
The ```startup.sh``` is in UTF-8. But the resulting concatenation is in ANSI which is not accepted by Linux.

After looking at the sources, the error would reside the the ```FileUtils#concat``` method that does not impose an encoding to the resulting file :
```
	public static void concat(File dest, File ... sources) throws Exception {
		Logger.info("Concatenating files [" + StringUtils.join(sources, ",") + "] into file [" + dest + "]");
		try {
			FileOutputStream fos = new FileOutputStream(dest);
			for (File source : sources) {
				FileInputStream fis = new FileInputStream(source);
				IOUtils.copy(fis, fos);
				fis.close();
			}
			fos.flush();
			fos.close();
		} catch (IOException e) {
			throw new Exception("Error concatenating streams", e);
		}
	}
```

On my system, ```System.getProperty("file.encoding")``` and ```Charset.defaultCharset()``` are returning "windows-1252".

A fix would be to adapt ```FileUtils#concat``` to move from ```FileOutputStream``` to [FileWriter](https://stackoverflow.com/a/34322496/2398993) to specify a CharSet. FileWriter are [also supported by Apache Common IOUtils](https://javadevcentral.com/apache-commons-ioutils#Copying_using_IOUtils).

- JavaPackager version: 1.5.1
- OS version: Windows 7
- JDK version: jdk1.8.0_162
- Build tool: 
	- [x] Maven 
	- [ ] Gradle

**Comment by fvarrui** [comment]
Hi @lgvr123!

Are you using a customized `startup.sh.vtl`  template? 

If we use `FileWriter` specifying a Charset, will this affect binary files?

**Comment by lgvr123** [comment]
> If we use `FileWriter` specifying a Charset, will this affect binary files?

I guess no. I was about to the update the plugin on my side and then make a pull-request for it.

**Comment by fvarrui** [comment]
Great! But I tried to build an app from Windows for Linux, and it worked fine on WSL with Ubuntu.

**Comment by lgvr123** [comment]
Do you have the same default encoding ?
On my system, System.getProperty("file.encoding") and Charset.defaultCharset() are returning "windows-1252".

Also, im my pom.xml, encoding is defined like this:
```
<properties>
    <project.build.sourceEncoding>windows-1252</project.build.sourceEncoding>
    <!--<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>-->
</properties>
```
I'm not sure if it has an influence. But couldn't switch to UTF_8 to test because all my project sources are in windows-1252.

**Comment by fvarrui** [comment]
Ok! Please, try what you suggested and make a PR if it works fine! I have the doubt if setting an encoding for a binary file can corrupt it, as I'm not sure about it. If so, we can add an special method only to concat a text file (`startup.sh` encoded in UTF-8) with a binary file (`jar` file).

**Comment by fvarrui** [comment]
BTW, I specify this in my testing project:
```xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```
maybe this makes the difference as you say.

**Comment by lgvr123** [comment]
I couldn't solve the issue. The only workaround has been to move all my project to UTF-8. And now it is working.
So this my might described as a pre-requisite for the plugin.

**Comment by fvarrui** [comment]
So, using this in your pom.xml
```xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> ```
fixed your problem?

I'll continue looking into it, because I think it's not a good idea making developers to adapt their code to a packaging plugin.

**Comment by fvarrui** [comment]
I haven't been able to reproduce your issue ... Could you send me the error message when running the application on Linux?

I've also been looking into `IOUtils.copy` and it copies the content of the files at byte level, without encoding, and changing the value of `project.build.sourceEncoding` property between `UTF-8` and `windows-1252` generates the same executable for Linux, with the same encoding.

How do you check the encoding of the generated executable? Are you sure your problem is not the encoding of your source code files? Maybe you can try it running your Jar directly on Linux, compiled from `windows-1252` source files.
