### ISSUE TITLE
How-To: JavaFX meets JavaPackager

### ISSUE THREAD

**Issue by antmordel** [fvarrui/JavaPackager#104]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
Hey Francisco, very nice piece of work. Thanks for sharing it with the open source community.

I was wondering if you have tried to package a JavaFX application using this plugin, and if so, if you mind sharing a small doc. If you want help writing that doc I could submit a PR! I've seen https://github.com/wiverson/maven-jpackage-template, but I was curious on how both compare! 

Thanks a lot Francisco.

**Comment by fvarrui** [comment]
Hi Nito!
Thanks ... a PR will be welcomed!

You just need to declare required JavaFX libraries as dependencies in your `pom.xml` or `build.gradle` and include a main class which calls `Application.main()` method (as it's explained [here](https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530)).

If you want I will send you sample project as soon as I can.

**Comment by fvarrui** [comment]
Hi @antmordel!
Here you have a sample project: [Dogs](https://github.com/dam-dad/Dogs).
I hope it helps!

**Comment by antmordel** [comment]
This is very cool indeed. Thanks a lot @fvarrui. Any help you need with JavaPackager please let me know.
