### ISSUE TITLE
Windows EXE with bundel JRE11 will not launch if JRE8 is in %PATH%

### ISSUE THREAD

**Issue by commi** [fvarrui/JavaPackager#110]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

The launcher EXE from launch4j does not start (due to some unlogged error i assume), if a conflicting JRE is in the current %PATH%.

**Steps to reproduce the issue/enhancement:**

1. Create Project with bundled JRE 11 and some stuff that requires JRE11 (in our case JFX11)
2. Build Windows EXE
3. Put a JRE 8 in the Windows %PATH% 
4. Start a  new terminal window (to make sure new %PATH% is set)
5. Check with echo %PATH% that the JRE 8 is present as the only JRE in %PATH%
6. Run EXE _from the folder the EXE is contained_

**What is the expected behavior?**

Exe should launch with the bundled  JRE under .\jre

**What is the current behavior?**

Exe spawns a javaw.exe-process (from the bundled JRE!) that hangs forever and does nothing.

**Please tell us about your environment:**

- JavaPackager version: 15.1
- OS version: Windows 10
- JDK version: Adopt-openjdk 11.0.11
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

I tried setting the minJreVersion parameter to 11, but that did not chnage the behaviour.
The launcher launches the correct javaw.exe, but somehow the PATH breaks something.

It can be be reproduced by changing the %PATH% var in a terminal repeatedly and launching the EXE, without re-building anyting. So it's a runtime problem.

I see that this is probably a launch4j bug, but maybe it helps to be aware of it. 
Maybe the bug can be fixed with a certain launch4j-config, but i did no look into this because right now the l4j-config is not editable, right?

**Comment by commi** [comment]
After searching similar issues in the adoptium and openj9 tracker, it seems that the JRE itself is influenced be PATH when searching for certain DLL's. All solutions included somehow modifying the PATH bevore launch.

So my question would be: Can launch4j modify ENV-vars and could we just always prepend the bundled jre-path and jre/bin-path the PATH with javapackager?

**Comment by fvarrui** [comment]
Hi @commi!

> Exe spawns a javaw.exe-process (from the bundled JRE!) that hangs forever and does nothing.

Sorry, but I wasn't able to reproduce your issue following your steps. I have a simple HelloWorld app for testing, which shows all environment and system variables. When I add jre8 path to `PATH` variable its output is the next, and it works as expected:

```
==============================================
ENVIRONMENT VARIABLES ========================
==============================================

[...]
JAVA_HOME=C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot
Path=C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\tools\ruby27\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\gnupg\bin;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files\nodejs\;C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\Users\fvarrui\AppData\Local\Microsoft\WindowsApps;C:\Users\fvarrui\AppData\Local\GitHubDesktop\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\fvarrui\AppData\Roaming\npm;;C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre\bin
[...]

==============================================
PROPERTIES ===================================
==============================================

[...]
java.class.path=C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\HelloWorldMaven.exe
java.home=C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre
java.runtime.version=11.0.11+9
java.version=11.0.11
user.dir=C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven
java.library.path=C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\tools\ruby27\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\gnupg\bin;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files\nodejs\;C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\Users\fvarrui\AppData\Local\Microsoft\WindowsApps;C:\Users\fvarrui\AppData\Local\GitHubDesktop\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\fvarrui\AppData\Roaming\npm;;C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre\bin;.
java.class.version=55.0
[...]
```
> \* I removed some irrelevant lines.

> \*\* Only one difference: I'm not including any stuff which requires JRE11 (e.g. JFX11) ... only my own classes.

```bash
C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>dir
 El volumen de la unidad C es Sistema
 El número de serie del volumen es: 7E0F-4FA3

 Directorio de C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven

13/05/2021  16:53    <DIR>          .
13/05/2021  16:53    <DIR>          ..
13/05/2021  16:53           264.804 HelloWorldMaven.exe
11/09/2020  18:21           209.948 HelloWorldMaven.ico
11/09/2020  18:21                20 info.txt
13/05/2021  16:53    <DIR>          jre
13/05/2021  16:52    <DIR>          libs
13/05/2021  16:52            35.149 LICENSE
               4 archivos        509.921 bytes
               4 dirs  32.216.334.336 bytes libres

C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>jre\bin\java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>java -jar HelloWorldMaven.exe
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/fvarrui/helloworld/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven>jre\bin\java -jar HelloWorldMaven.exe
args=[]
Starting app ...
PATH=C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\tools\ruby27\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\gnupg\bin;C:\Program Files (x86)\WiX Toolset v3.11\bin;C:\Program Files\nodejs\;C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\bin;C:\Users\fvarrui\AppData\Local\Microsoft\WindowsApps;C:\Users\fvarrui\AppData\Local\GitHubDesktop\bin;C:\Program Files\Oracle\VirtualBox;C:\Users\fvarrui\AppData\Roaming\npm;

```

Have you tried to build your EXE using `<winConfig><headerType>console</headerType></winConfig>`? (so, when you run your EXE, it'll print its output in a console window ... maybe it throws some light about why your app is hanging)

**Comment by commi** [comment]
Thanks for the tip with `headerType`, that will make things easier:)

The output now shows the Exception that i expected .. some `NoSuchMethodError` from JavaFX:

```
T:\nba-produkt\target\nba-produkt>echo %path%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.232-1\bin;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.232-1\jre\bin;C:\Program Files\Git\cmd;C:\Users\Till\AppData\Local\Microsoft\WindowsApps;

T:\nba-produkt\target\nba-produkt>nba-produkt.exe
Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
        at com.sun.glass.ui.win.WinApplication.staticScreen_getScreens(Native Method)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205)
```


The _same_ Exception is thrown, when i run the app from IntelliJ while %PATH% contains JRE8, even when IntelliJ has the correct JDK set as the project SDK.


Just for completeness the output after i 'fix' the path variable:

```
T:\nba-produkt\target\nba-produkt>set path=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Inno Setup 6;C:\Users\Till\AppData\Local\Microsoft\WindowsApps;

T:\nba-produkt\target\nba-produkt>echo %path%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Inno Setup 6;C:\Users\Till\AppData\Local\Microsoft\WindowsApps;

T:\nba-produkt\target\nba-produkt>nba-produkt.exe
18:59:51.889 [JavaFX Application Thread] […] ->App runs normally
```

So def a JVM bug i would say, and the Exceptions 'needs' JavaFX, because this causes the call to native code that crashes.

i found this demo project for JFX 11 to repro the bug: https://github.com/slothsoft/example-javafx-maven

JAVA_HOME is not set at all on this system. And the Windows Taskmanager confirms that the launched java(w).exe is indeed from the correct JRE every time. Maybe JAVA populates its own `library.path` from %PATH% and then loads all the wrong libraries.

**Comment by fvarrui** [comment]
Please, could you print `java.library.path` property in console and check what value it has?

```java
System.out.println(System.getProperty("java.library.path"));
```

**Comment by fvarrui** [comment]
I remember that I had a similar issue and removed `%USERPROFILE%\.openjfx` folder to fix it ... but I'm not sure if this is your problem.

**Comment by commi** [comment]
> T:\nba-produkt\target\nba-produkt>echo %path%
> C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.232-1\bin;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.232-1\jre\bin;C:\Program Files\Git\cmd;C:\Users\Till\AppData\Local\Microsoft\WindowsApps;
> 
> T:\nba-produkt\target\nba-produkt>nba-produkt.exe
> T:\nba-produkt\target\nba-produkt\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;**C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.232-1\bin;C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.232-1\jre\bin;C:\Program Files\Git\cmd;C:\Users\Till\AppData\Local\Microsoft\WindowsApps;**;T:\nba-produkt\target\nba-produkt\jre\bin;.
> Exception in thread "WindowsNativeRunloopThread" java.lang.NoSuchMethodError: <init>
>         […]
> Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
>         at com.sun.prism.d3d.D3DPipeline.getAdapterOrdinal(D3DPipeline.java:205)
>         […]

I logged the the library path (the line directly after the EXE-invocation). It seems to be a copy of `%PATH%`, with `.\jre\bin` and some defaults paths prepended. But the first entry does not seem to be enough to make the JVM use its own DLL's.

I deleted the .openjfx-folder, but that did not make a difference. There ere some DLL's in there, but they were all JAVA 11, and the folder is repopulated after a 'correct' start of the JavaFX-app.

**Comment by fvarrui** [comment]
Please, could you try this?

```bash
T:\nba-produkt\target\nba-produkt>java -Djava.library.path="C:\WINDOWS\Sun\Java\bin" -jar nba-produkt.exe
```

> I found it in this [link](https://stackoverflow.com/a/56954853/12214543).

If this fixes your problem, you can specify `-Djava.library.path="C:\WINDOWS\Sun\Java\bin"` as an `vmArg` in JavaPackager.

**Comment by commi** [comment]
That works:

```
T:\nba-produkt\target\nba-produkt>jre\bin\java -Djava.library.path="C:\WINDOWS\Sun\Java\bin" -jar nba-produkt-2.0.0-SNAPSHOT-runnable.jar
C:\WINDOWS\Sun\Java\bin
15:20:08.135 [JavaFX Application Thread]
[… runs]
```

I have the JAR _not_ wrapped in the EXE here, thats. That is because doing this prevents reading resources from the JAR at runtime.

For completeness:
> jre\bin\java -jar nba-produkt-2.0.0-SNAPSHOT-runnable.jar

does fail the same way.

**Comment by commi** [comment]
> jre\bin\java -Djava.library.path="" -jar nba-produkt-2.0.0-SNAPSHOT-runnable.jar

This also works :)
Since this seems to be fixable with jvmArgs, i'll close this.

Thanks for your support!

**Comment by fvarrui** [comment]
> > jre\bin\java -Djava.library.path="" -jar nba-produkt-2.0.0-SNAPSHOT-runnable.jar
> 
> This also works :)
> Since this seems to be fixable with jvmArgs, i'll close this.
> 
> Thanks for your support!

Great!! I'm happy to read this 😃
