### ISSUE TITLE
Ability to use gradle's toolchain to execute jlink and other commands

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#111]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
The additition of an option to give JavaPackager a gradle toolchain to use in the execution of jlink and other JDK tools.

**What is the current behavior?**
Uses same JDK as Gradle is run with.

**What is the motivation / use case for changing the behavior?**
When updating to Java 16, if gradle is run with a Java 15 JDK, certain JRE generation processes (such as for linux distributions) will fail due to the invoked jlink commands failing to execute as they cannot correctly parse the java 16 modules. Running gradle with Java 16 fixes these issues. As such it would be useful to be able to give javapackager a toolchain to use when executing commands.

**Please tell us about your environment:**

- JavaPackager version: 1.6.0-SNAPSHOT
- OS version: Windows 10
- JDK version: 15/16
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @keastrid!
Currently there's an option (`jdkPath`) to specify a different JDK. It's intended for generating JRE's for different platforms than the current one, but not for different versions. 

https://github.com/fvarrui/JavaPackager/blob/84d6d8ba0f5d9998c4789544a1d9d249b95da0b6/src/main/java/io/github/fvarrui/javapackager/packagers/BundleJre.java#L48

I'm not really sure if I understand your proposal: maybe could be done replacing last line with something like this?

```java
File currentJdk = new File(System.getProperty("java.home"));
if (jdkToolchainPath != null && jdkToolchainPath.exists()) 
    currentJdk = jdkToolchainPath;
```

where `jdkToolchainPath` is a option of type `File`, or do you need to specify different paths for `jdeps` and `jlink`?

**Comment by keastrid** [comment]
I think changing: https://github.com/fvarrui/JavaPackager/blob/84d6d8ba0f5d9998c4789544a1d9d249b95da0b6/src/main/java/io/github/fvarrui/javapackager/packagers/BundleJre.java#L109

to something like:
```java
File jlink;
if (jdkToolchainPath != null && jdkToolchainPath.exists()) {
  jlink = new File(pathFromToolchain, "/bin/jlink").getAbsolutePath();   
} else {
  jlink = new File(currentJdk, "/bin/jlink").getAbsolutePath();   
}
```

The issue arises as `jlink` doesn't understand java versions newer than it, causing https://github.com/fvarrui/JavaPackager/blob/84d6d8ba0f5d9998c4789544a1d9d249b95da0b6/src/main/java/io/github/fvarrui/javapackager/packagers/BundleJre.java#L112-L121
to fail.

I'll have to double check, but from the gradle script side it doesn't seem feasible to extract the file or path to the jdk, though tasks can expose properties for it: https://docs.gradle.org/current/userguide/toolchains.html#specify_custom_toolchains_for_individual_tasks

**Comment by keastrid** [comment]
[Gradle has updated its documentation now](https://docs.gradle.org/current/userguide/toolchains.html#sec:plugins)

The `executionPath` or `metadata.installationPath` likely has the tools needed for building.

**Comment by fvarrui** [comment]
Fixed by PR 111
