### ISSUE TITLE
Bug Launch4j build failed

### ISSUE THREAD

**Issue by Manerr** [fvarrui/JavaPackager#113]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
mvn package, build failed

**Steps to reproduce the issue/enhancement:**

1. JDK 16/OpenJFX 16
2. Run JavaPackager

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
https://paste.ee/p/AVRpk

**Please tell us about your environment:**

- JavaPackager version: 1.5.1
- OS version: Windows 10
- JDK version: 16
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
This error comes from JUnit, maybe update some dependencies? My project only use OpenJFX maven libs.
![image](https://user-images.githubusercontent.com/1338257/121896025-2434ff80-cd21-11eb-9ff9-1ac1542d055b.png)

**Comment by Manerr** [comment]
Updating launch4j maven plugin could solve the problem
https://github.com/lukaszlenart/launch4j-maven-plugin/issues/127

**Comment by Manerr** [comment]
Oh seems to be already fix in https://github.com/fvarrui/JavaPackager/issues/108 
Just there is not JavaPackager release up to date :(

**Comment by fvarrui** [comment]
JavaPackager v1.6.0 released to Maven Central
