### ISSUE TITLE
Not loading icon file

### ISSUE THREAD

**Issue by dipeshpatidar** [fvarrui/JavaPackager#116]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
While specifying icnsFile in macConfig or any os icon is not loading 

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**
Should load app with icon specified in icnsFile

**What is the current behavior?**
Not loading app with icon

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
used plugin -> 
<plugin>
				<groupId>io.github.fvarrui</groupId>
				<artifactId>javapackager</artifactId>
				<version>1.6.0-SNAPSHOT</version>

				<configuration>
					<macConfig>
						<icnsFile>./assetsDir/mac/47icon.icns</icnsFile>
					</macConfig>
					<bundleJre>true</bundleJre>
					<mainClass>com.fourtysevenbillion.timesheet.Main</mainClass>
					<generateInstaller>true</generateInstaller>
					<jrePath>/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/</jrePath>
					<platform>mac</platform>
				</configuration>
				<executions>
					<execution>
						<id>bundling-for-mac</id>
						<phase>package</phase>
						<goals>
							<goal>package</goal>
						</goals>
						<configuration>
							<platform>mac</platform>
							<createTarball>true</createTarball>
							<jdkPath>/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk</jdkPath>
						</configuration>
					</execution>
				</executions>
			</plugin>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.6.0-SNAPSHOT
- OS version: macOs Catalina 10.15
- JDK version:11
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @dipeshpatidar!

It seems that this issue is related to [this one](https://github.com/fvarrui/JavaPackager/issues/114#issuecomment-873655277).

If so, it's fixed in issue-114 branch.  There's a workaround explained in the above comment.

I hope this helps.

Thanks!

**Comment by fvarrui** [comment]
I've made some changes to your plugin config:

1. It's not a good idea to embed a JDK with your app. Use a JRE instead, or let JavaPackager to generate it for you, removing this property: `<jrePath>/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/</jrePath>`

2. `jdkProperty` is neccesary only when you want to generate a JRE for another platform or Java version. If `/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk` is your JDK by default, you don't need this property.

3. A workaround for the icon issue: move `./assetsDir/mac/47icon.icns` to `./assets/mac/${name}.icns`, and remove `icnsFile` property.

```xml
<plugin>
       [...]
	<configuration>
		<bundleJre>true</bundleJre>
		<mainClass>com.fourtysevenbillion.timesheet.Main</mainClass>
		<generateInstaller>true</generateInstaller>
	</configuration>
	<executions>
		<execution>
			<id>bundling-for-mac</id>
			<phase>package</phase>
			<goals>
				<goal>package</goal>
			</goals>
			<configuration>
				<platform>mac</platform>
				<createTarball>true</createTarball>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Comment by dipeshpatidar** [comment]
1. Thanks for your valuable suggestions, i need jdk path because my default jdk is 1.8.

2.  Secondly i am facing issue with jspawnhelper, whenever i make a build i need to give 755 permissions to this file else my bash commands from the app dosent run. Is there any way i can give the permissions at the time of building process?

3. I will try the workaround of icon.

**Comment by dipeshpatidar** [comment]
removing jrePath gives me a error
![Screenshot 2021-07-07 at 10 26 21 AM](https://user-images.githubusercontent.com/21073895/124703238-8f808480-df0f-11eb-928f-606f03fc08de.png)

and removing both jdkPath and jrePath gives me this error 
![Screenshot 2021-07-07 at 10 39 34 AM](https://user-images.githubusercontent.com/21073895/124703319-b50d8e00-df0f-11eb-875d-b19f407f11fd.png)

**Comment by fvarrui** [comment]
> 2. Secondly i am facing issue with jspawnhelper, whenever i make a build i need to give 755 permissions to this file else my bash commands from the app dosent run. Is there any way i can give the permissions at the time of building process?

I've planned to split the packaging task into multiple tasks, so that the developer can orchestrate the packaging actions (build app, bundle jre, generate EXE, setup, MSI, DMG, PKG, DEB, ...) ... so, you can change file permissions or any other action between tasks. I'm not really sure if this is your problem. If it has to be done before/after `packaging`, you can achieve it with a Maven plugin.

**Comment by fvarrui** [comment]
> removing jrePath gives me a error
> ![Screenshot 2021-07-07 at 10 26 21 AM](https://user-images.githubusercontent.com/21073895/124703238-8f808480-df0f-11eb-928f-606f03fc08de.png)

The problem here is that `/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk` is not a valid JDK path, as `release` can not be found in this location. You have to use: `/Library/Java/JavaVirtualMachines/jdk-11.0.11.jdk/Contents/Home`.

> 
> and removing both jdkPath and jrePath gives me this error
> ![Screenshot 2021-07-07 at 10 39 34 AM](https://user-images.githubusercontent.com/21073895/124703319-b50d8e00-df0f-11eb-875d-b19f407f11fd.png)

The other problem is explained in [this issue](https://github.com/fvarrui/JavaPackager/issues/106). This happens because `snakeyaml` library is non-modular, but `com.fasterxml.jackson.dataformat.yaml` references `org.yaml.snakeyaml`, which doesn't exist (as module-info is not present in `snakeyaml` library). You can fix this embedding a full JRE, using `<customizedJre>false</customizedJre>`.

**Comment by fvarrui** [comment]
Closing this issue as it's related to #114, and it's fixed in [issue-114](https://github.com/fvarrui/JavaPackager/issues/114) branch.
