### ISSUE TITLE
Update to gradle-launch4j breaks some existing builds

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#119]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
This issue affects the issue-112 branch.

After implementing PR 118 into [this project ](https://github.com/keastrid/astroimagej), I noticed that the generated exe file does not run. No errors are logged when packaging. Forcing the build to use the old (current) gradle-launch4j build produces a correct exe. The most noticeable difference between the 2 exes is that the exe from the new generation is ~11 kb larger.

**Steps to reproduce the issue/enhancement:**

1. Run the windows packaging for the linked project after setting to use a new javapackager
2. Attempt to run exe

**What is the expected behavior?**
Generated exe functions

**What is the current behavior?**
Generated exe does not function

**Please tell us about your environment:**

- JavaPackager version: custom version implementing both PRs 118 and 117
- OS version:Windows 10
- JDK version:16
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Ok. as I asked to you in PR 118, do I have to downgrade gradle-launch4j to the previous version?

**Comment by keastrid** [comment]
This issue only appears with gradle-launch4j 2.5.0, so using the old version should work. I did only test with your fork though, if you'd like I can test with upstreams' 2.4.7

**Comment by fvarrui** [comment]
> This issue only appears with gradle-launch4j 2.5.0, so using the old version should work. I did only test with your fork though, if you'd like I can test with upstreams' 2.4.7

Ok, yes please!

**Comment by keastrid** [comment]
Upstream
2.5.0 -> builds, but exe doesn't work
2.4.8-9 -> fails to init. ConfigPersister due to reflection/xstream errors
2.4.7 -> fails to find the ConfigPersister class

Your fork of 2.4.7 does work, so I think using that would be easiest for now.

**Comment by fvarrui** [comment]
gradle-launch4j downgraded to 2.4.7 fork, and working as expected

**Comment by fvarrui** [comment]
Hi @keastrid!

I've replaced `io.github.fvarrui:gradle-launch4j:2.4.7` with `edu.sc.seis.launch4j:launch4j:2.5.1` in JavaPackager v1.6.4-SNAPSHOT. I've tried with Gradle 7.1.1+Java 17 and it seems to be working fine: EXE is being generated and runs. Please, if you experience any problems, reopen this issue. 

Thanks!
