### ISSUE TITLE
Allow use of maven-shade-plugin (bring-your-own-fat-jar)

### ISSUE THREAD

**Issue by jdimeo** [fvarrui/JavaPackager#12]
I already have the `maven-shade-plugin` configured exactly the way I want to manage packaging up the .jar with its dependencies. I would like the option of specifying my own packaged .jar and skip the step where your plugin packages the .jar for me.

I've committed example code to do this on my fork:
https://github.com/ElderResearch/JavaPackager/commit/6680a417a98d72444fd69a69515e0925c04b0795
Let me know if you want me to open a PR. thanks!

**Comment by fvarrui** [comment]
Hi J, 
thanks for your contribution. All are good ideas and improvements for JavaPackager.
Yes, open a PR for all your issues, please!

**Comment by fvarrui** [comment]
Fixed in [v0.8.8](https://github.com/fvarrui/JavaPackager/releases/tag/v0.8.8).
