### ISSUE TITLE
Allow for a "bootstrap" script to be run before application start

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#122]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
The ability to run a script before launching the application's java runtime.

**What is the motivation / use case for changing the behavior?**
When an application has its own update facility, it is useful especially in long lifetime applications to allow for the bundled jre to be updated, either on user demand or part of its normal update process, without forcing users to entirely reinstall the application. At least on windows, you cannot update the jvm while it is running, forcing the use of an "elevator" process, written as a shell script or some other application, to update it.

Rather than starting a new process on a timer to rename the folders (eg. `jre` -> `jre.old`, `jre.new` -> `jre`) and immediately shutting down the program, it would be more useful to have a script capable of doing so on program startup, hence a bootstrap script. 

I imagine others may have more uses for this feature.

**Please tell us about your environment:**

- JavaPackager version: 1.6.0
- OS version: Windows
- JDK version: 16
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @keastrid!

I've been thinking about this. On Mac and Linux I think it's relatively easy to implement the execution of a script at startup, since we use our own scripts to start the application. But it isn't like that in the case of Windows, where we have a binary generated with launch4j, and it doesn't have an option that allows us to execute anything at the beginning. Any suggestions? Maybe a batch file (converted to EXE and edited to have an icon and other metadata attached) which launch the bootstrap script and then the binary.

> Rather than starting a new process on a timer to rename the folders (eg. `jre` -> `jre.old`, `jre.new` -> `jre`) and immediately shutting down the program, it would be more useful to have a script capable of doing so on program startup, hence a bootstrap script.

Why do you think that this is not a good alternative?

**Comment by keastrid** [comment]
I don't think its a good alternative as, in my case of a jre updater, it essentially requires download -> unpack -> start timer immediately and shutdown, or wait for user confirmation and do the timer and shutdown. It is also easier to get the application into a bad state, as the process could be killed while it is running leaving the application seemingly unusable from a user perspective.

A startup script that can do so can more easily inspect the state of the working directory and determine how it should rename things, so it can recover from a failed move/rename by automatically reverting to the backup.

**Comment by fvarrui** [comment]
Work in progress in branch [issue-122](https://github.com/fvarrui/JavaPackager/tree/issue-122).

**Comment by fvarrui** [comment]
I've just implemented and tested this feature for Mac OS, and it seems to work fine.

you have to use `scripts.bootstrap` property:
```groovy
scripts {
    bootstrap = file('path/to/your/bootstrap.sh')
}
```

The specified bootstrap script is copied to `Contents/Resources/scripts` folder with execute permissions and run just before the app.

**Comment by fvarrui** [comment]
Also works on Linux!

**Comment by fvarrui** [comment]
I don't know how to implement this feature for Windows. Any suggestions would be welcome!

I think we need a separate EXE from the JVM, which has to be executed from the application, or use a BAT file as startup.

This is [how Google Chrome does it](https://omaha-consulting.com/google-omaha-tutorial-chrome-updater).

**Comment by keastrid** [comment]
A separate exe may be the better option, as things like IntelliJ software and Chrome use exes rather than scripts.

**Comment by fvarrui** [comment]
I managed to run a startup script on Windows. For this we need a VBS script and a shortcut pointing to it. The VBS script runs the bootstrap script and finally runs the binary. Shortcut can be configured with an icon. Installers also generate shortcuts pointing to the VBS script file.

**Comment by fvarrui** [comment]
Please, try this feature for all platforms as soon as you can, so I can release v1.6.0 to Maven Central. Thanks!!

**Comment by keastrid** [comment]
Thanks!
Tested with your HelloWorldGradle project.
Windows and linux work. On mac the app can't be opened - it may be a permissions issue as I'm building it on windows. I will need to test further.

**Comment by fvarrui** [comment]
Shortcuts must be generated by installers, as it's not possible to make them reference to relative paths, so It has no sense to package a pre-built shortcut with the app

**Comment by fvarrui** [comment]
> On mac the app can't be opened - it may be a permissions issue as I'm building it on windows. I will need to test further.

There was a bug that I just fixed. 
Thanks!

**Comment by fvarrui** [comment]
The problem was that the bootstrap script execute permissions were not set when packaging as tarball/zipball

**Comment by hectorqin** [comment]
I think  it's time to release v1.6.0!

**Comment by fvarrui** [comment]
JavaPackager v1.6.0 released to Maven Central
