### ISSUE TITLE
When packaging jdeps, there was a problem that non-essential packages could not be found 

### ISSUE THREAD

**Issue by 503203440** [fvarrui/JavaPackager#128]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

When I rely on a jar package, but this jar depends on other non-essential dependent packages, jdeps will have a "not found" error, which causes the packaging to stop. After testing, I found that --ignore was added in the process of jdeps -missing-deps can solve this problem

**Steps to reproduce the issue/enhancement:**

In the specific situation, I used hutool-all, which is a simple toolkit, but it introduces other non-essential classes.

**What is the expected behavior?**

**What is the current behavior?**

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
![image](https://user-images.githubusercontent.com/29830517/135708326-2404c6be-4186-48d7-8e82-8c53e1710d07.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:
1.4.2

- OS version:
 windows 10 

- JDK version:

 java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @503203440!

Issue fixed in [issue-128 branch](https://github.com/fvarrui/JavaPackager/tree/issue-128). You have to install JavaPackager 1.6.2-SNAPSHOT manually.

If it works fine for you, I'll release v1.6.2 to Maven Central asap.

**Comment by 503203440** [comment]
@fvarrui Ok i got it, thank you

**Comment by fvarrui** [comment]
JavaPackager v1.6.2 released to Maven Central!
It will be available in a few hours.
