### ISSUE TITLE
Allow packaging for different OS than host

### ISSUE THREAD

**Issue by jdimeo** [fvarrui/JavaPackager#13]
Instead of automatically packaging for the host OS, I would like to be able to specify which OS to build for. I've used a Windows host to build both a .exe and a Mac .app bundle. You can build more than one package with multiple executions of the plugin.

I've committed some code to do this on my fork:
https://github.com/ElderResearch/JavaPackager/commit/96bf664ba0764c0161dd9a280d0a16a1e1d3cbe0

This introduces a new platform configuration, one of:
`auto` (the default- current behavior)
`mac`
`linux`
`windows`

Let me know if you want me to open a PR

**Comment by fvarrui** [comment]
Hi,
I like how you refactored Mojo's `execute` method. It's cleaner than before.
Thanks!

**Comment by fvarrui** [comment]
And I’ve just realized that a customized JRE couldn’t be bundled

**Comment by fvarrui** [comment]
Fixed in [v0.8.8](https://github.com/fvarrui/JavaPackager/releases/tag/v0.8.8).
