### ISSUE TITLE
Dependencies not included in exe launch script?

### ISSUE THREAD

**Issue by almostobvious** [fvarrui/JavaPackager#133]
I'm submitting a…
- [ ] question

**Short description of the issue/suggestion:**
Hi there and thanks for a great tool. I have encountered a few potential issues (though this may be just not doing things right).

1. I can't use fat jars due to tricky class/content loading tricks some of the code is playing. But I would like to use a wrapped jar for the main project. So I use copyDependencies which do end up in lib/*.jar but seem to be missing in the launcher so exe fails to start. I can add every single jar to classpath option, but this is a looong list - 30+ dependencies in my project - so I was wandering if this is a bug or a config problem on my end?

2. Haven't been able to find any documentation and examples in particular for several configuration options - things like additionalModulePaths and additionalModules. What would these be used for and how?

**What is the expected behavior?**
Including all dependencies in the exe classpath when copyDependencies is set to true.

**What is the current behavior?**
Dependencies do not appear to be in the exe classpath when copyDependencies is set to true, though they can be listed manually in classpath.

**What is the motivation / use case for changing the behavior?**
Specifying dependencies manually in classpath is error prone and means dependency change needs to be done in several places.

**Please tell us about your environment:**

- JavaPackager version: 1.6.2
- OS version: Win 10, Linux Rocky 8, MacOS
- JDK version: 11
- Build tool: 
	- [ ] Maven

**Comment by fvarrui** [comment]
Hi @almostobvious!

> 1. I can't use fat jars due to tricky class/content loading tricks some of the code is playing. But I would like to use a wrapped jar for the main project. So I use copyDependencies which do end up in lib/*.jar but seem to be missing in the launcher so exe fails to start. I can add every single jar to classpath option, but this is a looong list - 30+ dependencies in my project - so I was wandering if this is a bug or a config problem on my end?

Could you share your POM or at least your plugin config, please?

> 2. Haven't been able to find any documentation and examples in particular for several configuration options - things like additionalModulePaths and additionalModules. What would these be used for and how?

Sorry, I don't have examples for all the plugin options, but I'd like to improve documentation. I use two sample projects for testing: [HelloWorldMaven](https://github.com/fvarrui/HelloWorldMaven) and [HelloWorldGradle](https://github.com/fvarrui/HelloWorldGradle). Also, in the [releases](https://github.com/fvarrui/JavaPackager/releases) section you can find when and why every feature was added. Maybe it could help!

- `additionalModulesPaths` is used to specify other directories within Java modules (`.jmod` files), where `jlink` could find the needed modules in order to generate a customized JRE (by default, JavaPackager only includes `{your_jdk}/jmods`). For example: a directory with JavaFX modules.
- `additionalModules` is used to specify additional modules to those found by `jdeps` after analyzing your code and its dependencies, so that later `jlink` can generate a reduced JRE including only these modules.

If you need help with any other specific option, don't hesitate to ask!

**Comment by almostobvious** [comment]
Hi again, thanks very much for your help so far! 

I have isolated the problem into a simple example project that can help reproduce the issue. See attached. Note - to build this you will need to create folder jdks/win/ and put contents of a jdk 11 there. 

Essentially this builds fine but when you run the exe it fails with: 

> Error: JavaFX runtime components are missing, and are required to run this application

I suspect it's missing javafx-*-win.jar which are the platform dependent implementations, even though they are present after installation so clearly recognised as dependencies.

May well be something silly that I am doing... :(

Many thanks!

[experiment.zip](https://github.com/fvarrui/JavaPackager/files/7470016/experiment.zip)

**Comment by almostobvious** [comment]
After some experimentation, I was able to run the runnable jar with the following command:

> runtime\bin\java --module-path libs --add-modules=javafx.graphics -jar "Test app-1.0.0-SNAPSHOT-runnable.jar"

Omitting either module-path or add-modules results in failure (though two different failures).

If there is a good way to overcome this with config that would be great. But I expect a good workaround can be using vmArgs.

**Comment by almostobvious** [comment]
Ok, all works now with vmArgs. I used --upgrade-module-path instead of --module-path which means I don't need --add-modules.

**Comment by almostobvious** [comment]
If it helps anybody, the updated zip is attached showing vmArgs example.

[experiment.zip](https://github.com/fvarrui/JavaPackager/files/7474210/experiment.zip)

**Comment by fvarrui** [comment]
Hi @almostobvious!
I've been trying your `experiment` and it seems to be working fine. 
Has you managed to fix your issue?

**Comment by almostobvious** [comment]
Hi thanks for checking - the second zip will work - it has the fix with vmArgs. The first zip might work if you have JavaFX set up on your machine, but will likely fail otherwise - at least I think this could be an explanation...

**Comment by fvarrui** [comment]
Hi @almostobvious!

I published [here](https://github.com/fvarrui/testapp-dsp-bundling-experiment) your `experiment`, and it's working. It generates installers with an embedded JRE for different platforms. I hope you don't mind! 

Thanks!

**Comment by almostobvious** [comment]
Hey looks great, especially -Djavafx.platform=xxx which I wasn't aware was possible. Many thanks!

**Comment by fvarrui** [comment]
So, is it your original issue fixed? Do you think we can close this?

**Comment by almostobvious** [comment]
Of course - thanks
