### ISSUE TITLE
Windows Icon file is ignored?

### ISSUE THREAD

**Issue by dkoding** [fvarrui/JavaPackager#134]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

It seems the gradle winConfig ignores my icon property

**Steps to reproduce the issue/enhancement:**

Create a gradle task like this:

task createInstaller(type: PackageTask, dependsOn: proguard) {
    ...
    bundleJre = true
    generateInstaller = true
    administratorRequired = false
    runnableJar = file('build/libs/my.jar')
    jrePath = file('.../.jdks/liberica-1.8.0_312')
    assetsDir = file('src/main/resources')
    licenseFile = file("LICENSE.txt")
    winConfig {
        icoFile =  file('icon.ico')
    }
}

**What is the expected behavior?**

Finished application should have the supplied icon

**What is the current behavior?**

Finished application has a default icon, and the following error is shown during packaging:

```
Creating app ...
    Initializing packager ...
        PackagerSettings [outputDirectory=C:\work\...\build, licenseFile=C:\work\...\LICENSE.txt, iconFile=**null**, generateInstaller=true ...
    Packager initialized!
```

Then, later in the process I get this:

     Copying resource [/windows/default-icon.ico] to file [C:\work\...\build\assets\....ico]

- JavaPackager version: 1.6.2
- OS version: Windows 10
- JDK version: 8
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @dkoding!
Have you managed to fix this issue?
