### ISSUE TITLE
Unable to generate installer for windows from ubuntu

### ISSUE THREAD

**Issue by rdas6313** [fvarrui/JavaPackager#136]
I'm submitting a…

- [x] bug report

**Short description of the issue/suggestion:**
i am trying to generate installer for windows from my ubuntu machine.whenever i run mvn package, it shows " Setup installer cannot be generated due to the target platform (windows) is different from the execution platform (linux)! " and after when .exe file created and i run it in windows machine it shows "A JNI error has occurred, please check your installation and try again".

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

>[INFO] Generating installers ...
[INFO]     Initializing packager ...
[INFO]         PackagerSettings [outputDirectory=/home/rdas6313/Documents/Sem Project/desktop_download_manager/target, licenseFile=null, iconFile=/home/rdas6313/Documents/Sem Project/desktop_download_manager/target/assets/desktop_download_manager.ico, generateInstaller=true, mainClass=com.rdas6313.AppStarter, name=desktop_download_manager, displayName=desktop_download_manager, version=1.0, description=desktop_download_manager, url=null, administratorRequired=false, organizationName=ACME, organizationUrl=, organizationEmail=null, bundleJre=true, customizedJre=true, jrePath=/home/rdas6313/Music/jre, jdkPath=/usr/lib/jvm/java-11-openjdk-amd64, additionalResources=[/home/rdas6313/Documents/Sem Project/desktop_download_manager/target/assets/desktop_download_manager.ico], modules=[], additionalModules=[], platform=windows, envPath=null, vmArgs=[], runnableJar=null, copyDependencies=true, jreDirectoryName=jre, winConfig=WindowsConfig [icoFile=null, headerType=gui, companyName=ACME, copyright=ACME, fileDescription=desktop_download_manager, fileVersion=1.0.0.0, internalName=desktop_download_manager, language=null, originalFilename=desktop_download_manager.exe, productName=desktop_download_manager, productVersion=1.0.0.0, trademarks=null, txtFileVersion=1.0, txtProductVersion=1.0, disableDirPage=false, disableProgramGroupPage=true, disableFinishedPage=true, disableRunAfterInstall=true, createDesktopIconTask=true, generateSetup=true, generateMsi=true, generateMsm=false, msiUpgradeCode=7c4cab05-391f-475b-82b7-1c51b224ea8c, wrapJar=true, setupLanguages={english=compiler:Default.isl}, setupMode=installForAllUsers, signing=null, registry=Registry [entries=[]]], linuxConfig=null, macConfig=null, createTarball=false, createZipball=false, extra=null, useResourcesAsWorkingDir=true, assetsDir=/home/rdas6313/Documents/Sem Project/desktop_download_manager/assets, classpath=null, jreMinVersion=null, manifest=null, additionalModulePaths=[], fileAssociations=[], packagingJdk=/usr/lib/jvm/java-11-openjdk-amd64, scripts=Scripts [bootstrap=null, preInstall=null, postInstall=null]]
[INFO]     Packager initialized!
[INFO]     
[INFO]     Generating Setup installer...
[WARNING]         Setup installer cannot be generated due to the target platform (windows) is different from the execution platform (linux)!
[WARNING]         Setup installer artifact generation skipped!
[WARNING]     Setup installer NOT generated!!!
[INFO]     
[INFO]     Generating MSI merge module...
[WARNING]         MSI merge module cannot be generated due to the target platform (windows) is different from the execution platform (linux)!
[WARNING]         MSI merge module artifact generation skipped!
[WARNING]     MSI merge module NOT generated!!!
[INFO]     
[INFO]     Generating MSI installer...
[WARNING]         MSI installer cannot be generated due to the target platform (windows) is different from the execution platform (linux)!
[WARNING]         MSI installer artifact generation skipped!
[WARNING]     MSI installer NOT generated!!!
[INFO]     
[INFO] Installers generated! []
[INFO] 
[INFO] Creating bundles ...
[INFO] Bundles created!
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:40 min
[INFO] Finished at: 2021-12-12T14:35:58+05:30
[INFO] ------------------------------------------------------------------------

**Please tell us about your environment:**

- JavaPackager version:1.6.2
- OS version: ubuntu 18.04
- JDK version: 11
- Build tool: 
	- [x] Maven 
	- Pom.xml:  
```xml
	  <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>com.rdas6313.AppStarter</mainClass>
                            <bundleJre>true</bundleJre>
                            <customizedJre>false</customizedJre>
                        </configuration>
                    </execution>
                    <execution>
                        <id>bundling-for-windows</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <platform>windows</platform>
                            <mainClass>com.rdas6313.AppStarter</mainClass>
                            <bundleJre>true</bundleJre>
                            <generateInstaller>true</generateInstaller>
                            <jrePath>/home/rdas6313/Music/jre</jrePath>
                            <winConfig>
                                <generateSetup>true</generateSetup>
                                <headerType>gui</headerType>
	                            <wrapJar>true</wrapJar>
                                <setupMode>installForAllUsers</setupMode>
                                <setupLanguages>
		                            <english>compiler:Default.isl</english>
                                </setupLanguages>
                                <disableDirPage>false</disableDirPage>
                                <disableFinishedPage>true</disableFinishedPage>
	                            <createDesktopIconTask>true</createDesktopIconTask>
                            </winConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by fvarrui** [comment]
Hi @rdas6313!

> i am trying to generate installer for windows from my ubuntu machine.whenever i run mvn package, it shows " Setup installer cannot be generated due to the target platform (windows) is different from the execution platform (linux)! " 

Windows Setup and MSI intallers only can be generated from Windows, as it needs Inno Setup and WiX Toolset tools. JavaPackager can package your app for Windows from Linux, but not the installers.

> and after when .exe file created and i run it in windows machine it shows "A JNI error has occurred, please check your installation and try again".

I've seen that you are bundling your own JRE when packaging for Windows from Linux. Is this JRE for Windows?

**Comment by rdas6313** [comment]
Hello @fvarrui 
> I've seen that you are bundling your own JRE when packaging for Windows from Linux. Is this JRE for Windows?

Yes.this is for windows.
Hey, but after packaging is done ,it should run on windows right ? but it is not running.it shows 

> "A JNI error has occurred, please check your installation and try again".

Can you help me with this ? can you tell me the steps to run my app in windows machine.

**Comment by rdas6313** [comment]
Hey @fvarrui 
My app is running perfectly by Openjdk 11 runtime.Could you please tell me how can i bundle this jre for windows packaging ? is it possible ?

**Comment by fvarrui** [comment]
Hi @rdas6313!
You can also try letting the plugin generate a custom JRE for your app. You just have to set `jdkPath` property with the path to a Windows JDK, and use `customizedJre=true` for a reduced JRE or `false` to embed a full one.

**Comment by fvarrui** [comment]
I've been thinking about your problem and it could be that you are compiling your code for a higher version of Java than the JRE you are embedding. The only way I've managed to reproduce your problem is by doing this.

![image](https://user-images.githubusercontent.com/4354486/145792157-01aef5bd-e008-49cd-a8d0-1c0b2521f5ab.png)

```bash
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/fvarrui/helloworld/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

> java.lang.UnsupportedClassVersionError: io/.../Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

You can make sure by setting `winConfig.headerType=console` when packaging, and then run your EXE on Windows, so you get a full trace of the error in the console.
