### ISSUE TITLE
Allow custom VM arguments (e.g. -Xmx4G)

### ISSUE THREAD

**Issue by jdimeo** [fvarrui/JavaPackager#14]
Add a parameter to allow for custom VM arguments.

I've committed an example here on my fork:
https://github.com/ElderResearch/JavaPackager/commit/3be0faa8e68a81c2cbac0c387cbbf5c561be2fbe

Let me know if you want me to open a PR

**Comment by fvarrui** [comment]
Fixed in [v0.8.8](https://github.com/fvarrui/JavaPackager/releases/tag/v0.8.8).

**Comment by jdimeo** [comment]
Thank you @fvarrui ! Sorry I did not get around to formally opening a PR. Glad you found these changes useful.

**Comment by jdimeo** [comment]
@fvarrui this appears not to work with the new release as the VM args aren't passed through the new `startup` and stub. I'll look at it myself when I get the chance but it means my SWT app doesn't work (since I need to pass `-XstartOnFirstThread`). thanks!

**Comment by fvarrui** [comment]
Now, using stub, it takes VM args from Info.plist. Please, could you share this file?

**Comment by jdimeo** [comment]
You're right! I do see them here:
```
<key>JVMOptions</key>
<array>
	<string>-Xmx1024M -XstartOnFirstThread</string>
</array>
```

I think the problem is that it may be ignoring that because it's space-separated instead of a separate `<string>` entry. 

Do you think we should split on space in the mojo when filling out the template? or is that too opinionated? 
The space separated args worked for the old stub and work for Launch4j and https://github.com/brianm/really-executable-jars-maven-plugin which are the other two plugins I'm using (I'm only using this one for Macs right now- that might change in the future!)

**Comment by fvarrui** [comment]
Ok @jdimeo, how are you specifying VM args in your POM? And ... can you try this?

Edit Info.plist and modify as follows:
```xml
<key>JVMOptions</key>
<array>
	<string>-Xmx1024M</string>
        <string>-XstartOnFirstThread</string>
</array>
```
and run your app.

**Comment by jdimeo** [comment]
So these VM args are being set in a parent POM via a property. I've fixed my usage to properly use the array of arguments and that fixes it!
```
<vmArgs>
	<vmArg>-Xmx${application.maxHeapMB}M</vmArg>
	<vmArg>${application.vmArgs}</vmArg>
</vmArgs>
```

I'll have to deal with it on my end if I want to put more than one argument into `${application.vmArgs}`. Thank you for your help- false alarm.

**Comment by fvarrui** [comment]
You’re welcome @jdimeo! I’ll be here for whatever you need!!
