### ISSUE TITLE
[Question]: Is it necessary to codesign app for Mac when not using installer?

### ISSUE THREAD

**Issue by Ali-RS** [fvarrui/JavaPackager#151]
Hello!

I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

I am not a Mac user so I'm curious to know if it is necessary to codesign and notarize my app to run it on Mac? 

I am packaging my app from Linux to other platforms (Mac, Windows) without an installer (`generateInstaller = false`), using JavaPackager Gradle plugin. Will the app runs fine on Mac OS or I must codesign and notarize it to run?

Regards

**Comment by fvarrui** [comment]
Hi @Ali-RS!
Yes, it would be recommended so that the users of your app don't have to change the configuration of their systems to allow its execution.

**Comment by fvarrui** [comment]
AFAIK you need an Apple developer cert in order to sign and notarize your app.

**Comment by Ali-RS** [comment]
Ok

Thanks so much for the help.
