### ISSUE TITLE
Pass Through Configuration to Launch4J for Header Type Console?

### ISSUE THREAD

**Issue by safferyj** [fvarrui/JavaPackager#154]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other - support request

**Short description of the issue/suggestion:**

Is it possible to pass through configuration to Launch4J? Specifically, I have a console app and would like stdout to appear in the console. I see that Launch4J has an option for this with headerType console in its configuration file.

**Steps to reproduce the issue/enhancement:**

1. Make a simple app with console output
2. Use fvarrui/JavaPackager to package and create installers
3. Install the simple app
4. Run the simple app - nothing appears on the console
5. Run the simple app with output redirected to a file - expected output is in the file

**What is the expected behavior?**

I believe this is because Launch4J defaults to header type gui which has no support for console output.  

I would like to be able to pass through a configuration to Launch4J which sets the header type to console. 

**What is the current behavior?**

It does not seem to be possible to pass through a configuration to Launch4J.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

No

**What is the motivation / use case for changing the behavior?**

To be able to use fvarrui/JavaPackager to package console apps with console output.

**Please tell us about your environment:**

- JavaPackager version: 1.6.3
- OS version: Windows 10.0.19043.1526
- JDK version: 17.0.2
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

Thank you for this plugin and your support on my previous issue.

**Comment by safferyj** [comment]
It also seems that whenever the resulting executable is run, the working directory is set to its installation folder rather than being the location it is run from, as typically expected. I believe this is due to Launch4J chdir configuration defaulting to or being set to ".".  Similarly, I would like to be able to override this and set Launch4J's chdir configuration to empty string / null so that the typical working directory behaviour is seen, that is the program can read and write in the directory where it is executed.

**Comment by fvarrui** [comment]
Hi @safferyj!
I think you need to use next properties:
```xml
<winConfig>
    <headerType>console</headerType>
</winConfig>
<useResourcesAsWorkingDir>false</useResourcesAsWorkingDir>
```

**Comment by safferyj** [comment]
Perfect, thank you. Everything now works well.

**Comment by fvarrui** [comment]
Great!!
