### ISSUE TITLE
How to package a default .l4j.ini file?

### ISSUE THREAD

**Issue by ogerardin** [fvarrui/JavaPackager#157]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [X] other

**Short description of the issue/suggestion:**
The doc says that [you can pass additional options to the JVM](https://github.com/fvarrui/JavaPackager#additional-jvm-options-at-runtime) by putting a file named `${appname}.l4j.ini` next to the exe (Windows, Linux) or in the Resources folder (Mac).
Can you provide an example of how to package a default .l4j.ini so that it is correctly placed (for all all platforms)?

Thanks

**Comment by fvarrui** [comment]
Hi @ogerardin!
You have to create a file called `${name}.l4j.ini`, for example, in the root of your project, with a content similar to this:
```ini
-Dswing.aatext=true
-Dsomevar="%SOMEVAR%"
-Xms16m
```
> An VM argument per line.

And then bundle this file with your app using next property:
```xml
<additionalResources>
    <additionalResource>${name}.l4j.ini</additionalResource>
</additionalResources>
```

Last property copies the specified file next to the EXE/binary on Windows/Linux, and in `Resources` folder on MacOS.

**Comment by ogerardin** [comment]
Perfect, I'll try later!
I suggest you also add this to the doc :)

Thanks

**Comment by fvarrui** [comment]
Docs upgraded in devel branch.
