### ISSUE TITLE
[Windows] How to avoid "Windows protected your PC" dialog?

### ISSUE THREAD

**Issue by ogerardin** [fvarrui/JavaPackager#160]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [X] other

**Short description of the issue/suggestion:**
When running the installer EXE or the MSI, Windows 10 displays a big unsettling dialog saying "Windows protected your PC / Running this app might put your PC at risk". 
You can  bypass and "Run anyway" but it will probably scare away a lot of users. 
How to make Windows NOT display this?

**Steps to reproduce the issue/enhancement:**

1. Configure JavaPackager to generate EXE or MSI for Windows
2. Open the EXE or MSI on Windows 10

**What is the expected behavior?**
Installer starts

**What is the current behavior?**
This dialog appears
<img width="537" alt="Screenshot 2022-02-26 at 22 51 43" src="https://user-images.githubusercontent.com/110559/155860530-4dfa8083-79b2-4a39-90d4-775aa94be4ed.png">

**Please tell us about your environment:**

- JavaPackager version: 1.6.3
- OS version: Windows 10
- JDK version: 17
- Build tool: 
	- [X] Maven 
	- [ ] Gradle

**Comment by ogerardin** [comment]
Forgot this: after downloading the EXE, Chrome also displays a message that will discourage people from opening the file:
<img width="422" alt="Screenshot 2022-02-26 at 23 22 41" src="https://user-images.githubusercontent.com/110559/155860964-83e2c74a-ec0f-4e43-a0e4-82de553da18b.png">

All this is really making me wonder if providing a native installation method wasn't too ambitious and if i should stick to a basic ZIP :(

**Comment by fvarrui** [comment]
Hi @ogerardin!
You have to sign your app with a digital certificate issued by an issuing authority recognized by Windows.  It's possible to create your own digital certificate, without a root, but your users would have to install your certificate on their system before installing your apps so that message does not appear

**Comment by fvarrui** [comment]
There are properties to automate this:
https://github.com/fvarrui/JavaPackager/blob/master/docs/windows-specific-properties.md#signing-properties

**Comment by ogerardin** [comment]
> You have to sign your app with a digital certificate issued by an issuing authority recognized by Windows. 

I was afraid so. Do you have any recommandation on how to get such a certificate for this purpose?

**Comment by fvarrui** [comment]
> Do you have any recommandation on how to get such a certificate for this purpose?

No, sorry. But I've been researching a bit and found this: https://ssl.comodo.com/code-signing-certificates#:~:text=Code%20Signing%20provides%20authentication%20to,hacked%20since%20it%20was%20signed.

There are more certification authorities, and maybe one meets your needs.

**Comment by fvarrui** [comment]
> Too expensive for free stuff :)

I agree! :)
