### ISSUE TITLE
Resulting .exe will not run

### ISSUE THREAD

**Issue by EasyG0ing1** [fvarrui/JavaPackager#163]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [X] other

**Short description of the issue/suggestion:**
I tried a very simple JavaFX program to see if I could get it to compile into a self contained .exe and though it did kick out an .exe, it will not run. It does not provide an error as to why it won't run either.

**Steps to reproduce the issue/enhancement:**

Using IntelliJ, here is the Main class:

```[Java]
package com.simtechdata.helloworld;

import javafx.application.Application;
import javafx.stage.Stage;

public class Main extends Application {
	@Override public void start(Stage primaryStage) throws Exception {
		new Form();
	}

	public static void main(String[] args) {
		launch();
	}
}

```

Here is the Form class:

```[Java]
package com.simtechdata.helloworld;

import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class Form {

	public Form() {
		start();
	}

	private void start() {
		AnchorPane ap = new AnchorPane();
		VBox vbox = new VBox();
		Label label = new Label("Click The Button");
		Label label2 = new Label();
		Button button = new Button("Click");
		vbox.getChildren().setAll(label,label2,button);
		ap.getChildren().add(vbox);
		button.setOnAction(e->{
			label2.setText("Hello World!");
		});
		Stage stage = new Stage();
		Scene scene = new Scene(ap);
		stage.setScene(scene);
		stage.show();
		stage.getScene().getWindow().centerOnScreen();
	}
}
```

Here is the POM file:

```[xml]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.simtechdata</groupId>
    <artifactId>HelloWorld</artifactId>
    <version>1.0</version>
    <name>HelloWorld</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.8.2</junit.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>17.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>17.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-assembly-plugin</artifactId>
            <version>3.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.wixtoolset</groupId>
            <artifactId>wix-toolset</artifactId>
            <version>3.11.1</version>
        </dependency>
        <dependency>
            <groupId>io.github.fvarrui</groupId>
            <artifactId>javapackager</artifactId>
            <version>1.6.4</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.4</version>
                <configuration>
                    <bundleJre>true</bundleJre>
                    <mainClass>com.simtechdata.helloworld.Main</mainClass>
                    <generateInstaller>true</generateInstaller>
                    <administratorRequired>false</administratorRequired>
                    <platform>windows</platform>
                </configuration>
                <executions>
                    <execution>
                        <id>bundling-for-windows</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <platform>windows</platform>
                            <createZipball>true</createZipball>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <executions>
                    <execution>
                        <!-- Default configuration for running with: mvn clean javafx:run -->
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>com.simtechdata.helloworld/com.simtechdata.helloworld.Main</mainClass>
                            <launcher>app</launcher>
                            <jlinkZipName>app</jlinkZipName>
                            <jlinkImageName>app</jlinkImageName>
                            <noManPages>true</noManPages>
                            <stripDebug>true</stripDebug>
                            <noHeaderFiles>true</noHeaderFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

```

I **can** run it from the command line by issuing ```mvn JavaFX:run```

But when I run ```mvn clean compile``` I get these errors:

```
[ERROR] 'iscc' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
[ERROR] Setup installer generation failed due to: Command execution failed: iscc /OC:\Users\Michael\IdeaProjects\HelloWorld\target /FHelloWorld_1.0 C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.iss
[ERROR] org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: iscc /OC:\Users\Michael\IdeaProjects\HelloWorld\target /FHelloWorld_1.0 C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.iss

[ERROR] 'candle' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
[ERROR] MSI merge module generation failed due to: Command execution failed: candle -out C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wixobj C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wxs
[ERROR] org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: candle -out C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wixobj C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wxs


[ERROR] 'candle' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
[ERROR] MSI installer generation failed due to: Command execution failed: candle -out C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wixobj C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wxs
[ERROR] org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: candle -out C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wixobj C:\Users\Michael\IdeaProjects\HelloWorld\target\assets\HelloWorld.msm.wxs
```

Yet in spite of those errors, the command completes successfully 

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.469 s
[INFO] Finished at: 2022-03-08T18:54:37-08:00
[INFO] ------------------------------------------------------------------------
```

And I get an .exe file but when I try to run it either via CMD shell or by double-clicking on it, it simply does nothing at all.

Is there something I'm missing perhaps in my POM file?

**Please tell us about your environment:**

- JavaPackager version: 1.6.4
- OS version: Windows 11
- JDK version: 17.0.2
- Build tool: 
	- [X] Maven

**Comment by AntoninHuaut** [comment]
According to [#generated-artifacts](https://github.com/fvarrui/JavaPackager#generated-artifacts) , you need :
- Inno Setup for the target exe file.
- WiX Toolset for the target files msi and msm.

Exe and msi are created by default:
![image](https://user-images.githubusercontent.com/1338257/157419499-792d2a28-b119-44d7-8fda-53682adda458.png)

**Comment by fvarrui** [comment]
Hi @EasyG0ing1!

First of all, as @AntoninHuaut has explained, the problems with `iscc` and `candle` commands are because you have to install Inno Setup and Wix Toolset in your systems. You can follow this [guide](https://github.com/fvarrui/JavaPackager/blob/master/docs/windows-tools-guide.md). In case you have already installed these tools and problem persists, it's because these tools are not in the PATH environment variable.

And as for the EXE not running, you can try the following, in order to your EXE prints in the console any error or stacktrace, so you can see what's happening:

- Add the next property to JavaPackager config:
```xml
<winConfig>
    <headerType>console</headerType>
</winConfig>
```

> If the problem is that when you start the application it can't find the JavaFX components, there is a little trick for that

**Comment by fvarrui** [comment]
You also can take a look to this [issue](https://github.com/fvarrui/JavaPackager/issues/35).

**Comment by EasyG0ing1** [comment]
@fvarrui - So here is an interesting turn of events ... I got Inno installed without any issues... the wix tool set was a different story, but after manually downloading and installing dotnet 6.5, wix finally installed.

It left me with an environment variable just called WIX which points to the WIX folder just above the bin folder. However, I put the wix folder WITH the bin path into my main PATH statement... and I also rebooted.

NOW, when I issue ```mvn clean compile``` it processes WAY TOO QUICKLY then just says it was a success. Here is the output:
```
[INFO] ---------------------< com.simtechdata:HelloWorld >---------------------
[INFO] Building HelloWorld 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.github.fvarrui:launch4j:jar:2.5.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ HelloWorld ---
[INFO] Deleting C:\Users\Michael\IdeaProjects\HelloWorld\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HelloWorld ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ HelloWorld ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to C:\Users\Michael\IdeaProjects\HelloWorld\target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.433 s
[INFO] Finished at: 2022-03-10T13:04:37-08:00
[INFO] ------------------------------------------------------------------------
```

It no longer produces any exe's NOR any installers of any kind. The end folder structure from underneath target is:
- classes
- generated-sources
- maven-status

And that is all... any ideas?

**Comment by EasyG0ing1** [comment]
I should add, that I've never successfully built any self-executing artifacts before, much less any that also contains the JRE ... but that's mainly because I've never found a document that teaches how to do it with any kind of dedication to helping the audience understand exactly what it is to create these artifacts and which programs specifically address each part of that process... and with Java 9+ - now we have to be concerned with our module-info file and how that might play a role in getting these artifacts kicked out ... but based on what I have read, it seems to me that simply creating self-executing java programs as well as the same with the added JRE could use a book dedicated to teaching just that part of Java.

So in light of this truth, I fear I am ill-equipped to wield this plug-in where I should otherwise have some understanding of what I'm trying to make here to where I might be able to know what it is I'm missing. 

And I do apologize for my ignorance ... I've looked all over the web off and on for a long time now, looking for a good source to learn this aspect of Java but all I seem to find are quick and dirty examples that never depart enough knowledge to where I could apply the methods to my own code. Yesterday, I dedicated more time to learning this when I stumbled across this plugin, which looks to have a lot of promise in terms of simplicity ... if only I knew what I didn't know ... so I could ask the right questions...

**Comment by fvarrui** [comment]
Hi @EasyG0ing1!

> @fvarrui - So here is an interesting turn of events ... I got Inno installed without any issues... the wix tool set was a different story, but after manually downloading and installing dotnet 6.5, wix finally installed.
> 
> It left me with an environment variable just called WIX which points to the WIX folder just above the bin folder. However, I put the wix folder WITH the bin path into my main PATH statement... and I also rebooted.
> 

You could install Inno Setup and Wix Toolset using Chocolatey Package Manager, for example. It's very easy and is explained in docs. It sets PATH environment variable in the right way.

If you wanted to now if Inno Setup is right installed just run `iscc` command from CMD. Do the same for Wix running `candle`. If both commands prints something different than `command nota found


> NOW, when I issue `mvn clean compile` it processes WAY TOO QUICKLY then just says it was a success. Here is the output:
> 
> ```
> [INFO] ---------------------< com.simtechdata:HelloWorld >---------------------
> [INFO] Building HelloWorld 1.0
> [INFO] --------------------------------[ jar ]---------------------------------
> [WARNING] The POM for io.github.fvarrui:launch4j:jar:2.5.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ HelloWorld ---
> [INFO] Deleting C:\Users\Michael\IdeaProjects\HelloWorld\target
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ HelloWorld ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 0 resource
> [INFO]
> [INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ HelloWorld ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 3 source files to C:\Users\Michael\IdeaProjects\HelloWorld\target\classes
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  2.433 s
> [INFO] Finished at: 2022-03-10T13:04:37-08:00
> [INFO] ------------------------------------------------------------------------
> ```
> 
> It no longer produces any exe's NOR any installers of any kind. The end folder structure from underneath target is:
> 
> * classes
> * generated-sources
> * maven-status
> 
> And that is all... any ideas?
> 
> Edit: I'm not exactly sure why this happened, but when I did a `mvn verify`, it then all of a sudden started compiling everything it needed ... it compiled the JRE, it built the various EXEs and it even made what looks like a couple of installers ... and when I used the MSI installer, it only gave me one window then it went to town installing the exe that won't run at the moment.

**Comment by fvarrui** [comment]
Sorry, I closed accidentally

**Comment by fvarrui** [comment]
> I should add, that I've never successfully built any self-executing artifacts before, much less any that also contains the JRE ... but that's mainly because I've never found a document that teaches how to do it with any kind of dedication to helping the audience understand exactly what it is to create these artifacts and which programs specifically address each part of that process... and with Java 9+ - now we have to be concerned with our module-info file and how that might play a role in getting these artifacts kicked out ... but based on what I have read, it seems to me that simply creating self-executing java programs as well as the same with the added JRE could use a book dedicated to teaching just that part of Java.
> 

Don't worry about this, JavaPackager is here to free you from all those tedious and repetitive tasks. Or if you want to learn more about this, you have the source code, as JavaPackager is open source.

> So in light of this truth, I fear I am ill-equipped to wield this plug-in where I should otherwise have some understanding of what I'm trying to make here to where I might be able to know what it is I'm missing.
> 
> And I do apologize for my ignorance ... I've looked all over the web off and on for a long time now, looking for a good source to learn this aspect of Java but all I seem to find are quick and dirty examples that never depart enough knowledge to where I could apply the methods to my own code. Yesterday, I dedicated more time to learning this when I stumbled across this plugin, which looks to have a lot of promise in terms of simplicity ... if only I knew what I didn't know ... so I could ask the right questions...

Do you have an example project on Git which I can use to explain to you how to use JavaPackager?

**Comment by EasyG0ing1** [comment]
@fvarrui  It seems that everything is working, except when I run the executable, I get this familiar error:

```Error: JavaFX runtime components are missing, and are required to run this application```

Do I need to explicitly reference the dependencies so that they get compiled into the artifacts?

> Do you have an example project on Git which I can use to explain to you how to use JavaPackager?

As a matter of fact, the whole reason I'm trying to learn how to do this, is so I can create platform unique installers for [this project](https://github.com/RedmondSims/GistFX).

**Comment by fvarrui** [comment]
> You also can take a look to this [issue](https://github.com/fvarrui/JavaPackager/issues/35).

Please, take a look!

**Comment by fvarrui** [comment]
I'm sorry ... better this link! 
https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530

**Comment by EasyG0ing1** [comment]
@fvarrui OK, Creating a launcher class solved the error I was getting and now the executable runs. It does kick out a warning on the command line 

```WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2d89845b'```

Not sure what that's about since this is a basic hello world program as simple as it gets.

Also, the executable, when executed by double-clicking, brings up a DOS-style CMD window which stays up while the program is running. Is this normal behavior or can it be configured so that the window goes away when the program is running?

**Comment by EasyG0ing1** [comment]
@fvarrui 

Another question: Am I correct in assuming that the first <configuration> tag in the plugin will apply those settings to all <executions> underneath it, unless specifically overridden by a different <configuration> tag within a given <execution> ?

**Comment by fvarrui** [comment]
> @fvarrui OK, Creating a launcher class solved the error I was getting and now the executable runs. It does kick out a warning on the command line
> 
> `WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @2d89845b'`
> 
> Not sure what that's about since this is a basic hello world program as simple as it gets.
> 
> Also, the executable, when executed by double-clicking, brings up a DOS-style CMD window which stays up while the program is running. Is this normal behavior or can it be configured so that the window goes away when the program is running?

As you found what happened with your EXE, now you can set `headerType` to `gui`, or simply remove this property.

**Comment by fvarrui** [comment]
> @fvarrui
> 
> Another question: Am I correct in assuming that the first `<configuration>` tag in the plugin will apply those settings to all `<executions>` underneath it, unless specifically overridden by a different `<configuration>` tag within a given `<execution>` ?

Yes, that configuration is shared with all executions.

**Comment by fvarrui** [comment]
Hi @EasyG0ing1!
May I close this issue?

**Comment by EasyG0ing1** [comment]
@fvarrui Sure ☺

**Comment by fvarrui** [comment]
Great! Thanks
