### ISSUE TITLE
Code sign error : bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by saulhidalgoaular** [fvarrui/JavaPackager#166]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

I tried to generate an installer for mac and it gave this error while trying to sign the man folder of the jre. It used a MacAir computer, with Java 8, I think 1.8.332. I have specified a custom JRE path, and I have choise the default JRE that comes with MacOS. However, when doing the signature process, it gave this error when it tried to compile a file in the man folder..

Code sign error : bundle format unrecognized, invalid, or unsuitable

1. Add a custom jre path in the configuration, and choose the default JRE that MacOS brings.
2. run `mvn clean javapackager:package`

**What is the expected behavior?**
End without error.

**What is the current behavior?**
Build failure.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
Unfortunately no. 

**Please tell us about your environment:**

- JavaPackager version: 1.6.4
- OS version: MacOS
- JDK version: 1.8u332
- Build tool: 
	- [X] Maven 
	- [ ] Gradle

**Comment by fvarrui** [comment]
Fixed by PR #167.

**Comment by fvarrui** [comment]
JavaPackager 1.6.5 released to Maven Central. It will be available in a few minutes (an hour at most).

Thanks so much for your contribution!

**Comment by fvarrui** [comment]
> It will be available in a few minutes (an hour at most).

[Ready!](https://repo1.maven.org/maven2/io/github/fvarrui/javapackager/1.6.5/)
