### ISSUE TITLE
Feature Request: AppImage packaging for GNU/Linux

### ISSUE THREAD

**Issue by lilvadim** [fvarrui/JavaPackager#169]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
I suggest to add option to build linux self-contained `.appimage` packages, they suitable for all distros and easy to run. `DEB` and `RPM` packages not suitable for installing on Arch Linux based distros.

**Comment by fvarrui** [comment]
Hi @lilvadim!

Thanks for your request, it seems very interesting, and it doesn't seem hard to implement. This format reminds me a bit to MacOS apps format.

Could you transform/adapt a Linux app generated with JavaPackager into an AppImage as example and tell here the results, please? It would be very helpful as an example. 

Thanks again!

**Comment by fvarrui** [comment]
Found this: https://github.com/AppImage/AppImageKit/wiki/Bundling-Java-apps

**Comment by fvarrui** [comment]
Hi @lilvadim!

I have good news ... now JavaPackager supports AppImage packaging for GNU/Linux.

It's available in JavaPackager 1.6.7-SNAPSHOT branch [issue-169](https://github.com/fvarrui/JavaPackager/tree/issue-169). You have to install it manually to your local repo as SNAPSHOT versions are not being released to Maven Central.

`AppImage` generation is enabled by default, but it's possible to disable it with `linuxConfig.generateAppImage=false`.

It would be very helpful if you could test it and give me some feedback, please.

> I'm working so that the generated AppImage file shows the right icon.

Thanks!!

**Comment by fvarrui** [comment]
Branch issue-169 merged into devel.

**Comment by fvarrui** [comment]
JavaPackager v1.6.7 released to Maven Central. See changes [here](https://github.com/fvarrui/JavaPackager/releases/tag/v1.6.7).
