### ISSUE TITLE
Add as Gradle plugin

### ISSUE THREAD

**Issue by Petersoj** [fvarrui/JavaPackager#17]
This would help out your gradle friends!
`jpackage` with OpenJDK 14 has been a bust lately and this project looks great, but implementing it as a Gradle plugin would be pretty nice instead of having to execute a maven wrapper from a gradle task to run this plugin.

**Comment by fvarrui** [comment]
JavaPackager was born because of a need. I haven't yet taken the step towards Gradle, because all my projects use Maven. Maybe you could help me to migrate it to Gradle; all help would be welcome in this task.

Thanks @Petersoj for your comment!

**Comment by Petersoj** [comment]
@fvarrui I'm going to give `jpackage` a little more time to improve, then if I'm still having problems, I'll open a PR.

**Comment by fvarrui** [comment]
Hi @Petersoj,
I've been researching a bit about the migration of the plugin to Gradle, and the main problem I see 
is that JavaPackager has dependencies on other Maven plugins. JavaPackager uses the [mojo-executor](https://github.com/TimMoore/mojo-executor) library to invoke other Maven plugins, but it is only possible to use it within a Maven context. Therefore, we would have to build a large part of the plugin from scratch, or find something that performs these functions in Gradle. Not to mention, the effort to maintain both versions of the plugin (Maven and Gradle). However, I'll continue researching because it might be interesting.

**Comment by Petersoj** [comment]
@fvarrui Hey thanks for looking into this. It looks like you're using the mojo-executor library for the following reasons: create runnable jar, copy jar dependencies, launch4j, and a deb package installer plugin. For the runnable jar and jar dependencies part, you can use the [Gradle application plugin](https://docs.gradle.org/current/userguide/application_plugin.html) which does both of those easily. There is a Gradle launch4j plugin too located [here](https://github.com/TheBoegl/gradle-launch4j) and for debian packages, see [this](https://github.com/gesellix/gradle-debian-plugin) plugin (which might be a bit out of date though).
Also, have you looked into [create-dmg](https://github.com/andreyvit/create-dmg) for creating DMGs for macOS? It allows for more configuration beyond just calling `hdiutil` to create a basic disk image so may want to look into that if you want a more configurable DMG installer (add icon, background image, etc.)
As a side note, it seems as though you're storing your maven plugin artifacts in this repo which isn't the best practice. Binaries and Git don't work well over time. You should consider putting those in maven central so users don't have to add this repo as a plugin repo and so you don't have to use git for binaries.
Anyways, I've gotten `jpackage` to work with OpenJDK14 so I'll be using that for now. However, if in the future I want more control of creating images and installers, I'll be sure to help out with this project. Thanks.

**Comment by fvarrui** [comment]
Thanks @Petersoj! Your comments are very helpful

**Comment by fvarrui** [comment]
Following your advice, I've published [JavaPackager in Maven Central](https://search.maven.org/artifact/io.github.fvarrui/javapackager). Thanks!

**Comment by fvarrui** [comment]
Hi @Petersoj,
I've looked into **create-dmg**, and taked some ideas to enhance DMG creation. This is a sample of a generated DMG with JavaPackager 0.9.6-SNAPSHOT, by default, without any config.

![image](https://user-images.githubusercontent.com/4354486/79688134-19c5c580-8244-11ea-9b88-422dea0522a2.png)

As soon as I add properties to configure the DMG (background image, windows size and location, icons location), I'll publish 0.9.6.

I've been researching about Gradle plugins and I'm going to try to make a hybrid plugin (same JAR for Maven and Gradle), reusing as much functionality as possible, so I don't have to maintain two plugins. I'm not sure if it's a good idea, but I'll try it.

Thanks again for your feedback!!

**Comment by fvarrui** [comment]
Hi @Petersoj!

I'm happy to announce that [JavaPackager version 1.2.0 is also available for Gradle](https://github.com/fvarrui/JavaPackager#config-your-project-and-package-your-app-with-gradle).

At the moment it is only available in Maven Central (using legacy mode plugin application), but I'll publish it soon in Gradle's plugin portal.

Thanks!

**Comment by Petersoj** [comment]
Awesome! Good work!
