### ISSUE TITLE
createDesktopIconTask variable not working

### ISSUE THREAD

**Issue by AntoninHuaut** [fvarrui/JavaPackager#170]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
The desktop icon is not created

**Steps to reproduce the issue/enhancement:**

1. Set the createDesktopIconTask variable (Windows configuration) to true
2. Build and run the installer

**What is the expected behavior?**
The desktop icon must be created without user interaction

**What is the current behavior?**
The desktop icon is not created

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
```kotlin
 winConfig(closureOf<WindowsConfig> {
        setupMode = SetupMode.installForCurrentUser
        icoFile = layout.projectDirectory.file("./assets/windows/App.ico").asFile
        isRemoveOldLibs = true
        isGenerateMsi = false
        isGenerateMsm = false
        isDisableRunAfterInstall = false
        isCreateDesktopIconTask = true // Set to true manually, but it's true by default
        setupLanguages = linkedMapOf("english" to "compiler:Default.isl", "french" to "compiler:Languages\\French.isl")
    } as Closure<WindowsConfig>)
```

According to the documentation: "If this is set to true, Setup will not ask for desktop icon creation."
![image](https://user-images.githubusercontent.com/1338257/158153507-5242e629-c995-405d-9400-1fffd0dd9a52.png)
Although CreateDesktopIconTask is set to true, the installer makes the request to the user. The box is not check by default.
If the user does not check the box then the icon is not created.

**Please tell us about your environment:**

- JavaPackager version: 1.6.4
- OS version: Windows 10
- JDK version: 17.0.2
- Inno Setup: 6.2.0
- Build tool: 
	- [ ] Maven 
	- [X] Gradle

**Comment by fvarrui** [comment]
Hi @AntoninHuaut!
I'm not really sure about this, as I don't use Gradle with Kotlin, but maybe the problem is that you are referencing the "getters" of `WinConfig` (you are using `isDisableRunAfterInstall` with the prefix `is`, instead of `disableRunAfterInstall`)?

```kotlin
 winConfig(closureOf<WindowsConfig> {
        setupMode = SetupMode.installForCurrentUser
        icoFile = layout.projectDirectory.file("./assets/windows/App.ico").asFile
        removeOldLibs = true
        generateMsi = false
        generateMsm = false
        disableRunAfterInstall = false
        createDesktopIconTask = true // Set to true manually, but it's true by default
        setupLanguages = linkedMapOf("english" to "compiler:Default.isl", "french" to "compiler:Languages\\French.isl")
    } as Closure<WindowsConfig>)
```

**Comment by fvarrui** [comment]
> The problem is with "createDesktopIconTask" not "disableRunAfterInstall"

Sorry, I got confused!

> According to the documentation: "If this is set to true, Setup will not ask for desktop icon creation."

I'm afraid there's an error in docs ... it's the opposite: "If this is set to **false**, Setup will not ask for desktop icon creation.". You can see it in `iss.vtl` template, used to generate the input file for Inno Setup Compiler:

https://github.com/fvarrui/JavaPackager/blob/d240244a620449bc75acf4aee08da8f9a9773452/src/main/resources/windows/iss.vtl#L62-L90

Creating the desktop shortcut  (line 88) depends on the task `desktopicon` (line 64), which shows a page with a shortcut creation checkbox. And this checkbox is disabled by default using the flag `unchecked`. You can create your own template, it's also explained in docs, and if you want the desktop shortcut to always be created then remove the `#if ... #end` statement and the "Tasks" option:

```ini
 [Icons] 
 Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\\${info.iconFile.name}" 
 Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\\${info.iconFile.name}" 
```

**Comment by fvarrui** [comment]
If you need help with the templates, don't hesitate to ask me

**Comment by fvarrui** [comment]
Sorry, I think it's poorly explained in docs
