### ISSUE TITLE
Must use jrePath property to specify JRE location to be embedded

### ISSUE THREAD

**Issue by Krehizi** [fvarrui/JavaPackager#171]
I'm submitting a…

- [ ]  bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

1.error:
Failed to execute goal io.github.fvarrui:javapackager:1.6.5:package (default-cli) on project gg2: Could not create a customized JRE due to JDK version is 1.8.0_131. Must use jrePath property to specify JRE location to be embedded

2.maven configuration:
(Path "C:/Program Files/Java/jdk1.8.0_131/jre" is exist)
```
<plugin>
	<groupId>io.github.fvarrui</groupId>
	<artifactId>javapackager</artifactId>
	<version>1.6.5</version>
	<configuration>
		<bundleJre>true</bundleJre>
		<mainClass>com.gg2.Application</mainClass>
		<generateInstaller>true</generateInstaller>
	</configuration>
	<executions>
		<execution>
			<id>bundling-for-windows</id>
			<phase>package</phase>
			<goals>
				<goal>package</goal>
			</goals>
			<configuration>
				<displayName>gg2</displayName>
				<platform>windows</platform>
				<createZipball>true</createZipball>
				<winConfig>
					<!-- general properties -->
					<generateSetup>true</generateSetup>
					<generateMsi>true</generateMsi>
					<generateMsm>true</generateMsm>
					<!-- setup generation properties -->
					<setupMode>installForAllUsers</setupMode>
					<createDesktopIconTask>true</createDesktopIconTask>
					<disableDirPage>false</disableDirPage>
					<disableFinishedPage>false</disableFinishedPage>
					<setupLanguages>
						<english>compiler:Default.isl</english>
					</setupLanguages>
				</winConfig>
				<administratorRequired>true</administratorRequired>
				<jrePath>C:/Program Files/Java/jdk1.8.0_131/jre</jrePath>
				<additionalResources>
					<additionalResource>${basedir}/src/main/resources</additionalResource>
				</additionalResources>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**Please tell us about your environment:**

- JavaPackager version: 1.6.5
- OS version: windows10
- JDK version: 1.8.0_131
- Build tool: 
	- [x] Maven 
	- [ ] Gradle

**Comment by fvarrui** [comment]
Hi @Krehizi!
Could you share mvn output, please?

**Comment by Krehizi** [comment]
> Hi @Krehizi! Could you share mvn output, please?

I found the problem. bundleJre has to be false.

**Comment by Krehizi** [comment]
Solutions：
![捕获](https://user-images.githubusercontent.com/27603839/158785035-7726163d-3bc5-4cfd-a295-4cf599ca5b00.PNG)

**Comment by LittleStarShining** [comment]
Hi, @Krehizi ,
could you solve this problem? Please share, my bro

**Comment by fvarrui** [comment]
Hi @Krehizi!
What's your issue?
