### ISSUE TITLE
Generate windows setups from docker inno setup image

### ISSUE THREAD

**Issue by lrodriguez03** [fvarrui/JavaPackager#172]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
Hola, al momento de generar los ejecutables para windows desde mac (o linux), se arroja el siguiente warning:

![Captura de Pantalla 2022-03-18 a la(s) 09 13 56](https://user-images.githubusercontent.com/83590449/159001117-8a15e8a5-2a9a-425b-b658-58bc694e1f10.png)

Pero que pasaría si pudiera correr `iscc` desde un contenedor de docker linux con inno setup sobre wine
https://gist.github.com/amake/3e7194e5e61d0e1850bba144797fd797

Teniendo acceso a `iscc` desde el bash ¿Habría alguna forma de evitar que se omita la creación del setup (.exe)?

Muchas gracias.

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**

**What is the current behavior?**

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.6.5
- OS version: 10.15.7
- JDK version: 1.8.0_241
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hola @lrodriguez03!
Interesante propuesta. La verdad es que no me lo había planteado, pero según el enlace que adjuntas creo que sería viable. Tal vez se pueda llevar esta propuesta a otro nivel, e incluso generar un DMG desde Windows? (por ejemplo) Lo estudiaré, gracias!!

**Comment by fvarrui** [comment]
Por cierto, por si te es de utilidad, también es posible generar todos los artefactos de instalación para las múltiples plataformas mediante GitHub Actions o Circle CI

**Comment by fvarrui** [comment]
Ahora mismo la generación del Setup obliga a que el sistema operativo sea Windows. Se podría añadir la opción booleana `forceSetup` para que NO omita la generación del Setup en caso de que el empaquetado se ejecute desde Linux o MacOS. Qué crees?

---

Right now the generation of the Setup forces the OS to be Windows. But `forceSetup` boolean option could be added to NOT skip the Setup generation if the package is run from Linux or MacOS. What do you think?

**Comment by lrodriguez03** [comment]
Buenas tardes, actualmente usando la imagen https://hub.docker.com/r/ikus060/docker-wine-maven logramos generar el instalador de windows desde mac/linux. Como la imagen esta montada con wine, javapackager considera que esta corriendo en windows y genera los setups correctamente.
Fue necesario instalar inno setup y agregarlo al WINEPATH desde el Dockerfile. Y además correr el `mvn clean package` con `bash` para que funcione.
``` Dokerfile
# Install Inno Setup binaries
RUN curl -SL "https://files.jrsoftware.org/is/6/innosetup-6.1.2.exe" -o is.exe \
    && wine-x11-run wine is.exe /SP- /VERYSILENT /ALLUSERS /SUPPRESSMSGBOXES \
    && rm is.exe

ENV WINEPATH="c:\Program Files\Inno Setup 6"

CMD ["bash", "mvn", "clean", "package"]
```
En el caso del instalador para mac, seguimos investigando como poder crearlo. El paquete `genisoimage` puede llegar a servir.
https://linux.die.net/man/1/genisoimage

Si es posible agregar una propiedad para forzar la creación del dmg sería muy util para poder probar esto último. Muchas gracias

**Comment by fvarrui** [comment]
Hola @lrodriguez03! Creo que mejor sería añadir una opción más general: `forceInstaller`, de modo que cuando sea `true` ignore la comprobación del sistema operativo a la hora de generar los instaladores.

**Comment by lrodriguez03** [comment]
Hola!. Si eso creemos que puede funcionar, ¿podes agrega esta opción? y lo probamos.

**Comment by fvarrui** [comment]
Hola @lrodriguez03!
He publicado los cambios con la opción `forceInstaller` en el branch [issue-172](https://github.com/fvarrui/JavaPackager/tree/issue-172) como versión 1.6.6-SNAPSHOT de JavaPackager. Debes instalar el plugin de forma manual en tu repo Maven local. Está explicado en el README del proyecto.

Pruébalo y me cuentas, por favor!
Un saludo

**Comment by fvarrui** [comment]
No soy experto en el asunto, pero ... ¿no se podría realizar todo el proceso de empaquetado con Maven + JavaPackager desde el mismo contenedor, y no sólo la ejecución de Inno Setup?

**Comment by fvarrui** [comment]
JavaPackager v1.6.6 released to Maven Central
