### ISSUE TITLE
Linux DEB package does not set correct permission on jre/lib/jspawnhelper

### ISSUE THREAD

**Issue by AstroPixelProcessor** [fvarrui/JavaPackager#174]
I'm submitting a…

- [X ] bug report

**Short description of the issue/suggestion:**

Linux DEB installer installs a non working java application in terms of being able to load native libs from external library JOGL (OpenGL) that needs to execute a script in user TMP directory to load native libs per platform.

By setting permissions of 755 (rwx,rx,rx) to jspawnhelper in jre/lib/jspawnhelper when the package is installed the issue is solved.

In the RPM packager this is done correctly and explicitely already, so needs to be fixed for the DEB packager.

**Please tell us about your environment:**

- JavaPackager version: 1.6.5
- OS version: Problem confirmed on Linux Mint 20, Ubuntu 20, It is likely that all DEB distributions are affected.
- JDK version: OpenJDK 17 (Temurin)
- Build tool: 
	- [ X ] Maven

**Comment by AstroPixelProcessor** [comment]
Hi @fvarrui ,

After installation of the DEB package, the issue is solved 100% if the user performs:

sudo chmod 755 jre/lib/jspanwhelper 

from the package installation folder, so the DEB installer needs to perform this and then all will be okay ;-)

Cheers,
Mabula

**Comment by AstroPixelProcessor** [comment]
@fvarrui,

in src/main/java/io.github.fvarrui.javapackager/packagers/GernerateDEB you can add this to fix it

Mapper javaSpawnHelperMapper = new Mapper();
javaSpawnHelperMapper.setType("perm");
javaSpawnHelperMapper.setFileMode("755");
javaSpawnHelperMapper.setPrefix("/opt/" + name + "/" + jreDirectoryName + "/lib");

File jSpawnHelperFile = new File(appFolder, jreDirectoryName + "/lib/jspawnhelper");

Data javaSpawnHelperData = new Data();
javaSpawnHelperData.setType("file");
javaSpawnHelperData.setSrc(jSpawnHelperFile);
javaSpawnHelperData.addMapper(javaSpawnHelperMapper);

dataProducers.add(javaSpawnHelperData);

Now the DEB installer produces a working application on Linux Mint and Ubuntu and probably thus on all DEB distributions.

Cheers,
Mabula

**Comment by AstroPixelProcessor** [comment]
Awesome @fvarrui , thank you very much !

**Comment by fvarrui** [comment]
I'll release JavaPackager 1.6.6 to Maven Central ASAP.
Thanks!

**Comment by fvarrui** [comment]
JavaPackager v1.6.6 released to Maven Central
