### ISSUE TITLE
0.8.9 package problem

### ISSUE THREAD

**Issue by holechain** [fvarrui/JavaPackager#18]
[ERROR] net.sf.launch4j.BuilderException: Invalid data: Product version, should be 'x.x.x.x'

**Comment by fvarrui** [comment]
Launch4j requires a version number in x.x.x.x format. JavaPackager takes the version number from your pom.xml and adds  `.0` at the end. So, your pom.xml version number has to be in x.x.x format, where x are numbers, without alphanumeric characters (e.g.: if you use `<version>1.2.3</version>`, JavaPackager will pass `1.2.3.0` to launch4j).

**Comment by fvarrui** [comment]
The generation of the binary for Windows with Launch4j has been changed in JavaPackager 0.9.1, so the executable always has the version number 1.0.0.0, and now it's possible to use any format for the version number of the project.

**Comment by holechain** [comment]
ok，thanks
