### ISSUE TITLE
可以将libs一起打包到exe里面么

### ISSUE THREAD

**Issue by lhDream** [fvarrui/JavaPackager#181]
可以将依赖库一起打包到exe里面么，虽然现在单独存放在libs目录下也可以使用。

**Comment by fvarrui** [comment]
Your question in Chinese, so used Google Translator:
```
Can the dependent library be packaged into the exe together, although it can be used separately in the libs directory now.
```

My answer in Spanish:
```
Puedes crear un FAT JAR que incluya todas las librerías y empaquetar ese JAR en el EXE.
```

So our conversation is more fun 😄

**Comment by lhDream** [comment]
This is a good solution. 😄 (This is also Google translation)

**Comment by fvarrui** [comment]
Sorry! I was kidding 😆. Does my proposal meet your need?

**Comment by lhDream** [comment]
It's okay 🤣.  I'm kidding, too。
他可以解决我的问题，但是不是很符合我的需要。
~~~
虽然我很想用英语跟你交流，但是我英语太差了，而且翻译的不准确。
我知道"exe4j"这个软件可以实现将jar打包为exe，之前我也是这么做的，直到我发现"JavaPackager"。
~~~

**Comment by fvarrui** [comment]
Hi @lhDream! 
Don't worry, Google Translator will come to the rescue.

Sorry, I'm not sure what you really need ... Do you have an example? How exe4j package JARs?

**Comment by lhDream** [comment]
&emsp;&emsp;Sorry, I didn't make it clear. For example, "spring boot" will package all dependent jars into a jar file. Because I didn't know launch4j and winrun4j at that time, I packaged them into exe with "exe4j".

&emsp;&emsp;Now, I want to know whether "javapackage" can package all dependent jars into one jar like "spring-boot-maven-plugin", and then package them into an EXE file.

&emsp;&emsp;I want a solution that can automatically solve these steps, because it is cumbersome and meaningless to manually package the jar file into "exe" every time when you want to release the version frequently.

**Comment by lhDream** [comment]
Thank you very much for your help !

**Comment by fvarrui** [comment]
Which building tool are you using? Or do you plan to use one? Is your project on a public repo? 

Using a building tool you can automate this process. First you can package all your JARs into an uber/fat JAR, and then, give this FAT JAR to JavaPackager, so it can embed this JAR inside an EXE using Launch4j.

**Comment by fvarrui** [comment]
But JavaPackager doesn't create FAT JARs at the moment

**Comment by lhDream** [comment]
Sorry,this is not a public project。

I'm using Maven。How do I configure POM, give this FAT JAR to JavaPackager .

🤣 I learned a lot of English.

**Comment by fvarrui** [comment]
I'll implement an example app to show you how to do it

**Comment by fvarrui** [comment]
Hi @lhDream!
Here you have an example: https://github.com/fvarrui/HelloWorldMaven

**Comment by lhDream** [comment]
Thank you vary much！

**Comment by fvarrui** [comment]
Was this sample project helpful?

**Comment by lhDream** [comment]
Yes! It helped me a lot.

**Comment by lhDream** [comment]
My problem has been solved ！

The spring boot project requires the following configuration.
~~~java
<mainClass>org.springframework.boot.loader.JarLauncher</mainClass>
~~~
I hope it can help people with the same problems.

**Comment by lhDream** [comment]
@fvarrui ,Thank you very much for your help.

**Comment by fvarrui** [comment]
You are welcome!
