### ISSUE TITLE
New app using Java Packager

### ISSUE THREAD

**Issue by almostobvious** [fvarrui/JavaPackager#182]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
Not a bug /issue - more of an annoucement! I wanted to share good news - my site and app are now live. App is packaged with JavaPackager and is available for download here:

https://spektar.io

JavaPackager is included in acknowledgements. Many, many thanks!

**Comment by fvarrui** [comment]
Hi @almostobvious! Good news, I'm happy to hear that. Could I add a link to your app's web site in a new JavaPackager's README section? "Apps packaged with JavaPackager" 😃

**Comment by almostobvious** [comment]
Hi - thanks very much, that would be very nice. Many thanks again.
