### ISSUE TITLE
Process name and icon in Windows Task Manager

### ISSUE THREAD

**Issue by ilacc1** [fvarrui/JavaPackager#189]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Hi fvarrui, thanks again for a great tool. I've encountered an issue and was wandering if there is a trick to overcome this (possibly me doing something wrong!).

When my app is run, the taskbar icon and label behave as expected - app icon is shown correctly and tooltip shows window title. I expect these are derived from the window, in any event, that works fine.

However in task manager, app shows up as "OpenJDK Platform binary" and with a Java "duke" icon. I expect these are derived from the windows process / exec file?

So not sure if I'm doing something wrong / if there is any way to correct this and get windows to show my app icon and app name correctly in task manager?

Thanks

**Steps to reproduce the issue/enhancement:**

1. Create a windows installer with any app (gui or console makes no difference)
2. Install
3. Run the app
4. Open task manager (for example by pressing ctrl-shift-esc)
5. Your application shows as OpenJDK Platform binary and with a duke icon

**What is the expected behavior?**
Windows task manager should show app icon and app name specified in config

**What is the current behavior?**
Windows task manager shows OpenJDK Platform binary and with a duke icon

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
No but should be easy to reproduce with any packaged app.

**What is the motivation / use case for changing the behavior?**
Better user experience

**Please tell us about your environment:**

- JavaPackager version: 1.6.6
- OS version: windows 10
- JDK version: 11
- Build tool: 
	- [ x ] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @ilacc1!
That is the Launch4j behaviour. There are two other EXE generation tools: winrun4j and why. Please, take a look to winConfig.exeGenerationTool property.

**Comment by ilacc1** [comment]
Thanks for the pointers Francisco, I'll investigate. In the meantime, I'll close the ticket as this likely isn't JavaPackager issue. Many thanks!

**Comment by fvarrui** [comment]
If this option doesn't meet your needs, feel free to reopen this issue and we can look for other alternatives
