### ISSUE TITLE
How to remove libs directory from the generated installation?

### ISSUE THREAD

**Issue by RiverChu0** [fvarrui/JavaPackager#191]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
I use property `wrapJar=true` then generated exe included my jars.
I don't want libs directory. 
How do I remove it from the generated installation?

**Steps to reproduce the issue/enhancement:**
projectDir
 -jre/
 -libs/
 -LICENSE
 -project.exe
 -project.ico

**What is the expected behavior?**
remove libs/ and project.ico

**What is the current behavior?**
libs/ and project.ico is redundant.

**Please tell us about your environment:**

- JavaPackager version:
- OS version: windows 10
- JDK version: OracleJDK 1.8.0_201
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @RiverChu0!
Are you bundling your own fat JAR? If so, you can set `copyDependencies=false`, so `libs` folder is not created. Otherwise, the wrapped JAR only includes your code, not its dependencies, and your app needs them.

**Comment by fvarrui** [comment]
AFIKA, only one JAR can be wrapped in EXE file with Launch4j. So, if you want to wrap your libraries in EXE, you should create and bundle your own fat/uber JAR

**Comment by RiverChu0** [comment]
> Hi @RiverChu0! Are you bundling your own fat JAR? If so, you can set `copyDependencies=false`, so `libs` folder is not created. Otherwise, the wrapped JAR only includes your code, not its dependencies, and your app needs them.

Ok,that is work! thanks!
