### ISSUE TITLE
We need some way to resolve problems with generated .exe files

### ISSUE THREAD

**Issue by dkoding** [fvarrui/JavaPackager#192]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

Very hard to debug if the resulting .exe file does not work

**Steps to reproduce the issue/enhancement:**

1. Create java application
2. Create packager with bundled JRE
3. Create exe
4. Run exe - nothing happens
5. ?

**What is the expected behavior?**

Some way to verify the resulting .exe file - not necessarily code, but some kind of checklist, FAQ or something to use to resolve problems.

**What is the current behavior?**

Nothing happens when running the .exe 

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

Can be provided on request

**What is the motivation / use case for changing the behavior?**

A way to resolve problems. 

**Please tell us about your environment:**

- JavaPackager version: Latest
- OS version: Windows 10
- JDK version: Liberica 8
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @dkoding!
If you are using Launch4j as EXE creation tool, try to set `winConfig.headerType=console` and then run your EXE. This way it will show any output in console

**Comment by dkoding** [comment]
That is a great tip, thank you for your quick reply.

**Comment by fvarrui** [comment]
Hi @dkoding!
Did you manage to find what was going wrong with your EXE?
