### ISSUE TITLE
vmLocation in WinRun4J config

### ISSUE THREAD

**Issue by ilacc1** [fvarrui/JavaPackager#194]
I'm submitting a…

- [x] bug report
- [] feature request
- [] other

**Short description of the issue/suggestion:**
Hi Francisco!

I am trying to use WinRun4J to address the problems with Launch4J I have previously reported. I have encountered an issue with vmLocation. I can't work out whether vmLocation refers to build environment or execution environment. Documentation is not clear on this. Worst case would be to apply to both - in my rather complex setup, build uses one path (jdks/win/bin/server/jvm.dll) and runtime has a different layout (runtime/bin/server/jvm.dll). 

So what happens is that if I specify runtime location, build fails because this location doesn't exist in the build environment (or rather, it exists, but only under target/project-name/ where it s copied with bundleJre). Conversely, if I specify the build time location, the app is built, but it doesn't run as it can't find jvm.dll.

I was expecting that providing runtime value should work - at exe build time these files will already be there in the bundled JRE location (under target/project-name/). But it seems this isn't how it works...

How best to overcome this (ideally without major refactoring / creating yet another copy of the jdk)?

**Steps to reproduce the issue/enhancement:**

1. Create project where build uses one path (jdks/win/bin/server/jvm.dll) and runtime has a different layout (runtime/bin/server/jvm.dll). 
2. Configure vmLocation to point to runtime location (runtime/bin/server/jvm.dll)
3. Build

**What is the expected behavior?**

Build should find the jre under target/project-name/runtime/bin/server/jvm.dll

**What is the current behavior?**

Build fails

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.937 s
[INFO] Finished at: 2022-05-11T21:16:21+01:00
[INFO] Final Memory: 35M/124M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.6.6:package (bundling) on project testproject: VM location 'runtime/bin/server/jvm.dll' does not exist -> [Help 1]
```

**What is the motivation / use case for changing the behavior?**

I think it would be cleaner and keep the build time and runtime settings decoupled.

**Please tell us about your environment:**

- JavaPackager version: 1.6.6
- OS version: Win 10
- JDK version: 11
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @ilacc1!
Please, could you share your POM?

**Comment by fvarrui** [comment]
`vmLocation` refers to runtime environment. What is the error output when you build your project?

**Comment by ilacc1** [comment]
Here is an example. Note you have to set jdkPath to point to a valid jdk installation directory. (In my setup this is within project folder under jdks/${os.label}/).

[javapackager-winrun4j-buglet.zip](https://github.com/fvarrui/JavaPackager/files/8680933/javapackager-winrun4j-buglet.zip)

**Comment by fvarrui** [comment]
Hi @ilacc1!
Sorry for my late reply, but I've been so busy last weeks.

I've tried your example project, and if you are doing the same, you have to remove "runtime" from VM DLL location path, since this path is relative to the generated JRE:

Use:
```xml
<vmLocation>bin/server/jvm.dll</vmLocation>
```
instead of:
```xml
<vmLocation>runtime/bin/server/jvm.dll</vmLocation>
```

I hope it helps!

**Comment by ilacc1** [comment]
Thanks Francisco, this has solved the immediate problem. But the generated app fails to start - 

```
java.lang.ClassNotFoundException: my.main.MyMain
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at WinRun4JLauncher.main(WinRun4JLauncher.java:8)

```

Same config with launch4j works fine. Also, I've checked in target/winrun4j/app.jar and the class is there. Must be something silly I am doing...

I'll close this as resolved, and if I can't work out the above problem will be back to ask again!

**Comment by ilacc1** [comment]
Ok, I've adapted my winrun4j ini file for classpath and all good now. Many thanks!
