### ISSUE TITLE
How do I configure FileAssociations in gradle

### ISSUE THREAD

**Issue by jinsihou19** [fvarrui/JavaPackager#197]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

How do I configure FileAssociations in gradle?

I write this code：

```gradle
def association = new FileAssociation()
association.extension = 'log'
association.description = 'log_analyzer'
association.mimeType = 'text/plain'

task packageAppForMac(type: PackageTask, dependsOn: shadowJar) {
    appName = project.name
    platform = 'mac'
    fileAssociations  = [
            association
    ]
}
```

after run it report that:

```
Unable to store input properties for task ':packageAppForMac'. Property 'fileAssociations' with value '[FileAssociation [mimeType=text/plain, extension=log, description=log]]' cannot be serialized.
```

**Please tell us about your environment:**

- JavaPackager version:
- OS version: macos 12.3.1
- JDK version: 1.8.0_181
- Build tool: 
	- [ ] Maven 
	- [x] Gradle

**Comment by fvarrui** [comment]
Hi @jinsihou19!
It seems to be a bug, since the `FileAssociation` class would have to be serializable.

A work around could be to specify the file association in the extension:
```groovy
javapackager {
    fileAssociations = [
    	new FileAssociation(mimeType: 'text/plain', extension: 'log', description: 'log_analyzer')
    ]
}
```

**Comment by fvarrui** [comment]
Hi @jinsihou19!
I've made `FileAssociation` class serializable. This should fix this problem. Please, could you try JavaPackager 1.6.7-SNAPSHOT (devel branch)? 
> It has to be installed manually in your local repo:
> ```bash
> git clone https://github.com/fvarrui/JavaPackager --branch devel
> cd JavaPackager
> ./gradlew publishToMavenLocal
> ```

**Comment by fvarrui** [comment]
JavaPackager v1.6.7 released to Maven Central. See changes [here](https://github.com/fvarrui/JavaPackager/releases/tag/v1.6.7).
