### ISSUE TITLE
How to add registry entry to run app on startup (Windows) ?

### ISSUE THREAD

**Issue by DBChoco** [fvarrui/JavaPackager#198]
I was wondering how I could add a registry entry to add my app to the windows startup process.
I've already got this for now: 

```
<registry>
    <entries>
        <entry>
            <key>HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run</key>
            <valueName>myAppStartup</valueName>
            <valueType>string</valueType>
            <valueData>????</valueData>
        </entry>
    </entries>
</registry>
```
I saw [here](https://www.akadia.com/services/windows_registry.html) that I have to do this: 

> For each program you want to start automatically create a new string value using a descriptive name, and set the value of the string to the program executable.
> 
> For example, to automatically start Notepad, add a new entry of:
> 
> "Notepad"="c:\windows\notepad.exe".

However I don't know how to get the install path of my app.
Would appreciate some help, thanks !

-------------------

- JavaPackager version: 1.6.6
- JDK version: 18
- Build tool: 
	- [x] Maven 
	- [ ] Gradle

**Comment by fvarrui** [comment]
Hi @DBChoco!
I'll have a look into this and tell you something ASAP. Do you want to use Inno Setup installer or WiX Toolset MSI?

**Comment by DBChoco** [comment]
I use Inno Setup for an .EXE installer.
For now I went with this:

```
<!-- setup generation properties -->
<setupMode>installForCurrentUser</setupMode>
<disableRunAfterInstall>false</disableRunAfterInstall>
<createDesktopIconTask>false</createDesktopIconTask>

<!-- windows registry entries added during installation -->
<registry>
    <entries>
        <entry>
            <key>HKCU:Software\Microsoft\Windows\CurrentVersion\Run</key>
            <valueName>Salawat</valueName>
            <valueType>REG_SZ</valueType>
            <valueData>%USERPROFILE%\AppData\Local\Programs\Salawat\Salawat.exe</valueData>
        </entry>
    </entries>
</registry>
```

**Comment by fvarrui** [comment]
Hi @DBChoco!
Please, try using this: 
```xml
<registry>
    <entries>
        <entry>
            <key>HKCU:Software\Microsoft\Windows\CurrentVersion\Run</key>
            <valueName>Salawat</valueName>
            <valueType>REG_SZ</valueType>
            <valueData>""{app}\{#MyAppExeName}""</valueData>
        </entry>
    </entries>
</registry>
```
and give some feedback.
Thanks!

**Comment by DBChoco** [comment]
Hello @fvarrui, just tested it and it works perfectly, thanks a lot!
Have a nice day.

**Comment by fvarrui** [comment]
> ```
>         <entry>
>             <key>HKCU:Software\Microsoft\Windows\CurrentVersion\Run</key>
>             <valueName>Salawat</valueName>
>             <valueType>REG_SZ</valueType>
>             <valueData>""{app}\{#MyAppExeName}""</valueData>
>         </entry>
> ```

All registry entries are directly mapped into `iss.vtl` template when is rendered, so generating the `.iss` file which is used later as input for Inno Setup compiler (`iscc`). You can even create your own VTL templates, in case you need to customized something more in the future.
