### ISSUE TITLE
Packaging failed with multi-release jar

### ISSUE THREAD

**Issue by Pyeroh** [fvarrui/JavaPackager#2]
When packaging with a multi-release jar, I get a NPE from your plugin.
I'm using Maven, the faulty library is H2 (which is now multi-release), and when the plugin runs jeps, it gets an error, because `h2-1.4.199.jar is a multi-release jar file but --multi-release option is not set`.
Then jlink is called with that message, which is obviously not a valid modules list, and the jre folder is not created by jlink. Hence the NPE.

I tried to run the jdeps command on my machine, with the multi-release option, and it returns modules names.

BTW, thank you very much for this plugin, it does its jobs perfectly ! I spent too much time trying to fit my JavaFX/"Java 8 only libraries" app in the module system, and kept failing. It makes it work like a breeze !

**Comment by fvarrui** [comment]
Please, could you provide me with a sample project repo where you use a multi-release jar? Thanks for giving a try to JavaPackager.

**Comment by fvarrui** [comment]
I added `--multi-release` option to `jdeps` command using current JRE version as its value by default, then tried with `h2-1.4.199.jar` jar file and now it doesn't fail. Could you confirm me if this issue is really solved? Thanks!

**Comment by Pyeroh** [comment]
It's solved indeed, thank you very much !
