### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by holechain** [fvarrui/JavaPackager#20]
Hi Fran,  I have problem with the new 0.9.1 version. Can openjfx13 be used?

**Comment by fvarrui** [comment]
Hi @holechain ,
I think so, but tell me what your problem is, please. 
Could you share your Maven logs? From which platform are you using JavaPackager?
By the way, I've just published v0.9.3 in order to solve issue #19 ... maybe this is your problem.

**Comment by holechain** [comment]
thanks，my problem is that the packaged program of jdk13 cannot run.

**Comment by holechain** [comment]
Error: JavaFX runtime components are missing, and are required to run this application

**Comment by fvarrui** [comment]
Sorry, I need more info. Could you share you POM and Maven output, please?

**Comment by holechain** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>yunchucun-C-PC-java</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>storage</name>

    <properties>
        <client.version>1.0.0</client.version>
        <exec.maven.plugin.version>1.6.0</exec.maven.plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mainClass>com.mandela.Main</mainClass>
        <javafx.version>13.0.1</javafx.version>
        <maven.compiler.source>13</maven.compiler.source>
        <maven.compiler.target>13</maven.compiler.target>
        <maven.compiler.release>13</maven.compiler.release>
        <javafx.version>13</javafx.version>
    </properties>

    <repositories>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
    </repositories>

    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.fxml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>

        <plugins>
<!--            <plugin>-->
<!--                <groupId>com.zenjava</groupId>-->
<!--                <artifactId>javafx-maven-plugin</artifactId>-->
<!--                <version>8.8.3</version>-->
<!--                <configuration>-->
<!--                    <mainClass>${mainClass}</mainClass>-->
<!--                    <vendor>storage</vendor>-->
<!--                    <appName>storage</appName>-->
<!--                    <additionalAppResources>D:\test\peer_root\peer.dll</additionalAppResources>-->
<!--                </configuration>-->
<!--            </plugin>-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>org.openjfx</groupId>-->
<!--                <artifactId>javafx-maven-plugin</artifactId>-->
<!--                <version>0.0.4</version>-->
<!--                <configuration>-->
<!--                    <mainClass>${mainClass}</mainClass>-->
<!--                </configuration>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-dependency-plugin</artifactId>-->
<!--                <version>3.1.1</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>copy-dependencies</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>copy-dependencies</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <outputDirectory>${project.build.directory}/libs</outputDirectory>-->
<!--                            <overWriteReleases>false</overWriteReleases>-->
<!--                            <overWriteSnapshots>false</overWriteSnapshots>-->
<!--                            <overWriteIfNewer>true</overWriteIfNewer>-->
<!--                            <includeScope>compile</includeScope>-->
<!--                            <includeScope>runtime</includeScope>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
<!--            <plugin>-->
<!--                <groupId>io.github.fvarrui</groupId>-->
<!--                <artifactId>javapackager</artifactId>-->
<!--                <version>0.9.3</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>package</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <mainClass>${mainClass}</mainClass>-->
<!--                            <bundleJre>true</bundleJre>-->
<!--&lt;!&ndash;                            <customizedJre>true</customizedJre>&ndash;&gt;-->
<!--                            <generateInstaller>true</generateInstaller>-->
<!--                            <administratorRequired>false</administratorRequired>-->
<!--                            <platform>auto</platform>-->
<!--                            <jrePath>D:\IdeaProject\yunchucun-C-PC-java\target\java-runtime</jrePath>-->
<!--                            <iconFile>show/image/icon/icon.ico</iconFile>-->
<!--                            <runnableJar>D:\IdeaProject\yunchucun-C-PC-java\target\yunchucun-C-PC-java-1.0-SNAPSHOT.jar</runnableJar>-->
<!--                            <additionalResources>-->
<!--                                <param>show</param>-->
<!--                                <param>D:\test\peer_root\peer.dll</param>-->
<!--                                <param>D:\test\peer_super\conf</param>-->
<!--                            </additionalResources>-->
<!--                            <copyDependencies>true</copyDependencies>-->
<!--                            <name>${name}</name>-->
<!--                            <displayName>${name}</displayName>-->
<!--                            <vmArgs>&#45;&#45;module-path="storage\libs"</vmArgs>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->


            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>${mainClass}</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.0.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${mainClass}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>build-mac</id>

            <activation>
                <os><family>mac</family></os>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <artifactId>exec-maven-plugin</artifactId>
                        <groupId>org.codehaus.mojo</groupId>
                        <version>${exec.maven.plugin.version}</version>
                        <executions>
                            <execution>
                                <id>Build Native Mac App</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>${mainClass}</mainClass>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <executable>./build_app.sh</executable>
                            <environmentVariables>
                                <APP_VERSION>
                                    ${client.version}
                                </APP_VERSION>
                                <PROJECT_VERSION>
                                    ${project.version}
                                </PROJECT_VERSION>
                            </environmentVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>build-windows</id>

            <activation>
                <os><family>windows</family></os>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <artifactId>exec-maven-plugin</artifactId>
                        <groupId>org.codehaus.mojo</groupId>
                        <version>${exec.maven.plugin.version}</version>
                        <executions>
                            <execution>
                                <id>Build Native Windows App</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <mainClass>${mainClass}</mainClass>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <executable>build_app.bat</executable>
                            <environmentVariables>
                                <APP_VERSION>
                                    ${client.version}
                                </APP_VERSION>
                                <PROJECT_VERSION>
                                    ${project.version}
                                </PROJECT_VERSION>
                            </environmentVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

    <dependencies>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>net.coobird</groupId>
            <artifactId>thumbnailator</artifactId>
            <version>0.4.8</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.9</version>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.9.2</version>
        </dependency>
        <dependency>
            <groupId>com.onlyxiahui</groupId>
            <artifactId>only-app-fx</artifactId>
            <version>0.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.codefx.libfx</groupId>
            <artifactId>LibFX</artifactId>
            <version>0.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
            <version>5.1.5.RELEASE</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.8</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.8</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.5.3</version>
        </dependency>
    </dependencies>
</project>

**Comment by fvarrui** [comment]
I don’t see JavaPackager plugin in your POM

**Comment by holechain** [comment]
My project is developed by openjfx13. I use this ：https://github.com/javafx-maven-plugin/javafx-maven-plugin to package and run the program. The program cannot be run after using this https://github.com/fvarrui/JavaPackager/tree/v0.9.3 package.

**Comment by holechain** [comment]
<plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>0.9.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>${mainClass}</mainClass>
                            <bundleJre>true</bundleJre>

                            <generateInstaller>true</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>auto</platform>
                            <jrePath>D:\IdeaProject\yunchucun-C-PC-java\target\java-runtime</jrePath>
                            <iconFile>show/image/icon/icon.ico</iconFile>
                            <runnableJar>D:\IdeaProject\yunchucun-C-PC-java\target\yunchucun-C-PC-java-1.0-SNAPSHOT.jar</runnableJar>
                            <additionalResources>
                                <param>show</param>
                                <param>D:\test\peer_root\peer.dll</param>
                                <param>D:\test\peer_super\conf</param>
                            </additionalResources>
                            <copyDependencies>true</copyDependencies>
                            <name>${name}</name>
                            <displayName>${name}</displayName>
                            <vmArgs>--module-path="storage\libs"</vmArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by fvarrui** [comment]
I also used [javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) until it was no longer maintained, so I decided to develop my own plugin.

I think the problem was `<vmArgs>--module-path="storage\libs"</vmArgs>`; it's not necessary.
Further, many of the functions performed by the plugins you are using in your POM are already performed by JavaPackager. 

I tried to reduce your POM and I hope I haven't removed important parts. Take a look:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>com.mycompany</groupId>
	<artifactId>yunchucun-C-PC-java</artifactId>
	<version>1.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>storage</name>

	<properties>
		<client.version>1.0.0</client.version>
		<exec.maven.plugin.version>1.6.0</exec.maven.plugin.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<mainClass>com.mandela.Main</mainClass>
		<javafx.version>13.0.1</javafx.version>
		<maven.compiler.source>13</maven.compiler.source>
		<maven.compiler.target>13</maven.compiler.target>
		<maven.compiler.release>13</maven.compiler.release>
	</properties>

	<repositories>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>
	</repositories>

	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.fxml</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>io.github.fvarrui</groupId>
				<artifactId>javapackager</artifactId>
				<version>0.9.3</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>package</goal>
						</goals>
						<configuration>
							<mainClass>${mainClass}</mainClass>
							<bundleJre>true</bundleJre>
							<generateInstaller>true</generateInstaller>
							<iconFile>show/image/icon/icon.ico</iconFile>
							<additionalResources>
								<param>show</param>
								<param>D:\test\peer_root\peer.dll</param>
								<param>D:\test\peer_super\conf</param>
							</additionalResources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>


	<dependencies>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-swing</artifactId>
			<version>${javafx.version}</version>
		</dependency>
		<dependency>
			<groupId>net.coobird</groupId>
			<artifactId>thumbnailator</artifactId>
			<version>0.4.8</version>
		</dependency>
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<version>4.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.9</version>
		</dependency>
		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.9.2</version>
		</dependency>
		<dependency>
			<groupId>com.onlyxiahui</groupId>
			<artifactId>only-app-fx</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.codefx.libfx</groupId>
			<artifactId>LibFX</artifactId>
			<version>0.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>5.1.5.RELEASE</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>1.2.8</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.9.8</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-cli</groupId>
			<artifactId>commons-cli</artifactId>
			<version>1.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<version>4.5.3</version>
		</dependency>
	</dependencies>

</project>
```

**Comment by holechain** [comment]
Ok,I try it out,thank you

**Comment by holechain** [comment]
- After I try the new pom, the program prompts: Error: JavaFX runtime components are missing, and are required to run this application

![image](https://user-images.githubusercontent.com/32643286/76484746-a1563280-6455-11ea-86c3-77e80ab562b8.png)

- The picture below is the successful effect of using javafx-maven-plugin。

![image](https://user-images.githubusercontent.com/32643286/76484948-0d389b00-6456-11ea-8a29-6744cfd63045.png)
`            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.8.3</version>
                <configuration>
                    <mainClass>${mainClass}</mainClass>
                    <vendor>storage</vendor>
                    <appName>storage</appName>
                    <deployDir>show/image/icon/icon.ico</deployDir>
                </configuration>
            </plugin>`

**Comment by fvarrui** [comment]
Ok. Please, can you send `mvn package` output?

**Comment by holechain** [comment]
This?
![image](https://user-images.githubusercontent.com/32643286/76485801-74efe580-6458-11ea-8447-5f738a0f273b.png)

**Comment by holechain** [comment]
![image](https://user-images.githubusercontent.com/32643286/76485859-9fda3980-6458-11ea-99d2-e6bdf5ef0e35.png)

**Comment by holechain** [comment]
Take the liberty to ask, if you have time, you can use teamviewer to connect to my computer to operate.

**Comment by fvarrui** [comment]
Shall we meet at [https://meet.jit.si/JavaPackager](https://meet.jit.si/JavaPackager)?

**Comment by fvarrui** [comment]
I'm waiting ... are you ready?

**Comment by holechain** [comment]
hi，favrrui.thank you very much.You are welcome to come to China, and I will treat you warmly.I've added your telegram, and I'd like you to pass through.



---Original---

**Comment by fvarrui** [comment]
How to solve "Error: JavaFX runtime components are missing, and are required to run this application":

1. Create a new class (e.g. `Main`) which not extends `Application` with a `main` method.
2. Call `App.main` (`App` extends `Application`) method from `Main.main`.
3. Now run the app calling `Main.main`.
3. That's all!

```java
public class App extends Application {
    [...]
    public static void main(String [] args) {
        launch(args);
    }
    [...]
}
```

```java
public class Main {
    public static void main(String [] args) {
        App.main(args);
    }
}
```

This solves the problem.

**Comment by holechain** [comment]
OK,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fvarrui"<notifications@github.com&gt;; 
发送时间: 2020年3月14日(星期六) 晚上8:52
收件人: "fvarrui/JavaPackager"<JavaPackager@noreply.github.com&gt;; 
抄送: "793630556"<nrgh@foxmail.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [fvarrui/JavaPackager] problem (#20)





 
How to solve "Error: JavaFX runtime components are missing, and are required to run this application":
  
Create a new class (e.g. Main) which not extends Application with a main method.
 
Call App.main (App extends Application) method from Main.main.
 
Now run the app calling Main.main.
 
That's all!
  public class App extends Application {     [...]     public static void main(String [] args) {         launch(args);     }     [...] }
 public class Main {     public static void main(String [] args) {         App.main(args);     } }
 
This solves the problem.

**Comment by NewStorm-0** [comment]
> How to solve "Error: JavaFX runtime components are missing, and are required to run this application":
> 
> 1. Create a new class (e.g. `Main`) which not extends `Application` with a `main` method.
> 2. Call `App.main` (`App` extends `Application`) method from `Main.main`.
> 3. Now run the app calling `Main.main`.
> 4. That's all!
> 
> ```java
> public class App extends Application {
>     [...]
>     public static void main(String [] args) {
>         launch(args);
>     }
>     [...]
> }
> ```
> 
> ```java
> public class Main {
>     public static void main(String [] args) {
>         App.main(args);
>     }
> }
> ```
> 
> This solves the problem.

Hello, do you have any plans to fix it in the new version? I'm still experiencing the problem while using the version 1.7.5
