### ISSUE TITLE
Garbled code

### ISSUE THREAD

**Issue by lhDream** [fvarrui/JavaPackager#202]
When ${project. Description} is in Chinese, the process displays garbled code
```java
- JavaPackager version: 1.6.6
- OS version: windows Server 2019 Datacenter 1809
- JDK version: 1.8
- Build tool: Maven 3.8
```
![image](https://user-images.githubusercontent.com/41568266/170173949-a66ba4b3-821d-4a2c-bc02-2a6d69e27d2d.png)

**Comment by fvarrui** [comment]
Hi @lhDream!
Please, have a look at this related [issue](https://github.com/fvarrui/JavaPackager/issues/21).

**Comment by fvarrui** [comment]
Hi @lhDream!
Did you manage to fix this issue? JavaPackager is using [`rcedit-64.exe`](https://github.com/electron/rcedit) command line tool to customize WinRun4j and Why launchers (EXE files) ... maybe you can try it with the EXE generated by Launch4j.

**Comment by lhDream** [comment]
Hi @fvarrui 
I tried to use launch4j, but I couldn't.

**Comment by fvarrui** [comment]
I mean use `rcedit-x64.exe` command tool by your own to modify the description of the EXE generated with Launch4j

**Comment by lhDream** [comment]
@fvarrui 
[rcedit-x64.exe](https://github.com/electron/rcedit) does modify the EXE file description, but it cannot be executed.

**Comment by fvarrui** [comment]
Could you give a try to [Resource Hacker](http://www.angusj.com/resourcehacker/)? It also can be used as a command line tool, and if it works fine, maybe you can automate the "set-exe-description" process calling it from Maven. 

I'm sorry I can't help you much more

**Comment by lhDream** [comment]
Hi @fvarrui 
If the project path contains CJK, the project will fail to package.
Example:
```java
D:/test/测试/testProject
```

**Comment by fvarrui** [comment]
Hi @lhDream!
sorry for my late reply!
I'll do some research about this, but I'm not really sure if I can reproduce your issue on my Spanish Windows.

**Comment by lhDream** [comment]
hi @fvarrui 
It doesn't matter. It's not a big problem. If you can't reproduce it, you can try the virtual machine.

**Comment by fvarrui** [comment]
Let's keep this issue opened until we can find a solution. Thanks!

> hi @fvarrui It doesn't matter. It's not a big problem. If you can't reproduce it, you can try the virtual machine.

**Comment by fvarrui** [comment]
> The [Resource Hacker](http://www.angusj.com/resourcehacker/) GUI can use

Did you manage to automate the "set description" process using Resource Hacker?

**Comment by lhDream** [comment]
hi @fvarrui 
Tried, but failed. Maybe I used it the wrong way

**Comment by lhDream** [comment]
Hi @fvarrui ！

> ResourceHacker.exe version V5.1.8

demo.rc
```rc
1 VERSIONINFO
FILEVERSION 3,1,4,1592
PRODUCTVERSION 2,7,1,8
FILEOS 0x4
FILETYPE 0x1
{
BLOCK "StringFileInfo"
{
    BLOCK "040904E4"
    {
        VALUE "CompanyName", "测试0\0"
        VALUE "FileDescription", "测试1\0"
        VALUE "FileVersion", "测试2\0"
        VALUE "ProductName", "测试3\0"
        VALUE "InternalName", "测试4\0"
        VALUE "LegalCopyright", "测试5\0"
        VALUE "OriginalFilename", "测试6\0"
        VALUE "ProductVersion", "测试7\0"
    }
}

BLOCK "VarFileInfo"
{
    VALUE "Translation", 0x0409 0x04E4  
}
}
```

>ResourceHacker.exe -open demo.rc -save demo.res -action compile
 
>ResourceHacker.exe -open demo.exe -save newDemo.exe -action addoverwrite -resource demo.res

![image](https://user-images.githubusercontent.com/41568266/184855786-a82a7e38-17b7-44a7-8566-59b05aef194f.png)
![image](https://user-images.githubusercontent.com/41568266/184855957-92e62441-2f7b-417d-9708-675aaa4bd6ab.png)

**Comment by fvarrui** [comment]
Hi @lhDream!
So, is `ResourceHacker` command line tool working as expected?

**Comment by lhDream** [comment]
Hi @fvarrui !
Yes!

**Comment by fvarrui** [comment]
JavaPackager 1.7.0 released to Maven Central
