### ISSUE TITLE
DMG image generation failed due to: Command execution failed: bless --folder

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#217]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

I am trying to build an application image on Apple M1.
I am getting the following error when executing `mvn package`
`bless: The 'openfolder' is not supported on Apple Silicon devices`
`DMG image generation failed due to: Command execution failed: bless --folder`

```
jpackage --version
18.0.1
```

```
java -version
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode)
```

```
sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
```

- Build tool: 
	- [X] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

```
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.6</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <!-- mandatory -->
                            <mainClass>${main-class}</mainClass>
                            <!-- optional -->
                            <bundleJre>true</bundleJre>
                            <generateInstaller>true</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>mac</platform>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by fvarrui** [comment]
Hi @kerner1000!

Please, have a look to [issue-184](https://github.com/fvarrui/JavaPackager/issues/184) ... this problem was reported and is fixed in JavaPackager 1.6.7-SNAPSHOT. Try to install this version manually to your local repo until 1.6.7 is released to Maven Central:

```bash
git clone https://github.com/fvarrui/JavaPackager --branch issue-187
cd JavaPackager
./gradlew publishToMavenLocal
```

and then change JavaPackager version in your POM from `1.6.6` to `1.6.7-SNAPSHOT`.

Please, give some feedback.

Thanks!

**Comment by fvarrui** [comment]
JavaPackager doesn't use `jpackage` tool.

**Comment by kerner1000** [comment]
That worked, thanks a lot!
