### ISSUE TITLE
special jreFolder name and launch4j fileVersion

### ISSUE THREAD

**Issue by yan1989** [fvarrui/JavaPackager#22]
Thank you very much for developing such a useful plug-in for us！I have two issues
1、Allow a configurable folder name for  jreFolder，the defalut is "jre" ,but I want to call that "runtime"、“mini-jre”......， like the https://github.com/openjfx/javafx-maven-plugin/
2、Allow more configurable options for launch4j，
 like fileVersion,txtFileVersion,productVersion,txtProductVersion....

**Comment by fvarrui** [comment]
Here you have. Two new properties:
1. `jreDirectoryName`.
2. [`versionInfo`](https://github.com/fvarrui/JavaPackager#-version-information-property-example-using-default-values).

They are available on v0.9.4-SNAPSHOT, so you have to install it manually on your local Maven repo. You can follow [this steps](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin) to install a JavaPackager SNAPSHOT version.

Thanks to you for using JavaPackager!

**Comment by fvarrui** [comment]
[v0.9.4](https://github.com/fvarrui/JavaPackager/releases/tag/v0.9.4) published on Maven Central
