### ISSUE TITLE
Custom JRE not handled properly

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#223]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

I defined a custom JRE to use:

```
<bundleJre>true</bundleJre>
<packagingJdk>src/main/resources/jdk/temurin-18.jdk/Contents/Home</packagingJdk>
```

I deleted all binaries that are not needed from this JRE:

![Screenshot 2022-07-14 at 14 35 32](https://user-images.githubusercontent.com/13817521/178983707-651c1bce-c81c-4fe3-824d-303b13e354e5.png)

When I look at the generated app file, I see binaries which should not be there. My only explanation is, that the JRE Bundler did not copy resources from the right source directory.

![Screenshot 2022-07-14 at 14 36 42](https://user-images.githubusercontent.com/13817521/178984061-f29c5371-d2eb-4f23-99f4-01b5550b29f7.png)

**Comment by fvarrui** [comment]
Hi @kerner1000!
How did you manage to fix this issue? Just ommiting `packagingJdk` property?

**Comment by kerner1000** [comment]
Hi @fvarrui , It was my mistake, I set the wrong property (`packagingJdk`instead of `jrePath`). With `jrePath` it seems to work as intended :)
