### ISSUE TITLE
Add support for a provisionprofile

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#224]
I'm submitting a…

- [ ] bug report
- [X] feature request
- [ ] other

**Short description of the issue/suggestion:**

Some App Store features require the presence of a "provisionprofile". It needs to be packaged into the `Contents` folder.

**Comment by fvarrui** [comment]
I've just merged your PR ... thanks!

**Comment by kerner1000** [comment]
Thank you a lot for your work, I am now able to use your plugin to build and upload to the app store without violations. I will prepare some documentation and pull requests :)

**Comment by fvarrui** [comment]
Great! I'm happy to hear that
