### ISSUE TITLE
There will be some function exceptions when generating custom JRE

### ISSUE THREAD

**Issue by lhDream** [fvarrui/JavaPackager#228]
I'm submitting a…
- [x] bug report

There will be some function exceptions when generating custom JRE.
The simplest example:
```java
public static void main(String[] args) {
        try {
            String url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=zh-CNdt=t&q=" + URLEncoder.encode("word", "UTF-8");
            URL serverUrl = new URL(url);
            HttpURLConnection conn = (HttpURLConnection) serverUrl.openConnection();
            conn.setRequestMethod("GET");
            conn.setRequestProperty("Content-type", "application/json");
            conn.setInstanceFollowRedirects(false);
            conn.connect();
        }catch (Exception e) {
            // javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
            e.printStackTrace();
        }
        System.out.println("Enter any character to end.");
        Scanner scanner = new Scanner(System.in);
        scanner.nextLine();
        scanner.close();
    }
```
Plug in configuration:
```xml
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>1.6.6</version>
    <executions>
        <execution>
            <id>bundling-for-windows</id>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <mainClass>${mainClass}</mainClass>
                <platform>windows</platform>
                <bundleJre>true</bundleJre>
                <customizedJre>true</customizedJre>
                <copyDependencies>true</copyDependencies>
                <generateInstaller>false</generateInstaller>
                <winConfig>
                    <headerType>console</headerType>
                    <generateMsi>false</generateMsi>
                    <generateSetup>false</generateSetup>
                </winConfig>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by lhDream** [comment]
```shell
java version: openjdk version "17.0.2" 2022-01-18
```

**Comment by lhDream** [comment]
Hi @fvarrui 
You're right. How to judge which module is missing or which module is missing?

**Comment by fvarrui** [comment]
Hi @lhDream!
That is a very good question. `jdeps` helps to find modules which require others explicitly, but with services I really don't know it

**Comment by fvarrui** [comment]
I'm working on adding support for Java Modules in JavaPackager, and I'm learning about all this. I hope I can find a way to improve the dependencies analysis to avoid these issues

**Comment by lhDream** [comment]
Hi @fvarrui 
    It may be considered that when the client uses communication related functions, the corresponding module of the server should be added.Or add plug-in support like Lombok?
    Although I am using jdk17, I don't know much about Java modularity In fact, many people are using java8 :smile:

**Comment by lhDream** [comment]
I tried creating a modular project and adding the jdk.crypto.ec module, but jedps still can't find the module. :confused:
```java
module test{
    exports test;
    requires jdk.crypto.ec;
    requires java.base;
}
```
![image](https://user-images.githubusercontent.com/41568266/179884369-7999c8ea-581a-47ba-a7a2-04cae1c3314c.png)

**Comment by fvarrui** [comment]
Hi @fvarrui!

> I tried creating a modular project and adding the jdk.crypto.ec module, but jedps still can't find the module. 😕

It's a bit weird 🤷‍♂️ 

After some googling, I've found an [article](https://blog.adoptium.net/2021/10/jlink-to-produce-own-runtime/) which confirms that this could happens, but it doesn't explain why:

![image](https://user-images.githubusercontent.com/4354486/179939851-dfa00031-56eb-4382-bb3a-eee4442b4145.png)

:slightly_frowning_face:

**Comment by fvarrui** [comment]
No, this is not the problem 😞 

> I'm not sure about this, but maybe it's due to `jdk.crypto.ec` module doesn't export anything:
> 
> ```java
> module jdk.crypto.ec {
>     provides java.security.Provider with sun.security.ec.SunEC;
> }
> ```
> 
> It just provides an implementation of the `java.security.Provider` interface 🤷‍♂️

**Comment by lhDream** [comment]
Maybe because of SPI. 🤔 I'm not sure.
