### ISSUE TITLE
A new packaging tool can integrate into your plugin

### ISSUE THREAD

**Issue by yan1989** [fvarrui/JavaPackager#23]
Hi，Yesterday, JDK14 was released with a new [packaging tool](https://docs.oracle.com/en/java/javase/14/docs/specs/man/jpackage.html)  ，that you can integrate into your plug-in if you are interested.

The jpackage tool will take as input a Java application and a Java run-time image, and produce a Java application image that includes all the necessary dependencies. It will be able to produce a native package in a platform-specific format, such as an exe on Windows or a dmg on macOS.

**Comment by fvarrui** [comment]
That would force developers to use JDK 14, but I'll give it a chance.

Please, take a look to [jlink-jpackager-maven-plugin](https://agilhard-oss.github.io/jlink-jpackager-maven-plugin/site/index.html). It's possible that this plugin makes JavaPackager obsolete. Or not ;-D

Thanks for your comment!
