### ISSUE TITLE
Support custom Info.plist

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#242]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
.
Add support to use a custom `Info.plist` file.

**Comment by kerner1000** [comment]
Don't worry, already working on this issue, PR soon! ;)

**Comment by fvarrui** [comment]
It seems you are enjoying a lot contributing to JavaPackager 😃

**Comment by kerner1000** [comment]
> It seems you are enjoying a lot contributing to JavaPackager 😃

It's a total pain to package a Java App for the Apple App Store. Not giving up yet ;)
JavaPackager is a great PlugIn already, I want to tweak it a bit to ship around all the ugly Apple pitfalls ;)
I hope all what you need in the end is really not more than a `mvn deploy` 😎

**Comment by fvarrui** [comment]
> Don't worry, already working on this issue, PR soon! ;)

Is there news about that issue?

**Comment by kerner1000** [comment]
Its already merged :)
https://github.com/fvarrui/JavaPackager/pull/244
