### ISSUE TITLE
rpm generation fails

### ISSUE THREAD

**Issue by fvarrui** [fvarrui/JavaPackager#25]
`rpm` package generation fails sometimes. In addition, `alien` command requires root privileges to convert the `deb` package to `rpm`, and also it has to generate `deb` package first. Try alternative method: [rpm-maven-plugin](https://www.mojohaus.org/rpm-maven-plugin/).

**Comment by fvarrui** [comment]
Fixed on v0.9.5

**Comment by tajetaje** [comment]
I'm still having trouble with this on 0.9.7
```
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:0.9.7:package (default) on project DebateApp: Unable to execute mojo: The parameters 'sourceEncoding' for goal org.codehaus.mojo:rpm-maven-plugin:2.2.0:rpm are missing or invalid -> [Help 1]
```

**Comment by fvarrui** [comment]
Please, try to specify source encoding in your `pom.xml`:
```xml
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>
```

**Comment by tajetaje** [comment]
Nope, same issue. I'm running under Ubuntu 18.04 WSL if that makes a difference, but I haven't had any other issues with Maven so I doubt it would.

**Comment by fvarrui** [comment]
Ok, I'll try to repoduce your issue. Could you share your plugin configuration and `mvn -v` output?
Thanks!

**Comment by tajetaje** [comment]
Full pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <maven.compiler.target>11</maven.compiler.target>
        <maven.compiler.source>11</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>0.9.7</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <!-- mandatory -->
                            <mainClass>main.java.DebateAppMain</mainClass>
                            <!-- optional -->
                            <bundleJre>true</bundleJre>
                            <generateInstaller>true</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>auto</platform>
                            <organizationUrl>https://github.com/tajetaje</organizationUrl>
                            <url>https://github.com/tajetaje/DebateApp</url>
                            <!-- Must provide JRE for macOS: -->
                            <jrePath>${basedir}/../Libraries/Java/jdk-11.0.7-full.jdk</jrePath>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <groupId>tajetaje</groupId>
    <artifactId>DebateApp</artifactId>
    <version>2.0.0</version>
    <dependencies>
        <dependency>
            <groupId>org.jfxtras</groupId>
            <artifactId>jmetro</artifactId>
            <version>11.6.12</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>11.0.1</version>
        </dependency>
    </dependencies>
</project>
```

mvn -v
```

```

**Comment by fvarrui** [comment]
I hope you don't mind but I [forked your app](https://github.com/fvarrui/DebateApp) and adapted a bit your `pom.xml`.

# Testing on Ubuntu 18.04 WSL 
When I try to build your app on Ubuntu 18.04 WSL, `rpmbuild` throws a segmentation fault (return code 139):
![image](https://user-images.githubusercontent.com/4354486/83934614-38f3c480-a7aa-11ea-8c96-50b97a9188a8.png)
Environment:
![image](https://user-images.githubusercontent.com/4354486/83934676-9a1b9800-a7aa-11ea-9021-56773d80a574.png)
Why? I don't know.

# Testing on Ubuntu 18.04 in a virtual machine:
RPM file is built without problems:
![image](https://user-images.githubusercontent.com/4354486/83934863-99373600-a7ab-11ea-826d-e02a7e02e436.png)

Sorry, but I'm not sure where the problem is! I've not been able to reproduce your issue. I don't know if it's related to JavaPackager, rpm-maven-plugin or rpmbuild.

Use profiles if you only need `jrePath` property on MacOS:
```xml
<!-- Must provide JRE for macOS: -->
<profiles>
	<profile>
		<activation>
			<os>
				<name>mac</name>
			</os>
		</activation>
		<properties>
                        <jrePath>${basedir}/../Libraries/Java/jdk-11.0.7-full.jdk</jrePath>
		</properties>
	</profile>
</profiles>
```

**Comment by tajetaje** [comment]
Well, the RPM thing is annoying but thanks for the tip about profiles!

**Comment by fvarrui** [comment]
> ## Testing on Ubuntu 18.04 WSL
> When I try to build your app on Ubuntu 18.04 WSL, `rpmbuild` throws a segmentation fault (return code 139):
> ![image](https://user-images.githubusercontent.com/4354486/83934614-38f3c480-a7aa-11ea-8c96-50b97a9188a8.png)

I managed to fix this problem running next command `rpm --rebuilddb`, and then generate RPM for your app without problems:

![image](https://user-images.githubusercontent.com/4354486/85073207-4a799b00-b1b2-11ea-9fae-0ce19d694d80.png)

**Comment by fvarrui** [comment]
Sorry! The problem I reported had nothing to do with your issue. But, finally I managed to build RPM file for your app from Ubuntu 18.04 WSL.
