### ISSUE TITLE
Support mobile platforms (Android and iOS)

### ISSUE THREAD

**Issue by Osiris-Team** [fvarrui/JavaPackager#260]

**Comment by fvarrui** [comment]
Hi @Osiris-Team!
Wow, that's an ambitious proposal. Please, could you describe it a little more?
Thank you!!

**Comment by Osiris-Team** [comment]
Yeah it should be possible to run fx applications on those platforms:
https://stackoverflow.com/questions/20860931/is-it-possible-to-run-javafx-applications-on-ios-android-or-windows-phone-8
