### ISSUE TITLE
Javafx cannot find the main class when using JavaPackager

### ISSUE THREAD

**Issue by ftwl2733** [fvarrui/JavaPackager#268]
I'm submitting a…

- [√ ] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Javafx cannot find the main class when using JavaPackager, and the package cannot start the program, whether it is a jar or an exe, but the main class has been declared in mainClass or cannot be started successfully. It is preliminarily found that the problem is that jdk *+has separated javafx, but it can only be restarted after introducing the model externally. It is unknown whether JavaPackager can introduce the model

**Steps to reproduce the issue/enhancement:**

1. [First Step]
Introducing plugin

3. [Second Step]
mvn package 

5. [Other Steps...]
Idea start jar

**What is the expected behavior?**

The graphical interface of Windows will appear

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

After packaging, you need to import the javafx sdk into the virtual machine option to start the program. If you do not import the sdk, the following error will occur that the main class cannot be loaded

![image](https://user-images.githubusercontent.com/39188424/198865336-8d5d1c93-e1b4-49b1-a749-20fd9950d717.png)

![image](https://user-images.githubusercontent.com/39188424/198865395-d5b1958d-2849-495b-a75e-6ee05d14cb06.png)

Now my solution is to input the winning command line of bat to execute the jar in disguise, but the exe cannot point to the sdk. I don't know if there are other ways to solve my problem

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:
- OS version: windwos11
- JDK version: jdk19
- Build tool: 
	- [ √] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

Where do you want to add sdks other than those inside the jdk as references in packaging plug-ins

**Comment by lhDream** [comment]
pom.xml
```xml
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-fxml</artifactId>
    <version>17.0.2</version>
</dependency>
<dependency>
    <groupId>org.openjfx</groupId>
    <artifactId>javafx-controls</artifactId>
    <version>17.0.2</version>
</dependency>
...
<mainClass>MainApp</mainClass>
```

class:
```java
class TestApp extends Application{
    @Override
    public void start(Stage stage) {
        stage.show();
    }
}
class MainApp{
    public static void main(String[] args){
        Application.launch(TestApp.class,args);
    }
}
```
Hi @ftwl2733 , try this.

**Comment by lhDream** [comment]
@ftwl2733 可以直接使用这个[demo](https://github.com/lhDream/demo/tree/main/java17Demo/javafxDemo). 这个是javafx的问题

**Comment by fvarrui** [comment]
Hi @ftwl2733!
Did you finally manage to fix this issue?

**Comment by ftwl2733** [comment]
> 嗨@ftwl2733！您最终设法解决此问题了吗？

暂时是解决了试用jdk命令打包的,可能是这个插件不适合打包javafx程序,有一点不是很理解,是不是只能打包swing但是不能打包javafx

**Comment by lhDream** [comment]
@ftwl2733 不是给了你一个demo么，照着那个demo写就能打包

**Comment by asdfghjkl00001** [comment]
@ftwl2733 你好，请问你这个问题解决了吗？我在使用javapackager的maven插件时，总是构建失败，提示主类不存在或不合法，请问有没有什么解决方法呢？

**Comment by dolang-c** [comment]
@lhDream 你好，我照着你的demo配置了pom文件但是还是打包不成功，并总是提示：The parameters 'mainClass' for goal io.github.fvarrui:javapackager:1.6.7:package are missing or invalid，我确定我已经将示例中的mainClass改成了自己的主类。

**Comment by lhDream** [comment]
@dolang-c 给个图或者你的pom文件跟main函数所在类

**Comment by lhDream** [comment]
@dolang-c 你也可以试试把整个demo拉下来看看能不能打包

**Comment by fvarrui** [comment]
I'm going to close this incident due to lack of activity... reopen it without problem if necessary.
Thanks!

**Comment by ftwl2733** [comment]
> @ftwl2733 不是给了你一个demo么，照着那个demo写就能打包

那个也是打包失败了

**Comment by ftwl2733** [comment]
但是我试用javapackage倒是打包成功了,发现的问题是由于jdk11试用的是module-info是模块化程序,,maven引用的是非模块化的工具包是无法打包的,之后删除这个文件声明为非模块化打包之后还是失败,所以采用了命令打包成功了

**Comment by lhDream** [comment]
![image](https://user-images.githubusercontent.com/41568266/212217438-e7b100b7-b0d8-4793-b220-76fd8282fef4.png)
![image](https://user-images.githubusercontent.com/41568266/212217565-eea33ece-a68d-4c97-9991-2d2a76f47f06.png)

**Comment by lhDream** [comment]
@dolang-c 你可能是这个问题

**Comment by dolang-c** [comment]
谢谢



---Original---
From: ***@***.***&gt;
Date: Fri, Jan 13, 2023 09:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [fvarrui/JavaPackager] Javafx cannot find the main class whenusing JavaPackager (Issue #268)




 
@dolang-c 你可能是这个问题

**Comment by doublez-ten** [comment]
> @ftwl2733 可以直接使用这个[demo](https://github.com/lhDream/demo/tree/main/java17Demo/javafxDemo). 这个是javafx的问题

最初我不是按照这跟demo来的，而是只有这一个
```java
class TestApp extends Application{
    @Override
    public void start(Stage stage) {
        stage.show();
    }
}
```
改成demo里之后，就能正常运行exe了，这是为啥呢，是javafx哪出了问题呢
