### ISSUE TITLE
The console is garbled

### ISSUE THREAD

**Issue by renzhenxuexi0** [fvarrui/JavaPackager#269]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
[INFO]     Bundling JRE ... with E:\software\jdk-17
[INFO]         Creating customized JRE ...
[INFO]         Getting required modules ... 
[INFO]             Executing command: cmd.exe /s /c "E:\software\jdk-17\bin\jdeps -q --multi-release 17 --ignore-missing-deps --print-module-deps E:\workspace_java\demo\target\demo\libs\*.jar E:\workspace_java\demo\target\demo-1.0-SNAPSHOT-runnable.jar"
[INFO]             �����ҳ: 936
[INFO]             java.base,java.desktop,java.scripting,jdk.jfr,jdk.unsupported
[INFO]         Required modules found: [�����ҳ: 936
java.base, java.desktop, java.scripting, jdk.jfr, jdk.unsupported]
[INFO]         
[INFO]         Creating JRE with next modules included: �����ҳ: 936
java.base,java.desktop,java.scripting,jdk.jfr,jdk.unsupported
[INFO]         Using E:\software\jdk-17\jmods modules directory
[INFO]         Executing command: cmd.exe /s /c "E:\software\jdk-17\bin\jlink --module-path E:\software\jdk-17\jmods --add-modules "�����ҳ: 936
java.base,java.desktop,java.scripting,jdk.jfr,jdk.unsupported" --output E:\workspace_java\demo\target\demo\jre --no-header-files --no-man-pages --strip-debug --compress=2"
[INFO]         �����ҳ: 936
[INFO]         ����: ����ָ�� --output
[INFO]         �÷�: jlink <ѡ��> --module-path <ģ��·��> --add-modules <ģ��>[,<ģ��>...]
[INFO]         ʹ�� --help ���г����ܵ�ѡ��
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.264 s
[INFO] Finished at: 2022-11-02T11:16:02+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.6.7:package (default) on project demo: Command execution failed: E:\software\jdk-17\bin\jlink --module-path E:\software\jdk-17\jmods [Ljava.lang.String;@782cc5fa --add-modules �����ҳ: 936
[ERROR] java.base,java.desktop,java.scripting,jdk.jfr,jdk.unsupported --output E:\workspace_java\demo\target\demo\jre --no-header-files --no-man-pages --strip-debug --compress=2
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**

**What is the current behavior?**
<plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.7</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>com.example.demo.HelloApplication</mainClass>
                            <bundleJre>true</bundleJre>
                            <jdkPath>E:\software\jdk-17</jdkPath>
                            <generateInstaller>true</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>windows</platform>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:1.6.7
- OS version:
- JDK version:17
- Build tool: 
	- [ ] Maven 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @renzhenxuexi0!
Please, can you share your `pom.xml` or, at least, JavaPackager plugin config?

**Comment by renzhenxuexi0** [comment]
The dependency coding I added was different. Could I ask you a question about how to quickly convert a modular jar package into a modular one

**Comment by fvarrui** [comment]
Hi @renzhenxuexi0!

> The dependency coding I added was different. Could I ask you a question about how to quickly convert a modular jar package into a modular one

Do you mean to convert a third-party JAR in a modular one?

**Comment by fvarrui** [comment]
I close this issue due to lack of activity. If this problem persists, please reopen it.
Thanks!
