### ISSUE TITLE
JDeps invocation failure on Windows 10, Azul JDK 11, JavaPackager 1.6.1

### ISSUE THREAD

**Issue by jzy3d** [fvarrui/JavaPackager#273]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Packaging fails with the below message (see the --list-deps string array not properly converted to string)
 
`Command execution failed: C:\Program Files\Zulu\zulu-11\bin\jdeps -q --multi-release 11 --list-deps [Ljava.lang.String;@6481dce5 C:\Users\Martin\Dev\jzy3d\external\quantum\target\Quantum\libs\*.jar C:\Users\Martin\Dev\jzy3d\external\quantum\target\Quantum-1.0-runnable.jar
`
**Steps to reproduce the issue/enhancement:**

1. Run mvn clean package 

**What is the expected behavior?**

A successful build

**What is the current behavior?**

The above mentionned failure.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

[JavaPackager-stack.txt](https://github.com/fvarrui/JavaPackager/files/10155975/JavaPackager-stack.txt)

**What is the motivation / use case for changing the behavior?**

Evaluating JavaPackager on Windows.

**Please tell us about your environment:**

- JavaPackager version: 1.6.1
- OS version: Windows 10
- JDK version: Azul JDK 11 (JDK 17 not supported yet)
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @jzy3d!
This problem only happens when printing the executed command arguments, but the command is executed fine. Why are you using JavaPackager 1.6.1? Do you have a sample project in order to reproduce your issue? Maybe you can bypass this issue using customizedJre=false, until we find a solution.

**Comment by jzy3d** [comment]
My mistake, I took 1.6.1 instead of 1.6.7. It is indeed working correctly when using 1.6.7.
Thank you for your answer!
