### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#277]
Hello Sir,

Wen deployment of 1.7.0 to Maven Central?

**Comment by fvarrui** [comment]
Hi @kerner1000!
I have had a lot of trouble last months and I haven't been able to advance what I would have liked 😞 
I think that I'm going to release 1.6.8 with all implemented patches and enhances.

**Comment by fvarrui** [comment]
The most important thing for the move to 1.7.0 is support for JPMS, but it's still in development.

**Comment by kerner1000** [comment]
HI @fvarrui , what is JPMS?

No worries, take your time, I still struggle with Github actions so I continue to build locally for now :)

**Comment by fvarrui** [comment]
JPMS is the Java Platform Module System ... I'm adding support for Java Modules in JavaPackager

**Comment by kerner1000** [comment]
I am deploying a SNAPSHOT version to GitHub Packages and use this for my build now. I created a PR to enable this for your repo as well, if you are interested.

**Comment by fvarrui** [comment]
Hi @kerner1000!
Could you take a look at my comment in [your PR](https://github.com/fvarrui/JavaPackager/pull/281)?
Thanks!

**Comment by fvarrui** [comment]
I can't wait any longer... I'm going to release 1.6.8 with all the patches and improvements, which are quite a lot.
What do you think? Do you agree? 😅

**Comment by fvarrui** [comment]
JavaPackager 1.7.0 released to Maven Central 😆
