### ISSUE TITLE
Automatically build SNAPSHOT versions

### ISSUE THREAD

**Issue by lhDream** [fvarrui/JavaPackager#283]
Hi @fvarrui 
We can automatically build the SNAPSHOT version with the help of [JitPack](https://jitpack.io/).

**Comment by kerner1000** [comment]
We can also publish SNAPSHOTS to Maven Central, can't we?
mvn deploy without release should upload the current SNAPSHOT if I am not mistaken.

**Comment by lhDream** [comment]
Yes, but I don't think unofficial releases should be published to Maven Central.

**Comment by fvarrui** [comment]
> We can also publish SNAPSHOTS to Maven Central, can't we? mvn deploy without release should upload the current SNAPSHOT if I am not mistaken.

I think so ... but some time ago I tried to release SNAPSHOT versions to Maven Central without success. I don't remember what was the problem, but it would be great. I'm going to try it again and figure out what's the problem. 

> Yes, but I don't think unofficial releases should be published to Maven Central.

@lhDream They would have the word "SNAPSHOT" included with the version number, so I don't think that releasing SNAPSHOT versions to Maven Central should be a problem ... and AFAIK, SNAPSHOT versions could be overwritten, as they are artifacts in current development.

**Comment by lhDream** [comment]
Ok looking forward to SNAPSHOT

**Comment by kerner1000** [comment]
> > We can also publish SNAPSHOTS to Maven Central, can't we? mvn deploy without release should upload the current SNAPSHOT if I am not mistaken.
> 
> 
> 
> I think so ... but some time ago I tried to release SNAPSHOT versions to Maven Central without success. I don't remember what was the problem, but it would be great. I'm going to try it again and figure out what's the problem. 
> 
> 
> 
> > Yes, but I don't think unofficial releases should be published to Maven Central.
> 
> 
> 
> @lhDream They would have the word "SNAPSHOT" included with the version number, so I don't think that releasing SNAPSHOT versions to Maven Central should be a problem ... and AFAIK, SNAPSHOT versions could be overwritten, as they are artifacts in current development. 

How do you upload to maven central?
If I remember correctly, you just need to have a snapshot version in your Pom and then call mvn deploy.
(Your Pom needs to extend from sonstype parent which brings all the info needed such as the repository config. For Gradle it should be analogous)

**Comment by fvarrui** [comment]
Hi @kerner1000!
This part of the `build.gradle` does the job:

```groovy
if (project.hasProperty('release')) {

	apply plugin: 'signing'
	apply plugin: 'maven'

	task javadocJar(type: Jar) {
		classifier = 'javadoc'
		from javadoc
	}
	
	task sourcesJar(type: Jar) {
		classifier = 'sources'
		from sourceSets.main.allSource
	}
	
	artifacts {
		archives javadocJar, sourcesJar
	}

	// Signature of artifacts
	signing {
		sign configurations.archives
	}

	// OSSRH publication
	uploadArchives {
		repositories {
			mavenDeployer {
				// POM signature
				beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }
				// Target repository
				repository(url: "https://oss.sonatype.org/service/local/staging/deploy/maven2/") {
					authentication(userName: ossrhUser, password: ossrhPassword)
				}
				pom.project {
					name project.name
					description project.description
					packaging = 'maven-plugin'
					url 'https://github.com/fvarrui/JavaPackager'

					scm {
						connection 'scm:git:git://github.com/fvarrui/JavaPackager.git'
						developerConnection 'scm:git:git@github.com:fvarrui/fvarrui.git'
						url 'https://github.com/fvarrui/JavaPackager'
					}

					licenses {
						license {
							name 'GPL-v3.0'
							url 'http://www.gnu.org/licenses/gpl-3.0.txt'
							distribution 'repo'
						}
					}

					developers {
						developer {
							id = 'fvarrui'
							name = 'Francisco Vargas Ruiz'
							url = 'https://github.com/fvarrui'
						}
					}
				}
			}
		}
	}
	
}the `maven`

nexusStaging {
	username = project.findProperty('ossrhUser') ?: ''
	password = project.findProperty('ossrhPassword') ?: ''
}
```

JavaPackager depends on the `maven`, which was deprecated since Gradle 7.0.0:

```
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead.
```

This is the cause I haven't updated the Gersion yet and the plugin should be built with Java 11 (not higher). I need to change this part and see how I can release SNAPSHOT versions to Maven Central. 

Any help on this would be appreciated!!

**Comment by fvarrui** [comment]
`ossrhUser` and `ossrhPassword` are my OSS Sonatype credentials, stored in my `settings.xml` file.

**Comment by EasyG0ing1** [comment]
@kerner1000 - I publish to "Maven Central" (which is actually Maven is just one of many repositories that "Feed" from a central point) ... using sonatype.org ... once you're set up with a developer account with them (which is free) they have all the detailed instructions about how to configure your POM file for deploying code. There is a lot of setup involved and its kind of tedious but once that's all done, you can cookie cutter your POM file configs and publish anything you want.

They are strict in the sense that once you deploy a package and it gets accepted and published ... it's locked in stone for eternity ... there is no option of going backwards or pulling a successful deployment.

I wasn't aware until reading @fvarrui post just now that -SNAPSHOT tags can give you the option of overwriting successful deployments with updated code... wish I had known that a long time ago and I'm gonna look into it to verify that sonatype does comply with that.

**Comment by fvarrui** [comment]
Hi @EasyG0ing1!
[Maven SNAPSHOT repo VS RELEASE repo](https://www.baeldung.com/maven-snapshot-release-repository)

**Comment by EasyG0ing1** [comment]
@fvarrui - interesting but that article seems to be suggesting that we should be deploying SNAPSHOT versions to a different repository and it even seems to be saying that we need to be maintaining our own personal SNAPSHOT repository for those deployments. 

Do you know if sonatype has a mechanism for handling snapshots differently than release code? ... imma have to look into this further cause it would be really handy to be able to tell people to just change their POM file to pull snapshots when you want them to test out code revs that arent ready for release yet.

**Comment by fvarrui** [comment]
I've finally managed to upload SNAPSHOT versions to Maven Central.

Just add this to your `pom.xml` so Maven can download SNAPSHOT versions:

```xml
	<pluginRepositories>
		<pluginRepository>
			<id>nexus</id>
			<name>nexus-snapshot-repository</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
			<releases>
				<enabled>false</enabled>
			</releases>
		</pluginRepository>
	</pluginRepositories>
```

> Right now `1.7.2-SNAPSHOT` version is uploaded, and it can be overwritten.

> Not sure yet how it would be done in Gradle, but it will be similar. I'll find out soon.

**Comment by fvarrui** [comment]
Then you can use the latest SNAPSHOT version:

```xml
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>1.7.2-SNAPSHOT</version>
    [...]
</plugin>
```

or use an specific version (specifying its timestamp and index):

```xml
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>1.7.2-20230504.125631-4</version>
    [...]
</plugin>
```

**Comment by fvarrui** [comment]
Changes applied and documented into `devel` branch.

**Comment by EasyG0ing1** [comment]
@fvarrui I just started learning and using the Maven Versions plugin which is pretty nice ... it's quite powerful.
