### ISSUE TITLE
Compiled .exe spins off its own thread

### ISSUE THREAD

**Issue by EasyG0ing1** [fvarrui/JavaPackager#284]
I'm submitting a…
- [X] other

**Short description of the issue/suggestion:**

When a program is compiled for Windows, it seems to run as a spin-off into a separate thread. So if, for example, the program were executed from a command prompt, the prompt returns immediately as opposed to the program being run inside that CMD.EXE session. The problem with that is that there is no feedback given to the CMD session from the java program - say for example from System.println statements etc.

Is there a way to alter this behavior for the compiled .EXE?

- JavaPackager version:
- OS version: Windows 11
- JDK version: 19
- Build tool: 
	- [X] Maven

**Comment by fvarrui** [comment]
Hi @EasyG0ing1!
Try with `winConfig.headerType=console`, this option shows `System.println` output.

**Comment by EasyG0ing1** [comment]
@fvarrui 

That did the trick, thank you!
