### ISSUE TITLE
Code-signing for macOS does not sign JRE jars

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#285]

**Comment by kerner1000** [comment]
Already working on it.

**Comment by fvarrui** [comment]
Hi @kerner1000!
Could you provide a detailed description about this issue, please?

**Comment by kerner1000** [comment]
When I test an .app file, that has been bundled using _JavaPackager_ with `codesign --verify,` it complains that a jar file within the JRE path is `not codesigned at all`.

Don't know exactly why this is like that, I am still debugging.

**Comment by fvarrui** [comment]
Hey! What happened with your PR relateed to this issue?

**Comment by kerner1000** [comment]
I cannot reliably say what the problem is, so I cannot provide Andy PR :(
I use jackage now to code sign the app. It also packages it. It works well. I wrote a small maven plugin to do the task.
