### ISSUE TITLE
Support for notarization of macOS apps

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#286]

**Comment by kerner1000** [comment]
Already working on it.

**Comment by fvarrui** [comment]
Great! 
Thanks

**Comment by kia** [comment]
Hi @kerner1000, 
Hi @fvarrui ,
Just a question. Is this enhancement related to the following error message?
```
Reason: no suitable image found.  Did find:
	/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib: 
code signature in (/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib) 
not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary 
(signed with custom identity or adhoc?)
```

Otherwise I would like to open  a new issue for it. This happens on an osx-catalina machine after building the app by `javapackager 1.6.6` .

Thanks a lot.

**Comment by kerner1000** [comment]
> Hi @kerner1000, Hi @fvarrui , Just a question. Is this enhancement related to the following error message?
> 
> ```
> Reason: no suitable image found.  Did find:
> 	/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib: 
> code signature in (/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib) 
> not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary 
> (signed with custom identity or adhoc?)
> ```
> 
> Otherwise I would like to open a new issue for it. This happens on an osx-catalina machine after building the app by `javapackager 1.6.6` .
> 
> Thanks a lot.

This looks like a code-signing problem. Please note that I did not manage to get a valid code-signing using JavaPackager. I use now a Maven Plugin that wrapps JPackager, which works, sorry :((

Notarization is not supported by JavaPackager.

**Comment by kia** [comment]
> > Hi @kerner1000, Hi @fvarrui , Just a question. Is this enhancement related to the following error message?
> > ```
> > Reason: no suitable image found.  Did find:
> > 	/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib: 
> > code signature in (/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib) 
> > not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary 
> > (signed with custom identity or adhoc?)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Otherwise I would like to open a new issue for it. This happens on an osx-catalina machine after building the app by `javapackager 1.6.6` .
> > Thanks a lot.
> 
> This looks like a code-signing problem. Please note that I did not manage to get a valid code-signing using JavaPackager. I use now a Maven Plugin that wrapps JPackager, which works, sorry :((
> 
> Notarization is not supported by JavaPackager.

Hi @kerner1000 ,
could you please name me the plugin you are using as the wrapper of JPackager and how you managed the configuration?
Thanks a lot!

**Comment by kerner1000** [comment]
> > > Hi @kerner1000, Hi @fvarrui , Just a question. Is this enhancement related to the following error message?
> > > ```
> > > Reason: no suitable image found.  Did find:
> > > 	/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib: 
> > > code signature in (/Applications/<application>.app/Contents/PlugIns/jre/Contents/Home/bin/../lib/libjli.dylib) 
> > > not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary 
> > > (signed with custom identity or adhoc?)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Otherwise I would like to open a new issue for it. This happens on an osx-catalina machine after building the app by `javapackager 1.6.6` .
> > > Thanks a lot.
> > 
> > 
> > This looks like a code-signing problem. Please note that I did not manage to get a valid code-signing using JavaPackager. I use now a Maven Plugin that wrapps JPackager, which works, sorry :((
> > Notarization is not supported by JavaPackager.
> 
> Hi @kerner1000 , could you please name me the plugin you are using as the wrapper of JPackager and how you managed the configuration? Thanks a lot!

I use this one:
https://github.com/DrRename/codesign-java-for-mac
It is still under development, but finally I managed to code-sign and notarize my app successfully. Version 3.0.0 should be on Maven Central already.
