### ISSUE TITLE
Created a Mac ICNS Utility

### ISSUE THREAD

**Issue by EasyG0ing1** [fvarrui/JavaPackager#287]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [X] other

**Short description of the issue/suggestion:**
I created a [little program](https://github.com/EasyG0ing1/MacIcns) that can help people make a properly formatted MacOS `.icns` file if you're interested in linking it.

**Comment by fvarrui** [comment]
Hi @EasyG0ing1,
Yeah, cool. I've just added a [reference to your app](https://github.com/fvarrui/JavaPackager/blob/devel/docs/macosx-specific-properties.md#macos-specific-properties) in docs.
Thanks!
