### ISSUE TITLE
Command execution failed: ... -q --multi-release 17 --ignore-missing-deps --print-module-deps...

### ISSUE THREAD

**Issue by Leonardo-Zhou** [fvarrui/JavaPackager#288]
This is my first time to submit an issuse. So I dont know if there is any specification when submitting an issuse. 
I encountered a strange thing while packaging my javafx application to .exe through mvn package.
When I add some dependencies in pom.xml and add them to module-info.java, then some went wrong.

Command execution failed: D:\Program Files\Java\LibericaJDK-17-Full\bin\jdeps -q --multi-release 17 --ignore-missing-deps --print-module-deps [Ljava.lang.String;@54556723 C:\Users\Leo\IdeaProjects\P\target\P\libs\*.jar C:\Users\Leo\IdeaProjects\P\target\P-1.0-SNAPSHOT-runnable.jar

this is my pom.xml
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>PasswordManager</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>PasswordManager</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.9.1</junit.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>19</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>17</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-core</artifactId>
            <version>5.8.11</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <executions>
                    <execution>
                        
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>com.example.p/com.example.p.Main</mainClass>
                            <launcher>app</launcher>
                            <jlinkZipName>app</jlinkZipName>
                            <jlinkImageName>app</jlinkImageName>
                            <noManPages>true</noManPages>
                            <stripDebug>true</stripDebug>
                            <noHeaderFiles>true</noHeaderFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.7</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>

                            <mainClass>com.example.p.Main</mainClass>
                            <bundleJre>true</bundleJre>
                            <generateInstaller>false</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>windows</platform>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>`

my module-info.java
`module com.example.p {
    requires javafx.controls;
    requires javafx.fxml;
    requires hutool.core;

    opens com.example.p to javafx.fxml;
    exports com.example.p;
}`

and I added noting in the HelloController and HelloApplication.
It seems that whatever dependency I add, It will goes wrong.
Woundering if someone can help me.

**Comment by fvarrui** [comment]
@lhDream 
Thanks for giving support!!

**Comment by Leonardo-Zhou** [comment]
I find that when I add selenium to dependencies, it went wrong again. There is no module-info file in my project. And the error is the same.
`Command execution failed: D:\Program Files\Java\LibericaJDK-19-Full\bin\jdeps -q --multi-release 19 --ignore-missing-deps --print-module-deps [Ljava.lang.String;@134a8ead C:\Users\Leo\IdeaProjects\P\target\P\libs\*.jar C:\Users\Leo\IdeaProjects\P\target\P-1.0-SNAPSHOT-runnable.jar
`

**Comment by kerner1000** [comment]
The string array is not expanded:
`[Ljava.lang.String;@134a8ead`
Maybe this helps:
https://github.com/fvarrui/JavaPackager/pull/293

**Comment by fvarrui** [comment]
> The string array is not expanded: `[Ljava.lang.String;@134a8ead` Maybe this helps: #293

I think it's not being expanded only when the executed command arguments are shown, but when run.

**Comment by kerner1000** [comment]
For me it did not work until I applied this PR:
https://github.com/fvarrui/JavaPackager/pull/293

**Comment by fvarrui** [comment]
Hi @Leonardo-Zhou!
Can you try `1.7.1-SNAPSHOT` available on branch `pr-293`. You have to [build and install the plugin manually into your local repo](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin). Give some feedback, please!

**Comment by Leonardo-Zhou** [comment]
> Hi @Leonardo-Zhou! Could you try `1.7.1-SNAPSHOT` available on branch `pr-293`? You have to [build and install the plugin manually into your local repo](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin). Give some feedback, please!

Sorry for my late response. I didn't notice your reply. The issue has been solved and the system is running properly now. Thank you for your help! By the way, I don't really understand what you mean. I am new in Github
