### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by Terrency** [fvarrui/JavaPackager#294]
I am using this plugin to package my kotlin project, 
we use maven-jar-plugin:3.2.2 and spring-boot-maven-plugin:2.7.5 to package our project
after this two steps, it make a app.jar, can work normally
then do javapackager:1.7.1-SNAPSHOT: package phase, make a app-runnable.jar
this jar cannot work with Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
and package steps with an error:

Executing command: cmd.exe /s /c "C:\Users\Administrator\.jdks\corretto-11.0.17\bin\jdeps -q --multi-release 11 --ignore-missing-deps --list-deps F:\ADCModelica\app\target\ModelicaApplication\libs\*.jar F:\ADCModelica\app\target\ModelicaApplication-1.0.0-runnable.jar"
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module java.annotation not found, required by org.apache.tomcat.embed.core

I don't know why does this happen.

Happy to hear some suggestion

**Comment by Terrency** [comment]
I use runnableJar with config
<runnableJar>./target/app-1.0.0.jar</runnableJar>
and make the same error as #246 

[INFO]             Executing command: cmd.exe /s /c "C:\Users\Administrator\.jdks\corretto-11.0.17\bin\jdeps -q --multi-release 11 --ignore-missing-deps --list-deps\app\target\app\libs\*.jar \app\target\app-1.0.0.jar"
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module java.annotation not found, required by org.apache.tomcat.embed.core
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

**Comment by fvarrui** [comment]
Hi @Terrency!

I have to improve the way modular dependencies are analyzed (using `jdeps` tool) in order to generate the customized (reduced) JRE. A work around is to set `customizedJre=false`, but this willl generate a full JRE. If you really need a reduced JRE for your app, you can manually specify the Java core modules you need in your JRE using the `modules` option, but if your app depends on a lot of modules it could be hard.

I hope it helps!

**Comment by Terrency** [comment]
@fvarrui 
Thank you for reply.
i used customizedJre as u suggested.  packaged exe exit without an message. a litter difficult to make it.

**Comment by fvarrui** [comment]
@Terrency Try setting `winConfig.headerType=console` to print stacktrace when running your EXE from console. This way you can see what is happening.

**Comment by lhDream** [comment]
Try this
```cmd
java -jar yourApp.exe
```

**Comment by Terrency** [comment]
Thank you for reply.


It is strange, when I use java -jar app.exe, it runs normal.
but when i double click the exe, nothing happened.




| |
Good Luck
|
|
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/14/2023 09:47 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [fvarrui/JavaPackager] Kotlin Support (Issue #294) |

Try this

java -jar yourApp.exe

**Comment by lhDream** [comment]
Is it a Spring Boot project?

**Comment by lhDream** [comment]
If yes, you can try this configuration.
```xml
<mainClass>org.springframework.boot.loader.JarLauncher</mainClass>
```

**Comment by Terrency** [comment]
Thank you very much, it works. 


Bast Wishes!


| |
Good Luck
|
|
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/14/2023 10:27 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [fvarrui/JavaPackager] Kotlin Support (Issue #294) |

If yes, you can try this configuration.

<mainClass>org.springframework.boot.loader.JarLauncher</mainClass>

**Comment by Terrency** [comment]
Hello Luhua,
do you know something about DisplayName in Windows Task Manager
I start the exe, but the DisplayName shows "OpenJDK Platform binary"
i set many parameters but not work.


| |
Good Luck
|
|
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/14/2023 10:27 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [fvarrui/JavaPackager] Kotlin Support (Issue #294) |

If yes, you can try this configuration.

<mainClass>org.springframework.boot.loader.JarLauncher</mainClass>

**Comment by fvarrui** [comment]
It's because Launch4j runs Java in a different process. Maybe using `winConfig.exeCreationTool=why|winrun4j` instead of Launch4j?

**Comment by Terrency** [comment]
Thank you.
```exeCreationTool=why``` helped, make the right display in windows task manager.
btw winrun4j packaged with an error.


|
|
Good Luck
|
|
|
---- Replied Message ----
| From | Francisco Vargas ***@***.***> |
| Date | 2/14/2023 10:59 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [fvarrui/JavaPackager] Kotlin Support (Issue #294) |

It's because Launch4j runs Java in a different process. Maybe using winConfig.exeCreationTool=why|winrun4j instead of Launch4j?

**Comment by lhDream** [comment]
> 如果是，您可以尝试此配置。
> 
> ```
> <mainClass>org.springframework.boot.loader.JarLauncher</mainClass>
> ```

@fvarrui This configuration should be added to the documentation, or related problem description.
