### ISSUE TITLE
Main class invalid or missing

### ISSUE THREAD

**Issue by CanuckianGamer** [fvarrui/JavaPackager#30]
`<plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>0.9.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>Drivers.Driver</mainClass>
                            <bundleJre>true</bundleJre>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

Drivers.Driver is a valid class and I can access it from jars, but javapackager can't seem to find it

**Comment by fvarrui** [comment]
Hi @CanuckianGamer,
I can't reproduce your problem. 

Please, could you provide more info? 
`mvn -v` and `mvn package` output

You can update plugin version to 0.9.7.

Thanks!

**Comment by CanuckianGamer** [comment]
Maven -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T14:00:29-05:00)
Maven home: C:\Program Files\apache-maven-3.6.1\bin\..
Java version: 1.8.0_231, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jre1.8.0_231
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"


Mvn package
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project TrickleBot: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

Not sure why it thinks that but it's on jdk for sure

**Comment by fvarrui** [comment]
Are you using any IDE?

Maybe you don't have JAVA_HOME environment variable declared.

**Comment by CanuckianGamer** [comment]
Yes I'm currently using Intellij to compile

**Comment by fvarrui** [comment]
Try to declare JAVA_HOME and run maven from command line.

**Comment by fvarrui** [comment]
Another thing: if you use Java 8 or least, in order to bundle JRE, you have to provide its path with `jrePath` config parameter.

For example:
```xml
<jrePath>C:\Program Files\Java\jre1.8.0_231</jrePath>
```

**Comment by CanuckianGamer** [comment]
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:0.9.7:package (default) on project TrickleBot: Could not embed JRE from C:\Program Files\Java\jre1.8.0_231\bin: ${output directory}\jre\bin doe
sn't exist -> [Help 1]

Now it seems I'm getting this error

**Comment by fvarrui** [comment]
What's your JRE path?

Share config please.

**Comment by fvarrui** [comment]
If your code is published on GitHub I could test it.

**Comment by CanuckianGamer** [comment]
I figured it out it was the jre path I had it as /bin instead of just jre_201
