### ISSUE TITLE
deb installation package custom installation path

### ISSUE THREAD

**Issue by lhDream** [fvarrui/JavaPackager#302]
deb installation package to customize the installation path, which can be configured in the configuration file.

**Comment by fvarrui** [comment]
Hi @lhDream!
Yes, that makes sense ... we can add new option `linuxConfig.installationPath` set to `/opt` by default.

**Comment by fvarrui** [comment]
Work in progress in branch `issue-302`

**Comment by fvarrui** [comment]
Snapshot version `1.7.3-20230706.102558-15` published in Maven Central. 
Could you test DEB and RPM packages, please? 
Thanks!

**Comment by fvarrui** [comment]
Hi @lhDream!
Did you test this feature?

**Comment by lhDream** [comment]
> Hi @lhDream! Did you test this feature?

I will test it later.

**Comment by lhDream** [comment]
> Snapshot version `1.7.3-20230706.102558-15` published in Maven Central. Could you test `linuxConfig.installationPath` property with DEB and RPM packages, please? Thanks!

This version 1.7.3-20230706.102558-15 does not seem to exist.

**Comment by fvarrui** [comment]
Snapshot versions are removed from the repo after a while.

I've just released a new version from the branch of this issue: `1.7.3-20230824.111135-18`

**Comment by lhDream** [comment]
Hi @fvarrui 
After testing, both deb and rpm packages can be installed to the specified directory normally.

**Comment by fvarrui** [comment]
Branch issue-302 merged into devel, ready to be released in 1.7.4
