### ISSUE TITLE
No window is displayed after startup

### ISSUE THREAD

**Issue by yangxj96** [fvarrui/JavaPackager#304]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

After a successful build, double-clicking the exe does not display the application window.

**Steps to reproduce the issue/enhancement:**

1 Create a JavaFX project with IDEA,JDK version oracle-jdk-17.0.2, build utility Gradle, version 7.6

![1](https://user-images.githubusercontent.com/37774157/224198487-bac548b6-4515-4502-b09d-5bc1b14158fd.png)

2 Follow the steps for adding JavaPackager in the tutorial

3 run

**What is the expected behavior?**

Open the application normally

**What is the current behavior?**

After double clicking, no window is displayed and there are no errors

**Solution**

1 Create a new class and run the Application using Application.launch(HelloApplication.class, args) from the main function

2 rebuild

3 It is working properly and the window is also displayed

[Case of minimal recurrence problem.zip](https://github.com/fvarrui/JavaPackager/files/10937681/untitled-17.zip)

> Launch.java

``` java

package com.example.untitled;

import javafx.application.Application;

/**
 * launch
 *
 * @author yangxj96
 * @version 1.0.0
 * @date 2023/3/10 9:24
 */
public class Launch {

    public static void main(String[] args) {
        Application.launch(HelloApplication.class, args);
    }

}
```

> build.gradle

```gradle
buildscript {
    repositories {
        maven {
            url 'https://maven.aliyun.com/repository/public/'
        }
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.fvarrui:javapackager:1.7.0'
    }
}


plugins {
    id 'java'
    id 'application'
    id 'org.javamodularity.moduleplugin' version '1.8.12'
    id 'org.openjfx.javafxplugin' version '0.0.13'
    id 'org.beryx.jlink' version '2.25.0'
}

apply plugin: 'io.github.fvarrui.javapackager.plugin'

group 'com.example'
version '1.0-SNAPSHOT'

repositories {
    maven {
        url 'https://maven.aliyun.com/repository/public/'
    }
    mavenCentral()
}

ext {
    junitVersion = '5.9.1'
}

sourceCompatibility = '17'
targetCompatibility = '17'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

application {
    mainModule = 'com.example.untitled'
    mainClass = 'com.example.untitled.Launch'
}

javafx {
    version = '17.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {

    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
    useJUnitPlatform()
}

jlink {
    imageZip = project.file("${buildDir}/distributions/app-${javafx.platform.classifier}.zip")
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'app'
    }
}

jlinkZip {
    group = 'distribution'
}

task packageMyApp(type: io.github.fvarrui.javapackager.gradle.PackageTask, dependsOn: build) {
    // mandatory
    mainClass = 'com.example.untitled.Launch'
    generateInstaller = false
}
```

I don't know why I would create a new class and then use Application.launch(HelloApplication.class, args); Before it can run properly.

Because if you don't change, building with jpackage will work fine .

In JavaPackager, it must be modified to work properly. 

This is not addressed in the JavaPackager guidelines. And I can't find the answer in the search engine.

I wonder if it's me 

- JavaPackager version: 1.7.0
- OS version: win11
- JDK version:  oracle-jdk-17.0.2
- Build tool: 
	- [ ] Maven 
	- [x] Gradle

**Comment by fvarrui** [comment]
Hi @yangxj96! 
It's due by the way your Java app is started. To avoid this your app should manually specify JavaFX modules as VM arguments (using `--add-modules` argument), because right now, JavaPackager is not able to determine which dependencies are modular and which aren't. AFAIK, `jpackage` does. A workaround is to use a POJO as main entry point for your app (in your case `Launch.main()`) instead of directly using a class which extends `Application`. I haven't gone too deep into why this way of starting the app works, but I usually suggest it because it seems very simple to me.

**Comment by fvarrui** [comment]
Oh ... and you can set `winConfig.headerType=console` so that your EXE prints any output (and errors) in console. This way you can know what's happening with your Launch4J EXE.

**Comment by yangxj96** [comment]
@fvarrui  thanks
