### ISSUE TITLE
java.util.NoSuchElementException: No value present - PackageMojo.java:931

### ISSUE THREAD

**Issue by catalean** [fvarrui/JavaPackager#31]
hi,

Was just testing out this plugin with my existing app, which is currently tested only against Java 1.8. Besides getting rid of using String.isBlank() to be able to use this with java 1.8, now I get

Caused by: java.util.NoSuchElementException: No value present
    at java.util.Optional.get (Optional.java:135)
    at io.github.fvarrui.javapackager.PackageMojo.generateDmgImage (PackageMojo.java:931)
    at io.github.fvarrui.javapackager.PackageMojo.execute (PackageMojo.java:347)

I've also seen in the logs the following:
[error] hdiutil: create: Only one image can be created at a time.
[error] Usage:	hdiutil create <sizespec> [options] <imagepath>
[error] 	hdiutil create -help

and 

[error] hdiutil: attach: extra image argument "Run" - "<removed real path>target/assets/<app-name>" already specified
[error] Usage:	hdiutil attach [options] <image>
[error] 	hdiutil attach -help

Any idea? any hints on what the problem is?

Many thx in advance

**Comment by fvarrui** [comment]
Hi @catalean,
Sorry, I need more details. I guess you're on Mac Os X, so I've just tried this [sample app](https://github.com/fvarrui/HelloWorld) on the next environment: MacOS 10.12, JDK 1.8, JavaPackager 0.9.7 ... and it worked fine!

What's your Mac Os X version?

Please, Could you provide `mvn -v` and `mvn package` output and your plugin config?

Thanks!

**Comment by catalean** [comment]
hi,

Thanks for the quick response. I actually used now your hello world project as a base, and it worked just fine :-). I will make a comparison and try to find out the reason. Will let you know.

regards,

**Comment by fvarrui** [comment]
I've taken a look into source code and it seems that `java.util.NoSuchElementException: No value present - PackageMojo.java:931` exception is because `hdiutil` execution fails. This exception is thrown later, when `hdiutil` output is being processed, because `hdiutil` output is not what expected.

Please, tell me if you find out something!

**Comment by catalean** [comment]
Seems like I managed to reproduce this with your sample project. I just added a name to the pom.xml, e.g.:

<name>Hello World</name>

**Comment by fvarrui** [comment]
Ok, `name` property is used by default as volume name for DMG ... so, I think that using blank characters is not a good idea ... but, you can use `macConfig.volumeName` property to override `name` as default value.

**Comment by catalean** [comment]
Yes, the problem was the blank chars in the name, my project had this. All good now, great plugin! btw, thx for your work.

regards

**Comment by fvarrui** [comment]
Maybe JavaPackager can replace automatically blank chars with underscores in the volume name and warn the user.

Thanks for using JavaPackager and your feedback!
