### ISSUE TITLE
Signature fail on Mac if entitlements file not specified

### ISSUE THREAD

**Issue by amariottini** [fvarrui/JavaPackager#313]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Signature fail on Mac if entitlements is not specified 

**Steps to reproduce the issue/enhancement:**
Enable signature like this:
```
macConfig {
        codesignApp = true
        developerId = "XXXXXXXXXX"
        hardenedCodesign = true
        generatePkg = false
        volumeName = "MyVolumeName"
    }
```

**What is the expected behavior?**
Signature applied

**What is the current behavior?**
Error

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
```
Entitlements file not specified. Using defaults!
Executing command: /bin/sh -c cd '/Users/andrea/Projects/projectname/.' && 'find' /Users/andrea/Projects/projectname/build/projectname/projectname.app -depth -type f -exec codesign -f -o runtime -s XXXXXXXXXX --entitlements {} \;
        Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
               codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
               codesign -d [options] path ... # display contents
               codesign -h pid ... # display hosting paths
        Usage: codesign -s identity [-fv*] [-o flags] [-r reqs] [-i ident] path ... # sign
               codesign -v [-v*] [-R=<req string>|-R <req file path>] path|[+]pid ... # verify
               codesign -d [options] path ... # display contents
               codesign -h pid ... # display hosting paths
...............
```

**Please tell us about your environment:**
IntelliJ 2022.3.3
Gradle 7.6

- JavaPackager version: 1.7.0
- OS version: MacOS 10.15.7
- JDK version: 11.0.10
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @amariottini!
This issue seems to be duplicated.
Have a look to #306 
Thanks!

**Comment by amariottini** [comment]
Yes is the same problem, sorry I missed the issue.

**Comment by fvarrui** [comment]
JP 1.7.1 released to Maven Central
