### ISSUE TITLE
Can not bundle my own fat jar

### ISSUE THREAD

**Issue by MartinHeywang** [fvarrui/JavaPackager#32]
# Can not bundle my own fat jar

_Please don't care about errors, if there are some (I'm french)._

I've tried to bundle my own fat jar using `<runnableJar>`, but the plugin can't found my jar. (The logs shows me : 'Application jar does not exists'). I don't know if my path is wrong, or if I need to add the extension `.jar`. I tried to indicate the position of the jar from the project's root.

With an absolute path, it seems to work, it founds the jar, but the log indicates that the output file couldn't be opened after launch4j "Linking" operation.

Hope it's clear (and it helps) !

**Comment by fvarrui** [comment]
Hi @MartinHeywang,
Please, could you share your plugin config and `mvn -v` and `mvn package` output? 
Thanks!

**Comment by MartinHeywang** [comment]
Hi !

Result of `mvn -v` :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\apache-maven-3.6.3\bin\..
Java version: 12.0.2, vendor: Oracle Corporation, runtime: C:\Program Files (x86)\Java\jdk12.0.2
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
My plugin configuration :
```
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>0.9.7</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <mainClass>com.martinheywang.Main</mainClass>
                <!-- I do not want to bundle a JRE (even customized), because my fat jar is lower than 20 MB -->
                <bundleJre>false</bundleJre>
                <!-- In the meantime, using -->
                <runnableJar>${project.build.directory}/${project.artifactId}-${project.version}-jar-with-dependencies.jar</runnableJar>
                <copyDependencies>false</copyDependencies>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Just in case, here is the maven assembly plugin that builds the fat jar :
```
<plugin>
      	<artifactId>maven-assembly-plugin</artifactId>
      	<configuration>
        	<archive>
          		<manifest>
            	                <mainClass>com.martinheywang.Main</mainClass>
          		</manifest>
        	</archive>
        	<descriptorRefs>
          		<descriptorRef>jar-with-dependencies</descriptorRef>
        	</descriptorRefs>
       </configuration>
</plugin>
```

I managed to fix the _Application jar not found_, but the second error that I encountered is still  there (hope I didn't cut some important parts, it was really huge) :
```
[INFO] --- javapackager:0.9.7:package (default) @ Products ---
[INFO] Packaging app for windows
[info] Removing folder [C:\...\absolute_path\...\PRODUCTS\target\Products]
[WARNING] No license file specified
[info] Copying resource [/windows/default-icon.ico] to file [C:\...\absolute_path\...\PRODUCTS\target\assets\Products.ico]
[info] Copying stream to file [C:\...\absolute_path\...\PRODUCTS\target\assets\Products.ico]
[INFO] Using runnable JAR: C:\...\absolute_path\...\PRODUCTS\target/Products-0.5-SNAPSHOT-jar-with-dependencies.jar
[INFO] Creating Windows app bundle...
[INFO] Copying additional resources
[INFO] VersionInfo [companyName=ACME, copyright=ACME, fileDescription=a description, fileVersion=1.0.0.0, internalName=Products, language=null, originalFilename=Products.exe, productName=Products, productVersion=1.0.0.0, trademarks=null, txtFileVersion=0.5-SNAPSHOT, txtProductVersion=0.5-SNAPSHOT]
[INFO] Platform-specific work directory already exists: C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/Heywang/.m2/repository/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] launch4j: Compiling resources
[INFO] launch4j: Linking
[INFO] launch4j: C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\ld.exe: cannot open output file C:\...\absolute_path\...\PRODUCTS\target\Products\Products.exe: No such file or directory
[ERROR]
net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\ld.exe -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\crt2.o C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\head\guihead.o C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\head\head.o C:\Users\Heywang\AppData\Local\Temp\launch4j5921931759440163106o C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libmingw32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libgcc.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libmsvcrt.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libkernel32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libuser32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libadvapi32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libshell32.a -o C:\Users\Heywang\Documents\Prive\Enfants\Martin\Java\Partie2\PRODUCTS\target\Products\Products.exe
    at net.sf.launch4j.Builder.build (Builder.java:149)
    at com.akathist.maven.plugins.launch4j.Launch4jMojo.doExecute (Launch4jMojo.java:432)
    at ...
Caused by: net.sf.launch4j.ExecException: Exec failed (1): C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\ld.exe -mi386pe --oformat pei-i386 --dynamicbase --nxcompat --no-seh --subsystem windows -s C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\crt2.o C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\head\guihead.o C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\head\head.o C:\Users\Heywang\AppData\Local\Temp\launch4j5921931759440163106o C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libmingw32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libgcc.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libmsvcrt.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libkernel32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libuser32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libadvapi32.a C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\w32api\libshell32.a -o C:\Users\Heywang\Documents\Prive\Enfants\Martin\Java\Partie2\PRODUCTS\target\Products\Products.exe
    at net.sf.launch4j.Util.exec (Util.java:156)
    at net.sf.launch4j.Cmd.exec (Builder.java:215)
    at net.sf.launch4j.Builder.build (Builder.java:117)
    at com.akathist.maven.plugins.launch4j.Launch4jMojo.doExecute (Launch4jMojo.java:432)
    at ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

I am running this on Windows. I tried to set the `<platform>` property to linux or mac...and it works in both cases, with a beautiful BUILD SUCESS (but I'm not able to see if the generated file(s) are correct).

Thank you for helping me !

**Comment by fvarrui** [comment]
I've seen launch4j cannot open output file:
```
[INFO] launch4j: C:\Users\Heywang\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\ld.exe: cannot open output file C:\...\absolute_path\...\PRODUCTS\target\Products\Products.exe: No such file or directory
```
I can't figure out why this is happening.

Can you confirm to me if `Products.exe` it's being created on that path?

:warning: Be aware that when running JavaPackager with a `platform` property different from current platform it will only generate app without bundled JRE nor the installer.

**Comment by fvarrui** [comment]
Is this file opened or being executed while you run `mvn package`?

**Comment by fvarrui** [comment]
Sorry, the last question doesn't make sense ... `target/Products` folder is removed at the beginning of the process, and it would fail at that point in this case.

**Comment by fvarrui** [comment]
Sorry, but I can't reproduce your issue. 

Another thing you can do is try this [sample project](https://github.com/fvarrui/HelloWorld) for JavaPackager. I've just adapted it for using a fat JAR and it works fine. Maybe you can make a comparison between yours and this one.

You can also use `mvn -X package` for a full output with debug information and try to figure out why launch4j fails.

**Comment by MartinHeywang** [comment]
Hi @fvarrui !

I apologize I couldn't answer you the last two days.

I tried to adapt my config with your _Hello world_ sample project, but there was nothing to do.

`Products.exe` is never created, that's why he couldn't open it.
In `-X` mode, there is no property that seems incorrect to me before the crash.

As it worked for linux or mac, and your plugin doesn't make an installer if the target platform is different from the current, I thought it should be the problem (I already set the `bundleJre` property to false).

But I check in local maven repo, and in the specified path (`.m2\repository\net\sf`), there should be a `launch4j` folder, but there is only a  `jchardet` and a `jmatio`. So here is the problem : **the launch4j executable that should wrap the jar just doesn't exists**. (I know that I have already the launch4j desktop app installed.) Something surely went wrong when downloading this folder.
How can I get it?

Can you check if this folder exists on your computer?

**Comment by fvarrui** [comment]
Hi @MartinHeywang!
Don't worry, it was weekend 😃.

When you run `mvn package` in `HelloWorld` it crashes?

This is the content of my repository folder `launch4j`:
```
.m2\repository\net\sf\launch4j
└───launch4j
    └───3.12
        │   launch4j-3.12-core.jar
        │   launch4j-3.12-core.jar.sha1
        │   launch4j-3.12-workdir-win32.jar
        │   launch4j-3.12-workdir-win32.jar.sha1
        │   launch4j-3.12-workdir-win32.jar.unpacked
        │   launch4j-3.12.pom
        │   launch4j-3.12.pom.sha1
        │   _remote.repositories
        │
        ├───launch4j-3.12-workdir-win32
        │   ├───bin
        │   │       COPYING
        │   │       ld.exe
        │   │       windres.exe
        │   │
        │   ├───head
        │   │       consolehead.o
        │   │       guihead.o
        │   │       head.o
        │   │       LICENSE.txt
        │   │
        │   ├───head_jni_BETA
        │   │       head.o
        │   │       jniconsolehead.o
        │   │       jniguihead.o
        │   │       jnihead.o
        │   │       LICENSE.txt
        │   │
        │   ├───w32api
        │   │       crt2.o
        │   │       libadvapi32.a
        │   │       libgcc.a
        │   │       libkernel32.a
        │   │       libmingw32.a
        │   │       libmsvcrt.a
        │   │       libshell32.a
        │   │       libuser32.a
        │   │       MinGW.LICENSE.txt
        │   │
        │   └───w32api_jni
        │           crt2.o
        │           libadvapi32.a
        │           libgcc.a
        │           libkernel32.a
        │           libmingw32.a
        │           libmingwex.a
        │           libmoldname.a
        │           libmsvcrt.a
        │           libshell32.a
        │           libuser32.a
        │           MinGW.LICENSE.txt
        │
        └───META-INF
                MANIFEST.MF
```
Sometimes Maven dependencies are not correctly downloaded ... try to remove `launch4j` folder from `.m2` repo and run `mvn package`, so it will be downloaded again.

**Comment by MartinHeywang** [comment]
A good, and a bad news.

First, I cloned your sample project and it worked properly, generated the executable.
This action forced to re-download the missing `launch4j` folder, and it exists now.

So I cleaned up and rebuilt my `target`, but it still doesn't work...
I am trying to figure it out what is different...
I've noticed that it generated a `Products.exe.manifest`, who wasn't there before, and of course the icon, but not the executable itself (it crashed).

The end is near...

**Comment by fvarrui** [comment]
Does it show the same error message?

**Comment by MartinHeywang** [comment]
Wow...
It worked, created a `Products.exe` where it was expected.

I was so glad until I realized that it can't run...
The executable make the expected size, the fat jar is running properly and there are no error message...

I'm getting mad, tired and joyful that it _began to work._

Why? Why me? What?
I have no more words to say.

**Comment by fvarrui** [comment]
So, if you run your app directly from your fat jar file, does it work? Does it show any error message or your Products.exe close silently? Are you sure your main class is right? Is your app for GUI or for console?

**Comment by MartinHeywang** [comment]
My app is a GUI app (a game).

The jar is running properly : no error message, all resources are loaded.
The logs doesn't show any errors.

When I launch the exe, it launches, (I see it loads a little bit), but nothing else happens. There aren't any logs.

I already encountered this problem with others wrappers, so I don't think it's your plugin, but the dependencies that I should copy.

Unfortunately, I'm done for today and I can't test these things until tomorrow.

**Comment by fvarrui** [comment]
Hi @MartinHeywang,
I realized that the executable created by launch4j, when you run from command line, doesn't print any output. This behaviour is due to executable header is setted as `gui` by default.

What if I add a new property called `headerType`, as part of `winConfig` complex property, so you can choose between `console` or `gui` header type? So, if you use `console`, output will be showed when you run from terminal, and you can debug and see your app logs.

**Comment by MartinHeywang** [comment]
Hi @fvarrui !

I thought it was a dependencies mistake, but in fact I made a jar that should contains all of them.

So I enabled the logs with `headerType` (in `winConfig`, there is no `headerType`, so I did it in the main config), and still, nothing shows. (No logs, no errors, nothing, even from my os). It just enables a new line, ready to type something else.

In the Maven Build, there is also no error.

I think something go wrong in the wrapping process (I tried multiple times), but I can't figure it out what. Where an error happens ?

Your HelloWorld sample works properly on my computer.

**Comment by MartinHeywang** [comment]
### ⚠️This post might be off-topic

The `headerType` doesn't work :

``` xml
<configuration>
     [...]
     <!-- No error, doesn't work-->
     <headerType>console</headerType>

     <winConfig>
          <!-- Token not recognized, leads to an error -->
          <headerType>console</headerType>
     </winConfig>
     [...]
</configuration>
```

In debug maven build mode, I saw the `headerType` is still set to gui, which should not. That's why my logs doesn't show anyways.

**Comment by fvarrui** [comment]
Sorry for the misunderstanding! This feature is not yet implemented. I will notify you when it's in version 0.9.8-SNAPSHOT and I'll explain you how to install this version in your system manually. 

I was asking you if you think it is a good idea 😃

**Comment by fvarrui** [comment]
I've just added new property `headerType` as part of `winConfig`, and it works as expected!

![image](https://user-images.githubusercontent.com/4354486/82378237-b84c6e80-9a1c-11ea-9632-179d9835d5ad.png)

![image](https://user-images.githubusercontent.com/4354486/82376445-0c098880-9a1a-11ea-846c-d883486d461a.png)

If you use `<headerType>console</headerType>`, now it opens a terminal and shows output messages.

To install JavaPackager 0.9.8-SNAPSHOT from repo run next commands:

```bash
git clone https://github.com/fvarrio/JavaPackager.git
cd JavaPackager
mvn install
```

I hope it helps you to find the bug!

**Comment by MartinHeywang** [comment]
OK, I'll try this in the evening.

Yesterday, I packaged my app the old way with the launch4j desktop app which shows the logs anyways. It doesn't give so much details, but I understood that there is (don't know why) a dependency problem, as my app doesn't found the JavaFX jars.

My fat jar requires only a jre to work, everything else is included, it can run from anywhere.

But my exe doesn't find my dependency jars and can't find where to copy them (I tried in the same folder, in `libs` subfolder, in a `${name}/libs` subdirectory...).

**Comment by fvarrui** [comment]
Does your main class extend `javafx.application.Application`?

**Comment by fvarrui** [comment]
If it's so, maybe this could solve your problem:
[How to solve "Error: JavaFX runtime components are missing, and are required to run this application"](https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530).

**Comment by MartinHeywang** [comment]
## That was it !
#### Thank you so much !

It finally worked !

**Comment by fvarrui** [comment]
Great! Thanks for using JavaPackager
