### ISSUE TITLE
How to exclude icon file when package

### ISSUE THREAD

**Issue by ClayGminx** [fvarrui/JavaPackager#324]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [] other

As you see, the icon file located in the app directory is unneccessary. So, how to exclude it?
![Worship PPT icon issue](https://github.com/fvarrui/JavaPackager/assets/62022018/217330ad-e9ed-417a-859d-e228b11dfb73)

**Comment by fvarrui** [comment]
Hi @ClayGminx!
Yes, this happens to keep a similar behavior on all platforms, but you are right, in the case of Windows the ICO file doesn't need to be distributed, since it's a resource within the EXE. I can fix it!

**Comment by fvarrui** [comment]
Fixed in 1.7.3-SNAPSHOT. ICO file is no longer added as an additional resource on Windows.
