### ISSUE TITLE
Targetting linux from windows

### ISSUE THREAD

**Issue by 3nigm4** [fvarrui/JavaPackager#326]
[INFO]     Generating AppImage...
[WARNING]         AppImage cannot be generated due to the target platform (linux) is different from the execution platform (windows)!
[WARNING]         AppImage artifact generation skipped!
[WARNING]     AppImage NOT generated!!!

It was not clear to me from the README.md that this is not supported. Could you explain why this is not working?

**Comment by fvarrui** [comment]
Hi @3nigm4!
Did this answer your question?

**Comment by 3nigm4** [comment]
Hi @fvarrui, thank you for the explanation! Yes this answers my question. My next question is how this could be supported. I guess trying to get a PR into appimagetool would be easiest for you, right?

**Comment by fvarrui** [comment]
Hi @3nigm4!

> I guess trying to get a PR into appimagetool would be easiest for you, right?

Sorry, I'm not sure what you mean.

But if what you really want is to generate distributables of your app for all platforms, I suggest you use a CI tool like CircleCI or GitHub Actions.

**Comment by 3nigm4** [comment]
I meant building app images for linux on windows.

**Comment by fvarrui** [comment]
> I meant building app images for linux on windows.

You can't run `appimagetool` from Windows unless you use WSL or something like that. As I recommended to you above, I think you could use a CI tool in order to generate installers for all platforms.

**Comment by 3nigm4** [comment]
I see thank you!
