### ISSUE TITLE
Assumed Java location on Mac is not always right. More robust startup?

### ISSUE THREAD

**Issue by jdimeo** [fvarrui/JavaPackager#33]
Hello again. My coworkers are unable to run my Mac app because for them Java is in a different location than the `startup` script assumes. 

How feasible is it to incorporate a more robust startup stub like
https://github.com/tofi86/universalJavaApplicationStub/
?

**Comment by fvarrui** [comment]
Hi again @jdimeo!

After taking a look at [universalJavaApplicationStub](https://github.com/tofi86/universalJavaApplicationStub), I integrated this script to start Mac applications, following your advice.

It's available in **JavaPackager 1.0.0-SNAPSHOT**, so until I publish this version on Maven Central, you have to [install the plugin manually](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin). Please, test it and tell me if it works fine for you.

It's really helpful when someone opens an issue with a possible solution, thanks so much!

**Comment by fvarrui** [comment]
[v1.0.0](https://github.com/fvarrui/JavaPackager/releases/tag/v1.0.0) released at Maven Central

**Comment by jdimeo** [comment]
Sorry @fvarrui ! I'll try to test this this week

**Comment by fvarrui** [comment]
Don't worry @jdimeo, try it when you can. If it is still failing, we'll reopen the issue
