### ISSUE TITLE
The parameters 'mainClass' for goal io.github.fvarrui:javapackager:1.7.2:package are missing or invalid

### ISSUE THREAD

**Issue by jurimengs** [fvarrui/JavaPackager#330]
I add this plugin , try to package a javafx application ， bug got an error like : 
"The parameters 'mainClass' for goal io.github.fvarrui:javapackager:1.7.2:package are missing or invalid";

            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.7.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            
                            <mainClass>app.vplayer.VplayerApplication</mainClass>
                            
                            <bundleJre>true</bundleJre>
                            <jrePath>/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/jre</jrePath>
                            <generateInstaller>true</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            
                            <platform>mac</platform>
                            <copyDependencies>true</copyDependencies>
                            
                            <displayName>Vplayer</displayName>
                            <name>Vplayer</name>
                            <version>1.0</version>
                            
                            <additionalResources>
                            </additionalResources>
                            
                            <macConfig>
                                <icoFile></icoFile>
                                <generateSetup>false</generateSetup>
                                <generateMsi>false</generateMsi>
                                <generateMsm>false</generateMsm>
                            </macConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

<img width="1173" alt="image" src="https://github.com/fvarrui/JavaPackager/assets/10648133/e38ddb6a-b54b-468e-9fe6-c9b260011243">

IDE is : idea

**Comment by jurimengs** [comment]
osproxy-vplayer can run very very ok by local run , and this is my  class :  "app.vplayer.VplayerApplication" 
<img width="470" alt="image" src="https://github.com/fvarrui/JavaPackager/assets/10648133/c7a421ad-66ab-4e15-98d6-6aaccc6a26d3">

**Comment by fvarrui** [comment]
Hi @jurimengs!
Please, take a look:

https://github.com/fvarrui/JavaPackager/issues/280#issuecomment-1381453170

**Comment by jurimengs** [comment]
it works , thanks
