### ISSUE TITLE
Questions about jdeps and jmod

### ISSUE THREAD

**Issue by oneAsiaPeople** [fvarrui/JavaPackager#343]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Using custom build jre, the program cannot run after the build is completed

**Steps to reproduce the issue/enhancement:**

1. [First Step]
`<bundleJre>true</bundleJre>
`
 2. [Second Step]
`mvn package`
3. [Other Steps...]
Open exe file

**What is the expected behavior?**
It should be like using jar packages directly during development

**What is the current behavior?**
The program cannot execute properly and is stuck in the code using a third-party jar package

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.67
- OS version: win11
- JDK version: jdk11
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @oneAsiaPeople!
Maybe next recommendations could help:
- Upgrade to JavaPackager 1.7.2
- Set `winConfig.headerType=console`, so when running your EXE from command line it shows your app output (maybe it's throwing an exception) ... is your app using JavaFX?

**Comment by fvarrui** [comment]
Issue closed due to lack of activity. Please, if the problem persists, reopen this issue.
Thanks!
