### ISSUE TITLE
打包的exe文件无法运行

### ISSUE THREAD

**Issue by iyutong** [fvarrui/JavaPackager#348]
运行显示  错误: 缺少 JavaFX 运行时组件, 需要使用该组件来运行此应用程序   不知道怎么解决

**Comment by fvarrui** [comment]
Hi @iyutong!
Have a look: https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530
I hope it helps

**Comment by fvarrui** [comment]
Did you manage to fix this issue?

**Comment by iyutong** [comment]
解决了


---原始邮件---
发件人: &quot;Francisco Vargas ***@***.***&gt;
发送时间: 2023年8月22日(周二) 凌晨1:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fvarrui/JavaPackager] 打包的exe文件无法运行 (Issue #348)




 
Did you manage to fix this issue?
 
&mdash;

**Comment by fvarrui** [comment]
Great!! Thanks
