### ISSUE TITLE
Packaging run error

### ISSUE THREAD

**Issue by GuoHuaijian** [fvarrui/JavaPackager#349]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**

I developed my program with springboot and Springboot-Javafx-support, and packaged my program with javapackager with the following error
![image](https://github.com/fvarrui/JavaPackager/assets/49441099/42b5676d-ae54-4818-8c31-185b81578e98)

**Steps to reproduce the issue/enhancement:**
![image](https://github.com/fvarrui/JavaPackager/assets/49441099/64213dbc-4422-4e20-8ff5-510ee202ffa4)

**What is the expected behavior?**

**What is the current behavior?**

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.7.2
- OS version: windows10
- JDK version:11
- JavaFX：17
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by GuoHuaijian** [comment]
Hi@fvarrui!
I change to target/${name} and run java -jar ${name}-${version}-runnable.jar.  But it has an error, Error: JavaFX runtime component is missing and needs to be used to run this application.  Then I change to target/ and running java -jar ${name}-${version}.jar is fine

**Comment by fvarrui** [comment]
> I change to target/${name} and run java -jar ${name}-${version}-runnable.jar. But it has an error, Error: JavaFX runtime component is missing and needs to be used to run this application

Please, try with [this](https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530) tip.

**Comment by fvarrui** [comment]
Also, would it be possible for you to prepare a simple example that reproduces the problem so that I can do some research on this issue?

**Comment by fvarrui** [comment]
Hi @GuoHuaijian!
Any news?

**Comment by fvarrui** [comment]
Issue closed due to lack of activity. Please, if the problem persists, reopen this issue.
Thanks!
