### ISSUE TITLE
Cannot launch JavaFX 14 App on MacOS

### ISSUE THREAD

**Issue by bacnguyen6677** [fvarrui/JavaPackager#35]
Hi,

I have created the macOS installer of a simple JavaFX 14 App with version 1.0.1-SNAPSHOT and VM args like **<vmArgs>"--module-path=${JFX_HOME}/lib --add-modules=javafx.fxml,javafx.controls,javafx.graphics,javafx.media"</vmArgs>**. However, I cannot launch the app (error: com.apple.xpc.launchd[1] (XXX): Service exited with abnormal code: 78 or 1).

I have investigated and found the problem is that vmArg, which is in file **Contents/Info.plist**,  is incorrect.
Then i added above args to file **Contents/MacOS/universalJavaApplicationStub** and double-click on file startup, it worked. It still not work if i double-click on icon app in **Applications**.

Could you please let me know what i am wrong?

Thanks,
Bac Nguyen

**Comment by fvarrui** [comment]
Can you share your plugin configuration and `mvn -v` output, please?

**Comment by bacnguyen6677** [comment]
Hi,

**The plugin config**:
![image](https://user-images.githubusercontent.com/58674665/84023191-da009c00-a9b1-11ea-992d-30a5641951de.png)

**The output of mvn -v**:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/XXX/soft/apache-maven-3.6.3
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"

Thanks,
Bac Nguyen

**Comment by fvarrui** [comment]
Ok, `vmArgs` property is not well specified; you have to do it as follows:
```xml
<vmArgs>
    <vmArg>--module-path=${JFX_HOME}/lib</vmArg>
    <vmArg>--add-modules=javafx.fxml,javafx.controls,javafx.graphics,javafx.media</vmArg>
</vmArgs>
```

**Comment by fvarrui** [comment]
If you specify `vmArgs` this way:
```xml
<vmArgs>--module-path=${JFX_HOME}/lib --add-modules=javafx.fxml,javafx.controls,javafx.graphics,javafx.media</vmArgs>
```
Maven will understand it as:
```xml
<vmArgs>
    <vmArg>--module-path=${JFX_HOME}/lib --add-modules=javafx.fxml<vmArg>
    <vmArg>javafx.controls</vmArg>
    <vmArg>javafx.graphics</vmArg>
    <vmArg>javafx.media</vmArg>
</vmArgs>
```
splitting by commas.

**Comment by bacnguyen6677** [comment]
It still not work.

I modified **pom.xml** as your advice:
![image](https://user-images.githubusercontent.com/58674665/84027920-f6a0d200-a9b9-11ea-8304-4c945e530aea.png)

The output of **Contents/Info.plist**:
![image](https://user-images.githubusercontent.com/58674665/84028060-3ff12180-a9ba-11ea-9eb4-3507a23304c1.png)

if i run with **Contents/MacOS/startup,** i saw an error in the console:
**_The domain/default pair of (kCFPreferencesAnyApplication, AppleLocale) does not Error: JavaFX runtime components are missing, and are required to run this application (1)_**

It can be started via **Contents/MacOS/startup** script If i add the args like this:
![image](https://user-images.githubusercontent.com/58674665/84026851-3ff02200-a9b8-11ea-99d3-7ba3ed9637a6.png)

**Comment by fvarrui** [comment]
Please, leave the startup file as is and try this: [How to solve "Error: JavaFX runtime components are missing, and are required to run this application"](https://github.com/fvarrui/JavaPackager/issues/20#issuecomment-599055530).

**Comment by bacnguyen6677** [comment]
You are right. I have solved the problem.
Thank you very much!
