### ISSUE TITLE
Failed to execute goal io.github.fvarrui:javapackage

### ISSUE THREAD

**Issue by AlexanderCaoyu** [fvarrui/JavaPackager#353]
This is error message:
```[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.6.7:package (default) on project javafx: org.apache.maven.plugin.MojoExecutionException: Failed to build the executable; please verify your configuration.: net.sf.launch4j.ExecException: Exec failed (1): D:\1、java\mvn\net\sf\launch4j\launch4j\3.14\launch4j-3.14-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\ALEXAN~1\AppData\Local\Temp\launch4j8568450954283583138rc C:\Users\ALEXAN~1\AppData\Local\Temp\launch4j660789751684011149o -> [Help 1```

This is my pom.xml:

```
<plugins>
        <plugin>
            <groupId>io.github.fvarrui</groupId>
            <artifactId>javapackager</artifactId>
            <version>1.6.7</version>
            <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>package</goal>
                    </goals>
                    <configuration>
                        <mainClass>alex.learn.MainApp</mainClass>
                        <bundleJre>false</bundleJre>
                        <generateInstaller>false</generateInstaller>
                        <administratorRequired>false</administratorRequired>
                        <platform>windows</platform>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
```
My current java version is 1.8, and the above error occurred when executing the package

**Comment by fvarrui** [comment]
Hi @AlexanderCaoyu!
Please, try the latest JP version: 1.7.3

**Comment by AlexanderCaoyu** [comment]
> 你好@AlexanderCaoyu！ 请尝试最新的 JP 版本：1.7.3
I tried to switch to version 1.7.3, but the error message still appears
```
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.7.3:package (default) on project javafx: org.apache.maven.plugin.MojoExecutionException: Failed to build the executable; please verify your configuration.: net.sf.launch4j.ExecException: Exec failed (1): D:\1、java\mvn\net\sf\launch4j\launch4j\3.50\launch4j-3.50-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\ALEXAN~1\AppData\Local\Temp\launch4j6720689567674490477rc C:\Users\ALEXAN~1\AppData\Local\Temp\launch4j5459996924865524997o -> [Help 1][ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.7.3:package (default) on project javafx: org.apache.maven.plugin.MojoExecutionException: Failed to build the executable; please verify your configuration.: net.sf.launch4j.ExecException: Exec failed (1): D:\1、java\mvn\net\sf\launch4j\launch4j\3.50\launch4j-3.50-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\ALEXAN~1\AppData\Local\Temp\launch4j6720689567674490477rc C:\Users\ALEXAN~1\AppData\Local\Temp\launch4j5459996924865524997o -> [Help 1]
```

**Comment by fvarrui** [comment]
Are you setting any ICO file by storing it in assets dir?

**Comment by AlexanderCaoyu** [comment]
> Are you setting any ICO file by storing it in assets dir?

No, I didn't set up any ICO files.

**Comment by fvarrui** [comment]
Did you manage to fix it? 😮

**Comment by AlexanderCaoyu** [comment]
> Are you setting any ICO file by storing it in assets dir?

No, I didn't set up any ICO files.

>

**Comment by AlexanderCaoyu** [comment]
May I ask whether this is related to the operating system, my own operating system is Win11. But it can run normally on another Win10 operating system.😢

**Comment by fvarrui** [comment]
Maybe it could be related to different Java development environments.
Please, could you share `mvn -v` output on both systems?

**Comment by AlexanderCaoyu** [comment]
> Maybe it could be related to different Java development environments. Please, could you share `mvn -v` output on both systems?

OK,. This is output with Win10 OS
![image](https://github.com/fvarrui/JavaPackager/assets/101630552/07e11039-dc50-45d8-8206-e6fb55d9fa84)

And this is Win11 OS,Which was upgraded last year
![image](https://github.com/fvarrui/JavaPackager/assets/101630552/89107377-76d8-402a-9ec9-2df4edda053f)

**Comment by fvarrui** [comment]
Please, can you manually run this command just after a failed build?

```
D:\1、java\mvn\net\sf\launch4j\launch4j\3.50\launch4j-3.50-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\ALEXAN1\AppData\Local\Temp\launch4j6720689567674490477rc C:\Users\ALEXAN1\AppData\Local\Temp\launch4j5459996924865524997o
```

> Extracted from your output ... not sure if you censored or changed it before publish it

**Comment by AlexanderCaoyu** [comment]
> How can you build your app with Maven on Windows 10 if `JAVA_HOME` env variable is not defined?

I don't know, but I've been building projects on IDEA

**Comment by AlexanderCaoyu** [comment]
> ```
> D:\1、java\mvn\net\sf\launch4j\launch4j\3.50\launch4j-3.50-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\ALEXAN1\AppData\Local\Temp\launch4j6720689567674490477rc C:\Users\ALEXAN1\AppData\Local\Temp\launch4j5459996924865524997o
> ```
> 
> 
>     
>   
> 
> >
Ok, but it tells me that the system cannot find the file specified
![image](https://github.com/fvarrui/JavaPackager/assets/101630552/4a9bd0b3-9d60-463e-a9ee-8e46785706e4)

**Comment by fvarrui** [comment]
Is this path right `D:\1、java\mvn\net\sf\launch4j\launch4j\3.50\launch4j-3.50-workdir-win32\bin\windres.exe`?

**Comment by fvarrui** [comment]
Maybe a weird character in any path on your environment settings? ... I seem to remember that **launch4j** doesn't support CJK characters in paths

**Comment by AlexanderCaoyu** [comment]
> Maybe a weird character in any path on your environment settings? ... I seem to remember that **launch4j** doesn't support CJK characters in paths

Thrank you , you are right. After I changed the path 'D:\1、java' to 'D:\java', it succeeded😊

**Comment by fvarrui** [comment]
Great!!! 😃
