### ISSUE TITLE
exe icon is wrong

### ISSUE THREAD

**Issue by tanhuang2016** [fvarrui/JavaPackager#354]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
I packaged the jar into an exe file and set the icon, but the icon for the exe did not take effect

**Steps to reproduce the issue/enhancement:**

1. [First Step]
this is maven pom
```xml
     <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.7.2</version>
                <executions>
                    <execution>
                        <id>bundling-for-windows</id>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>xyz.hashdog.rdm.ui.Main</mainClass>
                            <bundleJre>true</bundleJre>
                            <jrePath>C:\Program Files\Java\jdk-1.8\jre</jrePath>
                            <generateInstaller>false</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>windows</platform>
                            <createZipball>true</createZipball>
                            <winConfig>
                                <icoFile>src/main/resources/icon/redis256.ico</icoFile>
                            </winConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
2 [Second Step]
The packaged directory already has the icon I set, but the icon of the exe program is wrong
![image](https://github.com/fvarrui/JavaPackager/assets/38677722/3c36f6d3-d890-42c8-b807-9d0ba5cd840e)

**What is the expected behavior?**
exe icon should be the same as the set ico

**What is the current behavior?**
But now you can see that the icon is wrong

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:
- OS version:windows10
- JDK version: jdk1.8.0_371
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @tanhuang2016!
Please, could you share Maven output?

**Comment by fvarrui** [comment]
I'm not able to reproduce your issue ... if I do the same, it works fine.

Oh, and there have been some changes related to icons in Windows in version 1.7.3. Could you try this version?

**Comment by tanhuang2016** [comment]
> 我无法重现您的问题...如果我这样做，它就可以正常工作。
> 
> 哦，在 1.7.3 版本中，Windows 中的图标也发生了一些变化。你能试试这个版本吗？

Switching to 1.7.3 is ok
Thank you for your answer
