### ISSUE TITLE
One or more registry entries have no key and/or value name

### ISSUE THREAD

**Issue by lhDream** [fvarrui/JavaPackager#356]
![image](https://github.com/fvarrui/JavaPackager/assets/41568266/bb992fea-3a1a-4268-af32-6371a32c9de7)

```
My "valueName" and "valueData" are empty characters, which is feasible in Inno setup.
```

![image](https://github.com/fvarrui/JavaPackager/assets/41568266/9ae4bf11-b44b-436e-b1e4-4c1aaf5dc5d3)
https://jrsoftware.org/ishelp/

**Comment by fvarrui** [comment]
Hi @lhDream!
Which JP version are you using?

**Comment by fvarrui** [comment]
Maybe this issue is related to https://github.com/fvarrui/JavaPackager/issues/341

**Comment by lhDream** [comment]
> Hi @lhDream! Which JP version are you using?

1.7.2

**Comment by fvarrui** [comment]
Please, try 1.7.3 ... If the problem persists, I'll code a patch

**Comment by lhDream** [comment]
Hi @fvarrui 
After using the new version, new problems appeared.
![image](https://github.com/fvarrui/JavaPackager/assets/41568266/9cd2ed47-4600-4069-af35-32ab301c103e)

**Comment by lhDream** [comment]
I have tried to configure jdkPath, but it will still use java8 and java17

**Comment by fvarrui** [comment]
Set both jdkPath and packagingJdk

**Comment by fvarrui** [comment]
Maybe it should be improved to add some coherence

**Comment by lhDream** [comment]
> Please, try 1.7.3 ... If the problem persists, I'll code a patch

Good ! Solved.
