### ISSUE TITLE
Do all dependent jar packages have to be obtained from Maven?

### ISSUE THREAD

**Issue by Xiaobaishushu25** [fvarrui/JavaPackager#359]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [ √] other

**Short description of the issue/suggestion:**

Do all dependent jar packages have to be obtained from Maven?My project has many jar which obtained from Maven,and a jar manually introduced by me.

**What is the current behavior?**

now use JavaPackager it report a error：
![RQTLI4 OAN5EW GEX0 }2GH](https://github.com/fvarrui/JavaPackager/assets/76581880/d54d7d13-e9f3-4917-93be-8189ccd3d3af)
The main idea is that I couldn't find the jar package that I manually imported. I flipped through several pages of the issue and couldn't find any similar issues, so I opened this issue.

**Please tell us about your environment:**

- JavaPackager version:
- OS version:windows10
- JDK version:17
- Build tool: 
	- [ √] Maven 
	- [ ] Gradle

**Comment by lhDream** [comment]
@Xiaobaishushu25 使用的本地导入方式是什么

**Comment by Xiaobaishushu25** [comment]
> @Xiaobaishushu25 使用的本地导入方式是什么

我已经知道怎么处理了，只需在pom.xml中添加jar包路径：
`      <dependency>
            <groupId>eawtstub</groupId>
            <artifactId>eawtstub</artifactId>
            <version>1.0.0</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/eawtstub.jar</systemPath>
        </dependency>`
已经成功打包，感谢您的回复
