### ISSUE TITLE
DMG generation fails on Travis-CI: "No value present"

### ISSUE THREAD

**Issue by ogerardin** [fvarrui/JavaPackager#36]
Build fails on Travis-CI on a macOS environment during DMG generation phase with error:
`[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.0.2:package (default) on project xpman-fx-dist: Execution default of goal io.github.fvarrui:javapackager:1.0.2:package failed: No value present -> [Help 1]`

Full build log: https://travis-ci.com/github/ogerardin/xpman/jobs/348812330#L1904

The same POM works fine when building locally on my Mac.

**Comment by fvarrui** [comment]
The plugin tried to mount the brand new DMG file (to configure its content) and it's not returning what's expected:
```
[info]         Executing command: /bin/sh -c cd '/Users/travis/build/ogerardin/xpman/.' && 'hdiutil' attach -readwrite -noverify -noautoopen "/Users/travis/build/ogerardin/xpman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg"
[info]         /dev/disk1          	GUID_partition_scheme  
```
The last output should have shown an entry for the mounted volume. Here is the [code that caused the failure](https://github.com/fvarrui/JavaPackager/blob/3bd608215fbb356a3f6b43ee0e4294c3f5843bd8/src/main/java/io/github/fvarrui/javapackager/packagers/MacPackager.java#L166-L175). 

I've never used Travis before, so I'm not sure if it's possible to run next command to figure out why it's not mounting the DMG file:
```bash
hdiutil attach -readwrite -noverify -noautoopen "/Users/travis/build/ogerardin/xpman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg"
```

**Comment by ogerardin** [comment]
Might be of interest that I'm using a so-called "xcode9.3" macOS image, which is the latest to provide Oracle JDK8 as my project needs it, and is actually macOS 10.13. Details there: https://docs.travis-ci.com/user/reference/osx/#macos-version

This command should be run right after the failure, correct? I can add commands to run after the build but I'm not sure if it will be executed immediately after the failure. Would it help to run Maven in debug mode?

**Comment by ogerardin** [comment]
I modified the Travis config to run the command in case of build failure, but the build worked! 
See: https://travis-ci.com/github/ogerardin/xpman/jobs/348936245#L1888

I didn't change anything in the POM file. I'm really puzzled, could this error happen randomly?

**Comment by ogerardin** [comment]
Next build failed again, so it does look like a random error...

**Comment by fvarrui** [comment]
Hi @ogerardin!
I've never experience this problem before, buy I'll do some research about it. Maybe `CommandUtils.execute()` is not always returning full command execution output.
Thanks!

**Comment by ogerardin** [comment]
Hi, and thanks!
It's annoying because builds are supposed to be reliably repeatable :(
I have noticed that it failed also randomly on my own mac, so it's probably not specific to Travis-CI or macOS 10.13...
Maybe a retry mechanism could help ?

**Comment by fvarrui** [comment]
I've made the next change in [`CommandUtils.execute()`](https://github.com/fvarrui/JavaPackager/commit/e22b6a1ec32ee17ee83c2a9f51244fa90cc0b9aa) static method, used to run system commands, so now it continues processing command output although the associated process ends. 

Please, could you give a try to **1.0.3-SNAPSHOT**?

**Comment by ogerardin** [comment]
DMG generation fails locally, here's the output

```
[info]     Generating DMG disk image file ...
[warn]         Whitespaces has been removed from volume name: X-PlaneManager
[info]         Creating Applications link
[info]         Creating symbolic link [/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/X-Plane Manager/Applications] to [/Applications]
[info]         Copying background image
[info]         Copying resource [/mac/background.png] to file [/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/X-Plane Manager/.background/background.png]
[info]         Copying icon file: /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/assets/mac/X-Plane Manager.icns
[info]         Copying file [/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/assets/mac/X-Plane Manager.icns] to folder [/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/X-Plane Manager/.VolumeIcon.icns]
[info]         Creating image: /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg
[info]         Executing command: /bin/sh -c cd '/Users/olivier/Projects/Idea/XPman/.' && 'hdiutil' create -srcfolder "/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/X-Plane Manager" -volname X-PlaneManager -fs HFS+ -format UDRW "/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg"
[info]         created: /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg
[info]         Mounting image: /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg
[info]         Executing command: /bin/sh -c cd '/Users/olivier/Projects/Idea/XPman/.' && 'hdiutil' attach -readwrite -noverify -noautoopen "/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg"
[info]         /dev/disk3          	GUID_partition_scheme          	
[info]         /dev/disk3s1        	Apple_HFS                      	/Volumes/X-PlaneManager
[info]         - Device name: /dev/disk3s1
[info]         Rendering applescript: /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/customize-dmg.applescript
[info]         Running applescript
[info]         Executing command: /bin/sh -c cd '/Users/olivier/Projects/Idea/XPman/.' && '/usr/bin/osascript' /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/customize-dmg.applescript X-PlaneManager
[error]         /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/customize-dmg.applescript:85:89: execution error: Finder got an error: Can’t get disk "X-PlaneManager". (-1728)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for xpman 1.0-SNAPSHOT:
[INFO] 
[INFO] xpman .............................................. SUCCESS [  1.761 s]
[INFO] xpman-api .......................................... SUCCESS [  8.039 s]
[INFO] xpman-fx ........................................... SUCCESS [  2.972 s]
[INFO] xpman-fx-dist ...................................... FAILURE [ 12.822 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.959 s
[INFO] Finished at: 2020-06-15T14:44:02+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.github.fvarrui:javapackager:1.0.3-SNAPSHOT:package (default) on project xpman-fx-dist: Command execution failed: /usr/bin/osascript /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/customize-dmg.applescript X-PlaneManager -> [Help 1]

```

**Comment by fvarrui** [comment]
As you can see here
```
[info]         Executing command: /bin/sh -c cd '/Users/olivier/Projects/Idea/XPman/.' && 'hdiutil' attach -readwrite -noverify -noautoopen "/Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/X-Plane Manager_1.0-SNAPSHOT.dmg"
[info]         /dev/disk3          	GUID_partition_scheme          	
[info]         /dev/disk3s1        	Apple_HFS                      	/Volumes/X-PlaneManager
[info]         - Device name: /dev/disk3s1
```
now it gets device name, needed to detach the mounted volume later, but fails when running applescript:
```
[info]         Executing command: /bin/sh -c cd '/Users/olivier/Projects/Idea/XPman/.' && '/usr/bin/osascript' /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/customize-dmg.applescript X-PlaneManager
[error]         /Users/olivier/Projects/Idea/XPman/xpman-fx-dist/target/assets/customize-dmg.applescript:85:89: execution error: Finder got an error: Can’t get disk "X-PlaneManager". (-1728)
```
Can you confirm to me if `/Volumes/X-PlaneManager` is mounted when `mvn package` fails?

I think we are close to the solution!

**Comment by ogerardin** [comment]
The dmg was mounted.

- I unmounted it and tried mvn package again and it worked.
- I tried again **without changing anything** and it failed with the same message as before
- I tried again and this time it froze when running the applescript
- I stopped and tried again and it worked

It seems to be totally random!

In any case the problem is with customize-dmg.applescript

**Comment by fvarrui** [comment]
Please, could you share generated `customize-dmg.applescript` and full `mvn package` output when it worked?

**Comment by fvarrui** [comment]
I took the DMG creation process from the script [create-dmg](https://github.com/create-dmg/create-dmg). Searching among its issues I found [this](https://github.com/create-dmg/create-dmg/blob/master/create-dmg). It seems the same problem and they suggest adding delays in the applecript.

**Comment by ogerardin** [comment]
As requested 
Maven log: https://gist.github.com/ogerardin/a92f84419be24323b0fdfe9b9ab74cf6
Generated Applescript: https://gist.github.com/ogerardin/4d9a9063c93f4aeaed85948b7d9950d1

**Comment by ogerardin** [comment]
You might also want to have a look at the script generated by the JavaFX ant task fx:deploy: https://gist.github.com/ogerardin/90a1b4e94de0903b6f58231a4369021a

**Comment by fvarrui** [comment]
I added a 2 seconds delay after mounting DMG and before running applescript, as https://github.com/seltzered/create-dmg/commit/5fe7802917bb85b40c0630b026d33e421db914ea suggests. It's a workaround. This problem seems to be happening only on macOS 10.13 (I'm testing on 10.12 and can't reproduce your issue). Please, try again with new **v1.0.3-SNAPSHOT**.

Maybe a better solution is a loop which breaks when DMG file is mounted.

**Comment by ogerardin** [comment]
I managed to make 3 successful builds in row! 👍 

However, all solutions based on hard delays are hacks and cannot be considered reliable, especially in virtualized environments... 

When you publish 1.0.3 I'll try on Travis-CI. Thanks!

**Comment by fvarrui** [comment]
> However, all solutions based on hard delays are hacks and cannot be considered reliable, especially in virtualized environments...

You are right!

**Comment by fvarrui** [comment]
> When you publish 1.0.3 I'll try on Travis-CI. Thanks!

**v1.0.3** released to Maven Central.

**Comment by ogerardin** [comment]
Seems to work on Travis-CI with version 1.0.3, so I'll close this issue.

**Comment by fvarrui** [comment]
Thanks for helping to improve JavaPackager!!!
