### ISSUE TITLE
Error in universalJavaApplicationStub on Mac

### ISSUE THREAD

**Issue by envas** [fvarrui/JavaPackager#360]
On my Mac there are the following Java versions installed

```
[JavaSearch] Searching for JavaVirtualMachines on the system ...
[JavaSearch] ... found JVM: 20.0.1+10:/Library/Java/JavaVirtualMachines/liberica-jdk-20-full.jdk/Contents/Home/bin/java
[JavaSearch] ... found JVM: 17.0.8.1+1-LTS:/Library/Java/JavaVirtualMachines/liberica-jre-17.jre/Contents/Home/bin/java
[JavaSearch] ... found JVM: 17.0.7+7-LTS:/Library/Java/JavaVirtualMachines/liberica-jdk-17-full.jdk/Contents/Home/bin/java
[JavaSearch] ... found JVM: 11.0.17+7-LTS:/Library/Java/JavaVirtualMachines/liberica-jdk-11-full.jdk/Contents/Home/bin/java
[JavaSearch] ... found JVM: 1.8.0_372-b07:/Library/Java/JavaVirtualMachines/liberica-jdk-8-full.jdk/Contents/Home/bin/java
```

The property `JVM Version` is  17+.  There is an error in the version comparison logic. `comparable_java_version` for my Java 1.8 is 0800037207, for `JVM Version` is 17000000.  The comparison returns true for Java 1.8, and the wrong JRE is selected in runtime

This code returns true for Java 1.8.0_372-b07 when `JVM Version` is set to 17:
```
# pre-requisite: current version number needs to be greater than min version number
if [ "$comp" -ge "$minC" ] ; then
...
```

**Comment by fvarrui** [comment]
Hi @envas!
Thanks for taking the time to find out what's causing this issue. 
`universalJavaApplicationStub` is a fork of this project: https://github.com/tofi86/universalJavaApplicationStub
Please, can you check if this issue persists on newer versions? And if not, open this issue there.

**Comment by envas** [comment]
After Java 1.8 update to 1.8.0.372 (currently latest) the error is gone. This is for me the workaround.

BTW the `universalJavaApplicationStub` project has been archived and is readonly. Not sure if it is still. maintained.

**Comment by fvarrui** [comment]
> BTW the `universalJavaApplicationStub` project has been archived and is readonly. Not sure if it is still. maintained.

Oh! Sorry, I didn't know it

**Comment by fvarrui** [comment]
> After Java 1.8 update to 1.8.0.372 (currently latest) the error is gone. This is for me the workaround.

Ok, happy to hear that 😃
