### ISSUE TITLE
generateSetup ico

### ISSUE THREAD

**Issue by wendao8469759** [fvarrui/JavaPackager#361]
I want to know, on the Windows platform, after configuring <generateSetup>true</generateSetup>, how should I configure the icon for generating the installation program? I tried using <icoFile>, but it didn't work.

**Comment by fvarrui** [comment]
Hi @wendao8469759!
Right now same icon is used for EXE and Setup installer.
You can set it with `winConfig.icoFile` property.
I hope it helps

**Comment by wendao8469759** [comment]
Mmm-hmm. I've configured it to use 'mvn clean package,' but after packaging, the program still hasn't changed the icon. However, I closed the command line and shut down IDEA. After restarting and running 'mvn clean package' again, the icon changed. I suspect it might have been using cached data?

**Comment by fvarrui** [comment]
This behaviour is caused by the Windows Explorer cache. If you kill the `explorer.exe` process and start it again, this problem is solved. Or just wait a while.
