### ISSUE TITLE
SSLHandshakeException after packaging

### ISSUE THREAD

**Issue by RealHypnoticOcelot** [fvarrui/JavaPackager#363]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
After packaging the application, requesting a page using IOUtils throws `javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure`

**Steps to reproduce the issue/enhancement:**

1. 
```java
    public static JSONObject getJson(URI url) {
        String json = null;
        try {
            json = IOUtils.toString(url, StandardCharsets.UTF_8);
            return new JSONObject(json);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```
2. 
```java
try {
     JSONObject infoJSON = getJson(new URI("https://api.open5e.com/races/?format=json"));
} catch (Exception ex) {
    JOptionPane.showMessageDialog(null, ex, "Error!", JOptionPane.ERROR_MESSAGE);
    throw new RuntimeException(ex);
}
```

**What is the expected behavior?**
JSONObject returned with data from webpage

**What is the current behavior?**
SSLHandshakeException

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
![image](https://github.com/fvarrui/JavaPackager/assets/57046530/a4c50915-37ad-4aeb-8cab-41c1d7c8dba3)

**What is the motivation / use case for changing the behavior?**
To fix requesting info from webpages

**Please tell us about your environment:**

- JavaPackager version:
- OS version: macOS Ventura 13.5.2
- JDK version: Oracle OpenJDK v21
- Build tool: 
	- [X] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @RealHypnoticOcelot!
Take a look at this comment https://github.com/fvarrui/JavaPackager/issues/228#issuecomment-1186918861
I hope it helps!

**Comment by RealHypnoticOcelot** [comment]
Thank you, that helped!!
