### ISSUE TITLE
mac packaging with Apple silicon

### ISSUE THREAD

**Issue by nemqooo** [fvarrui/JavaPackager#364]
Hello, packaging JavaFX app on mac with apple sillicon failed on "bless: The 'openfolder' is not supported on Apple Silicon devices". Packaging on mac with intel works without any major issues. Is there a way how to solve this please? Thank you

![Snímka obrazovky 2023-10-02 o 9 54 07](https://github.com/fvarrui/JavaPackager/assets/21354531/cd6db0d7-db82-4906-82fe-740f9b4fd104)

**Comment by fvarrui** [comment]
Hi @nemqooo!
Which JavaPackager version are you using?

**Comment by fvarrui** [comment]
Sorry for the delay

**Comment by fvarrui** [comment]
If you are using the latest JP version and `os.arch` system property is not equal to `aarch64`, maybe you are running an x64 JDK in compatibility mode due to Rosetta??
