### ISSUE TITLE
DMG installer is not generated

### ISSUE THREAD

**Issue by zjor** [fvarrui/JavaPackager#373]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Hi, I'm trying to generate a *.DMG package, it should be generated by default (as the documentation says), but I can't find it.
This is my config:

```xml
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.7.5</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>${exec.mainClass}</mainClass>
                            <bundleJre>true</bundleJre>
                            <generateInstaller>false</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <customizedJre>false</customizedJre>
                            <platform>mac</platform>
                            <macConfig>
                                <appId>world.retvrn.esc</appId>
                                <icnsFile>${project.basedir}/src/main/resources/images/retvrn_logo.png</icnsFile>
                                <generateDmg>true</generateDmg>
                            </macConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Steps to reproduce the issue/enhancement:**

1. Run `mvn clean package`

**What is the expected behavior?**
*.dmg file should be somewhere

**What is the current behavior?**
`target/${artifactid}` contains the app, but not a `*.dmg` file.

**Please tell us about your environment:**

- JavaPackager version: 1.7.5
- OS version: MacOS Sonoma 14.0
- JDK version: java 17.0.5 2022-10-18 LTS
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @zjor!
Could you share JavaPackager output, please?
I've seen that you are not providing a valid ICNS file

**Comment by zjor** [comment]
Hi @fvarrui !
Thank you for replying so fast!

This is the full output of `mvn clean package`:
[out.txt](https://github.com/fvarrui/JavaPackager/files/13276923/out.txt)

**Comment by fvarrui** [comment]
Hi @zjor!
Oh!! I've just realized that `generateInstaller` must be `true` in order to generate DMG

**Comment by zjor** [comment]
Thanks! That's true, also I needed to agree with a XCode license. Now everything works, thank you!
