### ISSUE TITLE
Missing or wrong launch4j dependency

### ISSUE THREAD

**Issue by Pesegato** [fvarrui/JavaPackager#378]
I'm submitting a…

- [X] bug report

**Short description of the issue/suggestion:**

This dependency does not exists on Maven Central, so unless you have something on maven local, version 1.7.3+ won't run

	implementation 'edu.sc.seis.launch4j:launch4j:2.5.2'

**Steps to reproduce the issue/enhancement:**

1. create a project that uses version 1.7.4 on a brand new machine
2. run gradle
3. gradle will complain for the missing dependency

**What is the expected behavior?**

To resolve the dependency

**What is the current behavior?**

To not resolve the dependency

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find edu.sc.seis.launch4j:launch4j:2.5.2.
        Searched in the following locations:
          - https://repo.maven.apache.org/maven2/edu/sc/seis/launch4j/launch4j/2.5.2/launch4j-2.5.2.pom
        Required by:
            project : > io.github.fvarrui:javapackager:1.7.5

**What is the motivation / use case for changing the behavior?**

See above

**Please tell us about your environment:**

- JavaPackager version: 1.7.5
- OS version: Windows 10
- JDK version: 11
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
I've just seen that this dependency is resolved when building the plugin:
```
C:\Users\fvarrui\.m2\repository>tree /f edu
Listado de rutas de carpetas
El número de serie del volumen es C8BB-EDFA
C:\USERS\FVARRUI\.M2\REPOSITORY\EDU
└───sc
    └───seis
        └───launch4j
            └───launch4j
                └───2.5.2
                        launch4j-2.5.2.jar
                        launch4j-2.5.2.jar.sha1
                        launch4j-2.5.2.pom
                        launch4j-2.5.2.pom.sha1
                        _remote.repositories
```
> Just build JP on a freshly installed Windows

I'm

**Comment by Pesegato** [comment]
Still, the README is incorrect. The build.gradle should be:

```
plugins {
    id 'io.github.fvarrui.javapackager.plugin' version '1.7.5'
    id 'edu.sc.seis.launch4j' version '2.5.2'
}
```

**Comment by fvarrui** [comment]
Hi @Pesegato!
I'm happy that you had managed to fix it!! 😃 

Have you tried this way?

```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.fvarrui:javapackager:1.7.5'
    }
}

apply plugin: 'io.github.fvarrui.javapackager.plugin'
```

> As is explained in README.

**Comment by Pesegato** [comment]
Oh this works. I probably have a messy build.gradle, with multiple plugin blocks. Thanks!
