### ISSUE TITLE
icon and names are not generated correctly

### ISSUE THREAD

**Issue by chenmingdu** [fvarrui/JavaPackager#386]
I'm submitting a…

- bug report

**Short description of the issue/suggestion:**

 When using maven to package, icon and names are not generated correctly

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**

Can display my configuration icon

**What is the current behavior?**

The icon I configured is not displayed

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

I have configured the icon according to the documentation, but the generated exe is still the default icon
    
![image](https://github.com/fvarrui/JavaPackager/assets/21030515/71ebdae6-6c76-4d1a-8a71-9b7b845db818)

![image](https://github.com/fvarrui/JavaPackager/assets/21030515/76e46328-692d-413c-b53c-6a8978ee9d8d)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.7.5
- OS version: win10
- JDK version: 11
- Build tool: 
	-Maven 
	

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @chenmingdu!

Windows Explorer caches icons and I guess it's showing the previous EXE icon instead of the new one. Please, see EXE file properties and check if it shows same icon or the right one.

To fix this, just remove all contents in Explorer cache folder: `C:\Users\%username%\AppData\Local\Microsoft\Windows\Explorer`

**Comment by chenmingdu** [comment]
> 你好@chenmingdu！
> 
> Windows 资源管理器缓存图标，我猜它显示的是以前的 EXE 图标而不是新图标。请查看 EXE 文件属性并检查它是否显示相同或正确的图标。
> 
> 要解决此问题，只需删除资源管理器缓存文件夹中的所有内容即可：`C:\Users\%username%\AppData\Local\Microsoft\Windows\Explorer`。也许您还必须终止 Explorer 进程并再次运行它

Ok, I will try it. Thank you for your reply

**Comment by fvarrui** [comment]
Hi @chenmingdu!
Did you manage to fix It?

**Comment by 16637142795** [comment]
![image](https://github.com/user-attachments/assets/15c17c84-b2fe-4207-a02e-0e399d1aff67)
他的路径好像存在问题吧
