### ISSUE TITLE
package error “Unresolved reference”

### ISSUE THREAD

**Issue by Xiaobaishushu25** [fvarrui/JavaPackager#396]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [ √] other

**Short description of the issue/suggestion:**

i use java-package to packaged javafx application，it can run in idea，but when i use   mvn clean package to build，it encounter error.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
PS F:\WorkSpace\Java\IdeaUltimate\Bshell> mvn clean package
[INFO] Scanning for projects...
[WARNING]                                                                                                          
[WARNING] Some problems were encountered while building the effective model for com.example:Bshell:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.systemPath' for eawtstub:eawtstub:jar should not point at files within the project directory, ${project.basedir}/lib/eawtstub.jar 
will be unresolvable by dependent projects @ line 129, column 25
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] -------------------------< com.example:Bshell >-------------------------
[INFO] Building Bshell 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The artifact org.slf4j:slf4j-log4j12:jar:1.7.36 has been relocated to org.slf4j:slf4j-reload4j:jar:1.7.36
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ Bshell ---
[INFO] Deleting F:\WorkSpace\Java\IdeaUltimate\Bshell\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Bshell ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 52 resources
[INFO] 
[INFO] --- kotlin-maven-plugin:1.8.21:compile (compile) @ Bshell ---
[INFO] Applied plugin: 'kotlinx-serialization'
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\MainAPP.kt: (41, 50) Unresolved reference: newVirtualThreadPerTaskExecutor
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\MainAPP.kt: (69, 13) Unresolved reference: tabDragPolicy
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\MainAPP.kt: (69, 37) Unresolved reference: TabDragPolicy
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\test\TestSSH.kt: (111, 39) None of the following functions can be called with the arguments suppli
ed:
public open fun toString(p0: Int): String! defined in java.io.ByteArrayOutputStream
public open fun toString(p0: String!): String! defined in java.io.ByteArrayOutputStream
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\test\TestTab.kt: (55, 13) Unresolved reference: tabDragPolicy
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\test\TestTab.kt: (55, 37) Unresolved reference: TabDragPolicy
[ERROR] F:\WorkSpace\Java\IdeaUltimate\Bshell\src\main\kotlin\xbss\utils\FileCommandPane.kt: (155, 42) Unresolved reference. None of the following candidates is appl
icable because of receiver type mismatch:
public inline fun <T, R> Array<out TypeVariable(T)>.map(transform: (TypeVariable(T)) -> TypeVariable(R)): List<TypeVariable(R)> defined in kotlin.collections        
public inline fun <R> BooleanArray.map(transform: (Boolean) -> TypeVariable(R)): List<TypeVariable(R)> defined in kotlin.collections

**Please tell us about your environment:**
jdk21 + kotlin1.8.21+serialization.version1.6.0

- JavaPackager version:1.7.5
- OS version:windows10
- JDK version:21
- Build tool: 
	- [ √] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by lhDream** [comment]
@Xiaobaishushu25 检查一下你gradle使用的java版本 是不是 java21

**Comment by Xiaobaishushu25** [comment]
> @Xiaobaishushu25 检查一下你gradle使用的java版本 是不是 java21

已设置pom.xml： 
```
<configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
```
               
![image](https://github.com/fvarrui/JavaPackager/assets/76581880/b94f939d-cc73-473d-8c5b-96452eb4d061)
![image](https://github.com/fvarrui/JavaPackager/assets/76581880/d045ad63-2995-40ac-bc24-996ae6ae0308)
![image](https://github.com/fvarrui/JavaPackager/assets/76581880/506252af-302f-4f97-ace0-e52cc92f46ec)
还是一样的错误

**Comment by lhDream** [comment]
@Xiaobaishushu25 双击 Ctrl  输入 java -version 命令看看

**Comment by Xiaobaishushu25** [comment]
> @Xiaobaishushu25 双击 Ctrl 输入 java -version 命令看看

原来是1.8，我改成21后打包成功了，我把项目涉及的版本都改了没有想到是环境变量里面的版本问题，非常感谢！
