### ISSUE TITLE
JavaPackager ignoring runnableJar setting

### ISSUE THREAD

**Issue by almostobvious** [fvarrui/JavaPackager#397]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
I am using proguard to obfuscate my jar. I was hoping to tell JavaPackager to bundle that jar instead of building another one. However, this doesn't seem to work, at least on Windows. Whatever I do, however I specify the runnableJar it's always ignored.

**Steps to reproduce the issue/enhancement:**

1. Unzip attached project. 
2. Update pom.xml to point to your jdk version and modules. This needs to be done in both a) proguard plugin section and b) javapackager section
3. Build package

**What is the expected behavior?**
After installation my installer should deliver tests-runnableJar-obf.jar to the target installation directory.

**What is the current behavior?**
The wrong (unobfuscated) jar called tests-runnableJar-1.0.0-runnable.jar is installed. 

A good way to verify is to open jars in ${project-home}/target in jd-gui (http://java-decompiler.github.io/). This allows you to check actual code that was delivered and confirm.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
Example project
[runnableJar.zip](https://github.com/fvarrui/JavaPackager/files/14781607/runnableJar.zip)

Decompiled code. Left is the code from the jar delivered by the installer. Right is the code from the obfuscated jar.
![runnableJar](https://github.com/fvarrui/JavaPackager/assets/93102382/fe758205-ccad-462d-9b7d-6c7c69bb6770)

- JavaPackager version:
- OS version: 1.7.5
- JDK version: 17
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by almostobvious** [comment]
Resolved it.

In proguard config, I put 

`<outjar>${project.name}-${project.version}-o.jar<outjar>`

... and in java packager config under <configuration> I put

`<runnableJar>target/cosmic-pv-obf.jar</runnableJar>`

This seems to have done the trick.

**Comment by fvarrui** [comment]
> Resolved it.
> 
> In proguard config, I put
> 
> `<outjar>${project.name}-${project.version}-o.jar<outjar>`
> 
> ... and in java packager config under I put
> 
> `<runnableJar>target/${project.name}-${project.version}-o.jar</runnableJar>`
> 
> This seems to have done the trick.

Great! And sorry, I haven't had time to look at your issue in detail, but I'm glad you found a solution. I have plans to support code obfuscation in JP, so your attached sample project will be very helpful. Thanks
