### ISSUE TITLE
With "org.apache.poi" in my project, there is always "module not found" error occured

### ISSUE THREAD

**Issue by payfish** [fvarrui/JavaPackager#399]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

Well i import this org.apache.poi dependency to my project to export a word file. 
```
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>5.2.3</version>
    </dependency>
```
But it comes to an error when i was packaging the proj, i try to import the module which was not founded, but it always comes out another "module not found" error.
```
[ERROR]  Exception in thread "main" java.lang.module.FindException: Module commons.math3 not found, required by org.apache.poi.poi
```
I guess there is a conflict between "org.apache.poi" and JavaPackager because when i deleted the dependency, the Packager works correctly.

**Please tell us about your environment:**

- JavaPackager version:1.7.5
- OS version:Windows11
- JDK version:17.0.9
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by chenyany** [comment]
I also encountered the same problem.

**Comment by fvarrui** [comment]
Hi @chenyany  and @payfish!
I haven't found a solution for this issue yet ... a work around is to set `customizedJre=false` and bundle a full JRE, or manually specify `modules` (but this is a bit tedious). `jdeps` is used to find out which core modules are needed in order to generate a minimal JRE, including only those core modules, but not sure why some non-modular JARs cause this problem.  I'd really appreciate it if you could give me some hint on what options JP should pass to `jdeps` to solve this problem.
Thanks!

**Comment by fvarrui** [comment]
#259

**Comment by fvarrui** [comment]
I researched again about this issue and found [this](https://stackoverflow.com/a/47512109/12214543) answer in StackOverflow, then I tried to add `--add-modules=ALL-MODULE-PATH` to `jdeps` call as explained, and it seems to be working fine. 😮 

I've only tried adding the `poi-ooml` dependency to the `pom.xml` file and it bundles a customized JRE without errors, so I released a SNAPSHOT version, so you can check it: `1.7.6-20240416.203813-5`.

Changes were pushed into `issue-399` branch.

Please, give me some feedback.

Thanks!!

**Comment by fvarrui** [comment]
Doing some tests I just realized that `jdeps` can't find all needed modules when using a fat jar 😢

**Comment by payfish** [comment]
Thank you!! Things works well with the SNAPSHOT version! But here is some little question: when I import the SNAPSHOT plugin I encountered an "Unresolved plugin" error, but I can still package my proj with it, despite the maven sync error.

**Comment by payfish** [comment]
I'm not familiar with **jdeps** so I'm sorry that I can't help, But I believe you have found out the correct anwser to solve this problem. Your work helps me a lot! I appreciate for your time and thank you truely!

**Comment by fvarrui** [comment]
> I'm not familiar with **jdeps** so I'm sorry that I can't help, But I believe you have found out the correct anwser to solve this problem. Your work helps me a lot! I appreciate for your time and thank you truely!

Thanks to you for helping to improve JP

**Comment by payfish** [comment]
> > Thank you!! Things works well with the SNAPSHOT version! But here is some little question: when I import the SNAPSHOT plugin I encountered an "Unresolved plugin" error, but I can still package my proj with it, despite the maven sync error.
> 
> Please, could you post here the error message?

Ofcourse! Maven has downloaded the SNAPSHOT version correctly(I can find it in my local repo). But it still get this error when synchronizing, I tried so many ways but still can't fix it, probably an issue with my configuration. Whatever, it works, I just ignore the error and do the package it works good. thanks!
```
Unresolved plugin: 'io.github.fvarrui:javapackager:1.7.6-20240416.203813-5'
```

**Comment by fvarrui** [comment]
Branch `issue-399` merged into `devel`, ready to be released

**Comment by NewStorm-0** [comment]
> Hi @chenyany and @payfish! I haven't found a solution for this issue yet ... a work around is to set `customizedJre=false` and bundle a full JRE, or manually specify `modules` (but this is a bit tedious). `jdeps` is used to find out which core modules are needed in order to generate a minimal JRE, including only those core modules, but not sure why some non-modular JARs cause this problem. I'd really appreciate it if you could give me some hint on what options JP should pass to `jdeps` to solve this problem. Thanks!

Could you please tell me how to manually specify `modules`  in JavaPackager?

**Comment by sproket** [comment]
How can I test out your pre-release for 1.7.6?

**Comment by payfish** [comment]
> How can I test out your pre-release for 1.7.6?

https://github.com/fvarrui/JavaPackager?tab=readme-ov-file#how-to-use-snapshot-versions

**Comment by fvarrui** [comment]
v1.7.6 released to Maven Central
