### ISSUE TITLE
RPM generation fails on Ubuntu 18.04 WSL

### ISSUE THREAD

**Issue by fvarrui** [fvarrui/JavaPackager#40]
Nope, same issue. I'm running under Ubuntu 18.04 WSL if that makes a difference, but I haven't had any other issues with Maven so I doubt it would.

_Originally posted by @tajetaje in https://github.com/fvarrui/JavaPackager/issues/25#issuecomment-639865711_

**Comment by fvarrui** [comment]
Full pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <properties>
        <maven.compiler.target>11</maven.compiler.target>
        <maven.compiler.source>11</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>0.9.7</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <!-- mandatory -->
                            <mainClass>main.java.DebateAppMain</mainClass>
                            <!-- optional -->
                            <bundleJre>true</bundleJre>
                            <generateInstaller>true</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>auto</platform>
                            <organizationUrl>https://github.com/tajetaje</organizationUrl>
                            <url>https://github.com/tajetaje/DebateApp</url>
                            <!-- Must provide JRE for macOS: -->
                            <jrePath>${basedir}/../Libraries/Java/jdk-11.0.7-full.jdk</jrePath>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <groupId>tajetaje</groupId>
    <artifactId>DebateApp</artifactId>
    <version>2.0.0</version>
    <dependencies>
        <dependency>
            <groupId>org.jfxtras</groupId>
            <artifactId>jmetro</artifactId>
            <version>11.6.12</version>
        </dependency>
        <dependency>
            <groupId>org.controlsfx</groupId>
            <artifactId>controlsfx</artifactId>
            <version>11.0.1</version>
        </dependency>
    </dependencies>
</project>
```

mvn -v
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.7, vendor: BellSoft, runtime: /usr/lib/jvm/bellsoft-java11-full-amd6
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-19635-microsoft", arch: "amd64", family: "unix" 
```

**Comment by fvarrui** [comment]
I hope you don't mind but I [forked your app](https://github.com/fvarrui/DebateApp) and adapted a bit your `pom.xml`.

# Testing on Ubuntu 18.04 WSL 
When I try to build your app on Ubuntu 18.04 WSL, `rpmbuild` throws a segmentation fault (return code 139):
![image](https://user-images.githubusercontent.com/4354486/83934614-38f3c480-a7aa-11ea-8c96-50b97a9188a8.png)
Environment:
![image](https://user-images.githubusercontent.com/4354486/83934676-9a1b9800-a7aa-11ea-9021-56773d80a574.png)
Why? I don't know.

# Testing on Ubuntu 18.04 in a virtual machine:
RPM file is built without problems:
![image](https://user-images.githubusercontent.com/4354486/83934863-99373600-a7ab-11ea-826d-e02a7e02e436.png)

Sorry, but I'm not sure where the problem is! I've not been able to reproduce your issue. I don't know if it's related to JavaPackager, rpm-maven-plugin or rpmbuild.

Use profiles if you only need `jrePath` property on MacOS:
```xml
<!-- Must provide JRE for macOS: -->
<profiles>
	<profile>
		<activation>
			<os>
				<name>mac</name>
			</os>
		</activation>
		<properties>
                        <jrePath>${basedir}/../Libraries/Java/jdk-11.0.7-full.jdk</jrePath>
		</properties>
	</profile>
</profiles>
```

**Comment by fvarrui** [comment]
Hi @tajetaje! I've opened a new issue with your problem. I hope we can find a solution asap!

**Comment by tajetaje** [comment]
Thanks, I'll be back to my main computer tomorrow and I plan to do a bit of work on my packaging workflow so I'll take another crack at it and see what I can figure out.

**Comment by fvarrui** [comment]
> ## Testing on Ubuntu 18.04 WSL
> When I try to build your app on Ubuntu 18.04 WSL, `rpmbuild` throws a segmentation fault (return code 139):
> ![image](https://user-images.githubusercontent.com/4354486/83934614-38f3c480-a7aa-11ea-8c96-50b97a9188a8.png)

I managed to fix this problem running next command `rpm --rebuilddb`, and then generate RPM for your app without problems:

![image](https://user-images.githubusercontent.com/4354486/85073207-4a799b00-b1b2-11ea-9fae-0ce19d694d80.png)

Sorry! The problem I reported had nothing to do with your issue. But, finally I managed to build RPM file for your app from Ubuntu 18.04 WSL.

**Comment by fvarrui** [comment]
I will try to use the same JDK as you.  What language do you have configured in Windows?

**Comment by fvarrui** [comment]
I took a look to `sourceEncoding` property in **rpm-maven-plugin** [code](https://github.com/mojohaus/rpm-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/rpm/AbstractRPMMojo.java#L505-L509):
```java
    /**
     * @since 2.1-alpha-4
     */
    @Parameter( required = true, readonly = true, property = "project.build.sourceEncoding" )
    private String sourceEncoding;
```
which causes your issue because it's missing or invalid:
> I'm still having trouble with this on 0.9.7
> ```
> [ERROR] Failed to execute goal io.github.fvarrui:javapackager:0.9.7:package (default) on project DebateApp: Unable to execute mojo: The parameters 'sourceEncoding' for goal org.codehaus.mojo:rpm-maven-plugin:2.2.0:rpm are missing or invalid -> [Help 1]
> ```
and it takes its value from `${project.build.sourceEncoding}` by default.

I can't figure out why it fails if you specify `project.build.sourceEncoding` in your POM:
```xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```

**Comment by fvarrui** [comment]
When I remove:
```xml
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
```
from your POM
![image](https://user-images.githubusercontent.com/4354486/85185870-dad8de00-b28d-11ea-8004-8c088971c95c.png)
I get this:
![image](https://user-images.githubusercontent.com/4354486/85185907-052a9b80-b28e-11ea-8eb5-956da421a979.png)
So, I only can reproduce your issue this way.
Are you sure that this is [the POM that failed](https://github.com/fvarrui/JavaPackager/issues/40#issuecomment-645035957)?

**Comment by tajetaje** [comment]
Yes I’m sure, and the JDK I use is Liberica JDK full. Come to think of it, it may be failing because the parameter is invalid rather than because it is missing. I’ll play around with some different ways of entering it next time I need to do a package.

**Comment by fvarrui** [comment]
Hi @tajetaje!
Did you find a solution or a work around about this issue?

**Comment by tajetaje** [comment]
> Hi @tajetaje!
> Did you find a solution or a work around about this issue?

I more or less narrowed it down to some kind of issue with my WSL, it works on my bare metal Linux, left the issue open since I never did figure out why it happened, but it seems isolated so I will go ahead and close it out.
