### ISSUE TITLE
mis/exe installation package custom installation path 

### ISSUE THREAD

**Issue by futurecad** [fvarrui/JavaPackager#401]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

**Steps to reproduce the issue/enhancement:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**What is the expected behavior?**

**What is the current behavior?**

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version:
- OS version:
- JDK version:
- Build tool: 
	- [ ] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @futurecad!
What do you need exactly?

**Comment by futurecad** [comment]
It's been solved. I changed it.
[Setup]
DefaultDirName

**Comment by fvarrui** [comment]
> It's been solved. I changed it. [Setup] DefaultDirName

Great! And how did you change MSI installation path?
