### ISSUE TITLE
How can I set the singleInstance property of launch4j through a plugin

### ISSUE THREAD

**Issue by Mr-YiQiJia** [fvarrui/JavaPackager#406]
I'm submitting a…
﻿
- [ ] bug report
- [✓] feature request
- [ ] other
﻿
**Short description of the issue/suggestion:**
I want my program to run as an instance, double-click the program again, and it is not allowed to open new program instances again
How to set the singleInstance property of launch4j through plugins
﻿
﻿
**Steps to reproduce the issue/enhancement:**
﻿Here are some of my configuration files pom.xml

> <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.7.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <bundleJre>true</bundleJre>
                            <jrePath>${basedir}\jre</jrePath>
                            <version>${project.version}</version>
                            
                            <mainClass>${exec.mainClass}</mainClass>
                            <name>CQDXER</name>
                            <displayName>${name}</displayName>
                            <description>x64</description>
                            <organizationName>CQDXER, Inc.</organizationName>
                            <organizationUrl>https://github.com/Mr-YiQiJia/serial_desktop</organizationUrl>
                            <licenseFile>${basedir}/license</licenseFile>
                            <winConfig>
                                <icoFile>${basedir}/src/main/resources/images/favicon.ico</icoFile>
                                <setupLanguages>
                                    <english>compiler:Default.isl</english>
                                    <chinese>compiler:Languages\ChineseSimplified.isl</chinese>
                                </setupLanguages>
                                <exeCreationTool>launch4j</exeCreationTool>
                                <generateSetup>true</generateSetup>
                                <generateMsi>false</generateMsi>
                                
                                <disableDirPage>false</disableDirPage>
                                
                                <disableFinishedPage>false</disableFinishedPage>
                                
                                <disableRunAfterInstall>false</disableRunAfterInstall>
                            </winConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

﻿
**What is the expected behavior?**
﻿I want my program to run as a single instance, double clicking again to display the previous running instance
﻿
**What is the current behavior?**
﻿Each time you double-click to run the program, it will open another instance
﻿
﻿
**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
﻿
![图片](https://github.com/fvarrui/JavaPackager/assets/56389242/e990f44c-c3cd-4854-9977-c72356ca6286)

﻿
﻿
**What is the motivation / use case for changing the behavior?**
﻿I want to control the excessive opening of the program
﻿
﻿
**Please tell us about your environment:**
﻿
- JavaPackager version:1.7.0
- OS version: Windows 10
- JDK version:jdk1.8.0_181
- Build tool: 
- [✓] Maven 
- [ ] Gradle 
﻿
**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Launch4j's `singleInstance` property is not supported by JavaPackager, but maybe you can try this pure Java solution (cross-platform) from [SO](https://stackoverflow.com/a/2002948):

```java
public class Main {

	public static boolean lockInstance(final String lockFile) {
		try {
			final File file = new File(lockFile);
			final RandomAccessFile randomAccessFile = new RandomAccessFile(file, "rw");
			final FileLock fileLock = randomAccessFile.getChannel().tryLock();
			if (fileLock != null) {
				Runtime.getRuntime().addShutdownHook(new Thread() {
					public void run() {
						try {
							fileLock.release();
							randomAccessFile.close();
							file.delete();
						} catch (Exception e) {
							System.err.println("Unable to remove lock file: " + lockFile);
							e.printStackTrace();
						}
					}
				});
				return true;
			}
		} catch (Exception e) {
			System.err.println("Unable to create and/or lock file: " + lockFile);
			e.printStackTrace();
		}
		return false;
	}

	public static void main(String[] args) throws IOException {
		if (lockInstance(System.getProperty("java.io.tmpdir") + File.separator + Main.class.getName() + ".lock")) {
			HelloWorldFrame.main(args);
		}
	}

}
```

I've just tried it and it seems to be working fine and is valid for all platforms, not only Windows.

Anyway, we can add support for Launch4j's `singleInstance` in JP if you really need it.

**Comment by valimaties** [comment]
This simple solution works for me:

```java
private static final int PORT = <WhateverPortYouWant>;
private static final String HOST = "localhost";

public static void main(String[] args) {
  try (Socket socket = new Socket(HOST, PORT)) {
      System.out.println("Application already running");
      ObjectOutputStream oos = new ObjectOutputStream(socket.getOutputStream());
      oos.writeObject("bringToFront");
      oos.flush();
      ObjectInputStream ois = new ObjectInputStream(socket.getInputStream());
      ois.readObject();
      oos.close();
      ois.close();
      socket.close();
      System.exit(0);
  } catch (Exception e) {
      launch(args);
  }
}
```

**Comment by Mr-YiQiJia** [comment]
The current requirement for the program is to have multiple instances. If the program is required to have a single instance in the future, it would be very convenient to have a simple setting. But it's not necessary, it's just an idea.
Your ideas are very good, and I can refer to your ideas. Thank you very much for providing me with help
@fvarrui @valimaties
