### ISSUE TITLE
when I try tro execute the .exe file, it repots  "The application requires a java Runtime Environment"

### ISSUE THREAD

**Issue by shikuicao** [fvarrui/JavaPackager#409]
pom
<plugin>
      <groupId>io.github.fvarrui</groupId>
      <artifactId>javapackager</artifactId>
      <version>1.6.7</version>
      <executions>
          <execution>
              <phase>package</phase>
              <goals>
                  <goal>package</goal>
              </goals>
              <configuration>
                  <mainClass>com.xiaomi.uidemo.Main</mainClass>
                  <bundleJre>true</bundleJre>
                  <jrePath>/usr/lib/jvm/java-8-openjdk-amd64/jre</jrePath>
                  <generateInstaller>true</generateInstaller>
                  <administratorRequired>false</administratorRequired>
                  <platform>windows</platform>
              </configuration>
          </execution>
      </executions>
  </plugin>

**Comment by fvarrui** [comment]
May I help you? Or did you manage to fix it?

**Comment by fvarrui** [comment]
Ok, can you provide more info? (Plugin configuration, your environment, ...)

**Comment by fvarrui** [comment]
Are you building your app for Windows from Linux?

**Comment by shikuicao** [comment]
Yes

---- Replied Message ----
| From | Francisco Vargas ***@***.***> |
| Date | 05/15/2024 22:08 |
| To | fvarrui/JavaPackager ***@***.***> |
| Cc | shikuicao ***@***.***>,
State ***@***.***> |
| Subject | Re: [fvarrui/JavaPackager] when I try tro execute the .exe file, it repots "The application requires a java Runtime Environment" (Issue #409) |

Are you building your app for Windows from Linux?

**Comment by fvarrui** [comment]
> /usr/lib/jvm/java-8-openjdk-amd64/jre

Are you bundling this JRE with your app? I guess it's for Linux

**Comment by fvarrui** [comment]
If so, you have to download a JRE for Windows and bundle this one with your app. As you are using Java 8, you have to bundle a full JRE since it can't generated with `jlink`

**Comment by shikuicao** [comment]
yes, you are so great!   And I  execute cmd "mvn clean pakcage", there is a demo in target dir

target 

   - demo

       - jre

       - libs

       - demo.exe

       - others 

I send the demo.zip to my windows pc, and  try to execute  demo.exe, the it reports the erroe msg.













At 2024-05-15 22:13:20, "Francisco Vargas Ruiz" ***@***.***> wrote:

/usr/lib/jvm/java-8-openjdk-amd64/jre

Are you bundling this JRE with your app? I guess it's for Linux

**Comment by shikuicao** [comment]
ok, I wiil try this way tomorrow, thank you very much !













At 2024-05-15 22:15:39, "Francisco Vargas Ruiz" ***@***.***> wrote:

If so, you have to download a JRE for Windows and bundle this one with your app. As you are using Java 8, you have to bundle a full JRE since it can't be generated with jlink

**Comment by shikuicao** [comment]
```xml
<bundleJre>true</bundleJre>
<jrePath>/home/mi/winJre/jre-8u401-windows-x64/jre1.8.0_401</jrePath>

I use jre for win and  build a app successfully， but when I  execute the UI-demo.exe， it reports "A java Eeception has occurred"
![image](https://github.com/fvarrui/JavaPackager/assets/81000579/eacf86ac-1f51-4172-94fd-2febf94d9738)

**Comment by shikuicao** [comment]
Main.java
```java
public class Main {
    public static void main(String[] args) {
        HelloApplication.main(args);
    }
}

pom.xml
```xml
<project>
    ....
    <plugins>
        <!-- javapackager  -->
            <plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.6.7</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>com.demo.demo.Main</mainClass>
                            <bundleJre>true</bundleJre>
                            <jrePath>/home/mi/winJre/jre-8u401-windows-x64/jre1.8.0_401</jrePath>
                            <generateInstaller>false</generateInstaller>
                            <administratorRequired>false</administratorRequired>
                            <platform>windows</platform>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
    </plugins>
</project>
after "mvn clean package"，there is a dir named "demo", it contains jre dir, libs, demo.exe and demo.ico。 I send demo.zip to  Windowns and unzip ，when I double click demo.exe, It toast, title is "Java Virtual Machine Launcher", content is "A java Exception has occurred"

**Comment by shikuicao** [comment]
I checked my java version :
```shell
java -version
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

then I change the jrePath in pom.xml :
```xml
<jrePath>/home/mi/winJre/jdk-17_windows-x64_bin/jdk-17.0.11</jrePath>

then I  repeated steps as followings:
1.  'mvn clean package'
2.  send demo.zip to windows
3. unzip and  double click the demo.exe
there was nothing happened. I am confused, so I want to ask you for help. I'll appriciate you if you can help to see the problem, thank you , thank you , thank you

**Comment by fvarrui** [comment]
Please, could you share your demo app to take a look into it?

**Comment by shikuicao** [comment]
[demo.zip](https://github.com/fvarrui/JavaPackager/files/15332065/demo.zip)
this  is me demo code, thank you !

**Comment by shikuicao** [comment]
> ke a look in

**Comment by fvarrui** [comment]
> Please ，what about the issue
> […](#)
> ---- Replied Message ---- | From | Francisco Vargas ***@***.***> | | Date | 05/16/2024 16:18 | | To | fvarrui/JavaPackager ***@***.***> | | Cc | shikuicao ***@***.***>, State ***@***.***> | | Subject | Re: [fvarrui/JavaPackager] when I try tro execute the .exe file, it repots "The application requires a java Runtime Environment" (Issue #409) | Please, could you share your demo app to take a look into it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

I'll tell you something ASAP

**Comment by fvarrui** [comment]
Ok, I've seen that your demo project is using JavaFX and is modular (it has `module-info`), so, do this:
1. Add this to JP config:
```xml
              <vmArgs>
                  <vmArg>--module-path=libs</vmArg>
                  <vmArg>--add-modules=javafx.controls,javafx.fxml</vmArg>
              </vmArgs>
```
2. And, since you are building your app for Windows from another platform, you should know that JavaFX uses native libraries, so build it this way:
```bash
mvn package -Djavafx.platform=win
```
And fixed. Easy! 😅 
![image](https://github.com/fvarrui/JavaPackager/assets/4354486/fe91db79-61f4-4c14-b9f0-9639280e8eaa)

**Comment by shikuicao** [comment]
great method!  Thank you so much, If you come to China one day, please contact me and I want to invite you for lunch

**Comment by Nonoas** [comment]
> Are you building your app for Windows from Linux?

I get the error too:
![image](https://github.com/fvarrui/JavaPackager/assets/54799528/a0a7cb37-1ba3-4007-b038-36165a52624d)

plugin: io.github.fvarrui:javapackager:1.7.6-SNAPSHOT
config:
``` grovvy
tasks.register('packageMyApp', PackageTask) {
    dependsOn clean, jar
    // mandatory
    mainClass = mainClassName
    // optional
    modules = ["java.base", "java.management", "java.net.http", "java.scripting", "java.sql", "java.naming",
               "jdk.jsobject", "jdk.unsupported", "jdk.unsupported.desktop", "jdk.xml.dom"]
    bundleJre = true
    generateInstaller = false
    administratorRequired = false
    winConfig { createZipball = true }

}
```
```
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

**Comment by shikuicao** [comment]
> > Are you building your app for Windows from Linux?
> 
> I get the error too: ![image](https://private-user-images.githubusercontent.com/54799528/333767086-a0a7cb37-1ba3-4007-b038-36165a52624d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MDYyODcsIm5iZiI6MTcxNjYwNTk4NywicGF0aCI6Ii81NDc5OTUyOC8zMzM3NjcwODYtYTBhN2NiMzctMWJhMy00MDA3LWIwMzgtMzYxNjVhNTI2MjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDAyNTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMmQ3NzcwMjYzYmI0NTAzMzBkNWVjZWExNzhlYjYwNjM4MjcyMGZkN2UzZDRlNjA3MTk2MDU0MTkyNGQ1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tAli1JakZWANfhf8USVNg3e_WsoAmGAe8o_QJi7aN5E)
> 
> plugin: io.github.fvarrui:javapackager:1.7.6-SNAPSHOT config:
> 
> ```
> tasks.register('packageMyApp', PackageTask) {
>     dependsOn clean, jar
>     // mandatory
>     mainClass = mainClassName
>     // optional
>     modules = ["java.base", "java.management", "java.net.http", "java.scripting", "java.sql", "java.naming",
>                "jdk.jsobject", "jdk.unsupported", "jdk.unsupported.desktop", "jdk.xml.dom"]
>     bundleJre = true
>     generateInstaller = false
>     administratorRequired = false
>     winConfig { createZipball = true }
> 
> }
> ```
> 
> ```
> java version "17" 2021-09-14 LTS
> Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
> Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
> ```
> 
> But, it works when i using `.\jre\bin\java -jar worktools.exe` to run it. so i think maybe the jre is no problem, and i don1t know have to fix

sorry  I  don't know about your problem, I used the pom.xml to config and build an .exe file from Linux. I think you can see the detial config in the demo.zip I uploaded or asking the author for help, he is a very goog man

**Comment by fvarrui** [comment]
> > Are you building your app for Windows from Linux?
> 
> I get the error too: ![image](https://private-user-images.githubusercontent.com/54799528/333767086-a0a7cb37-1ba3-4007-b038-36165a52624d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTIzNzQsIm5iZiI6MTcxOTc1MjA3NCwicGF0aCI6Ii81NDc5OTUyOC8zMzM3NjcwODYtYTBhN2NiMzctMWJhMy00MDA3LWIwMzgtMzYxNjVhNTI2MjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDEyNTQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OGY2MTUzNDk3N2Y1NThhZGFkNTk3MjQ4MjA2OGU3MmYxYWQzYTZiMDc4MmUwNzFhNWYwYTJhM2I3MjEzMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WAupwnqJQNijuMOxa8ne8WARci2B59i7hqt4BhJ7cVk)
> 
> plugin: io.github.fvarrui:javapackager:1.7.6-SNAPSHOT config:
> 
> ```
> tasks.register('packageMyApp', PackageTask) {
>     dependsOn clean, jar
>     // mandatory
>     mainClass = mainClassName
>     // optional
>     modules = ["java.base", "java.management", "java.net.http", "java.scripting", "java.sql", "java.naming",
>                "jdk.jsobject", "jdk.unsupported", "jdk.unsupported.desktop", "jdk.xml.dom"]
>     bundleJre = true
>     generateInstaller = false
>     administratorRequired = false
>     winConfig { createZipball = true }
> 
> }
> ```
> 
> ```
> java version "17" 2021-09-14 LTS
> Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
> Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
> ```
> 
> But, it works when i using `.\jre\bin\java -jar worktools.exe` to run it. so i think maybe the jre is no problem, and i don1t know have to fix

Hi @Nonoas!
Could you provide a sample project?

**Comment by badbadbadbadbad** [comment]
> Ok, I've seen that your demo project is using JavaFX and is modular (it has `module-info`), so, do this:
> 
>     1. Add this to JP config:
> 
> 
> ```
>               <vmArgs>
>                   <vmArg>--module-path=libs</vmArg>
>                   <vmArg>--add-modules=javafx.controls,javafx.fxml</vmArg>
>               </vmArgs>
> ```
> 
>     2. And, since you are building your app for Windows from another platform, you should know that JavaFX uses native libraries, so build it this way:
> 
> 
> ```shell
> mvn package -Djavafx.platform=win
> ```
> 
> And fixed. Easy! 😅 ![image](https://private-user-images.githubusercontent.com/4354486/331315337-fe91db79-61f4-4c14-b9f0-9639280e8eaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDc1NDEsIm5iZiI6MTcyNjUwNzI0MSwicGF0aCI6Ii80MzU0NDg2LzMzMTMxNTMzNy1mZTkxZGI3OS02MWY0LTRjMTQtYjlmMC05NjM5MjgwZThlYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTcyMDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTBhN2RkM2Q0NDRiYzdiMjQxOTIzY2EwMjhlYWUxNzRhZTNiZjQ3Nzc0MDVmNzYxOTI0Nzc4ZjFmNmU5ZTM0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o6luf6J5mUqzSfH_vnN6zRoBXWrNS-x5sUIqtz3qHzM)


Hi there!

I ran into the same issues as the OP of this issue, and resolved it just as you suggested. Out of curiousity: I bundle my own JavaFX program into both a Linux and a Windows version in two different executions, but unfortunately, I have to run your tool once with the default terminal command and once using the Windows-specific flag you posted to get both a usable Linux and a usable Windows version. Is there some way to add the Windows-specific flag into the execution for Windows I have in my pom.xml so I can just run your tool once and get both a functioning Windows version and a Linux version with one JavaPackager use?

**Comment by fvarrui** [comment]
Hi @badbadbadbadbad!
Sorry, not sure. If there was a way to pass `javafx.platform=???` argument to `maven-dependencies-plugin` ...
