### ISSUE TITLE
How can I package for macOS with  the demo ?  https://github.com/fvarrui/JavaPackager/issues/409

### ISSUE THREAD

**Issue by shikuicao** [fvarrui/JavaPackager#410]
https://github.com/fvarrui/JavaPackager/issues/409
Should I use the cmd ? mvn package -Djavafx.platform=mac

**Comment by fvarrui** [comment]
> #409 Should I use the cmd ? mvn package -Djavafx.platform=mac

Yes, and bundle a JRE for macOS
