### ISSUE TITLE
javapackager packaging and security

### ISSUE THREAD

**Issue by 7ye** [fvarrui/JavaPackager#416]
I have a security-related question. After packaging a Java application into an .exe using javapackager, the executable can be opened with compression tools, revealing all the source code and Maven metadata. This allows others to easily copy the code, open it in an IDE like IntelliJ IDEA, and compile it into their own program. How can I address this issue?

**Comment by fvarrui** [comment]
Hi @7ye!

> I have a security-related question. After packaging a Java application into an .exe using javapackager, the executable can be opened with compression tools, revealing all the source code and Maven metadata. This allows others to easily copy the code, open it in an IDE like IntelliJ IDEA, and compile it into their own program. How can I address this issue?

Yes, that's how it works ... and to be accurate, it's not source code, but bytecode (easily decompilable 😞 ).

AFAIK, only thing you can do is to obfuscate your code before packaging. You can build your own JAR, obfuscate it and the pass your obfuscated JAR to JavaPackager using its `runnableJar` property.
