### ISSUE TITLE
Add verification on Project name

### ISSUE THREAD

**Issue by HumanG33k** [fvarrui/JavaPackager#42]
I know it but in file system some characters as :  can be root of issues.
I think a verification of this kind of stuff should be add before anything else.
it s useless to start packaging if we can know by review of var if will have troubles. 

For now all this are not file system safe (exept for some file system : ext3/4 ) 
```
“ < > / \ : * ? |
```

**Comment by fvarrui** [comment]
Now checks if an invalid name is specified at the beginnig of the process. You can try this feature in 1.1.1-SNAPSHOT, which requires a manual installation.

For example, when you use a name like `hola:mundo` which contains `:`:

![image](https://user-images.githubusercontent.com/4354486/87396721-29d31400-c5ab-11ea-95b9-7a276ee5340d.png)

**Comment by fvarrui** [comment]
I think it’s solved, so I’m going to close this issue. Otherwise, we can reopen it
