### ISSUE TITLE
edu.sc.seis.launch4j:launch4j:jar:2.5.2 was not found in https://repo.maven.apache.org/maven2 

### ISSUE THREAD

**Issue by rememberber** [fvarrui/JavaPackager#423]
<img width="684" alt="image" src="https://github.com/user-attachments/assets/30ee82ba-7cc0-41cf-954c-baaca9104671">

**Comment by fvarrui** [comment]
That is because Launch4j Gradle plugin is not on Maven Central, but on Gradle Plugin Portal

https://plugins.gradle.org/m2/edu/sc/seis/launch4j/launch4j/2.5.2/

**Comment by fvarrui** [comment]
Why do you need to know where is `edu.sc.seis.launch4j:launch4j:jar:2.5.2`? Any problem?

**Comment by rememberber** [comment]
Could not found it in maven central when nmvn package before,but I try it today again and it works well
