### ISSUE TITLE
exe icon 不更新   

### ISSUE THREAD

**Issue by 16637142795** [fvarrui/JavaPackager#424]
如图：![image](https://github.com/user-attachments/assets/72cac6b2-d9a2-4795-84e2-d853a986d856)
icon path 没有问题
launch4j 的 icon 也已经更新，为何 app的不刷新
![image](https://github.com/user-attachments/assets/2c5f6b6c-2b75-4428-9e53-621ea61e1a7c)

**Comment by 16637142795** [comment]
这是我的插件配置
<plugin>
                <groupId>io.github.fvarrui</groupId>
                <artifactId>javapackager</artifactId>
                <version>1.7.6</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>package</goal>
                        </goals>
                        <configuration>
                            <mainClass>com.ngs.gui.LauncherApp</mainClass>
                            <bundleJre>true</bundleJre>
                            <winConfig>

                                <generateMsi>false</generateMsi>
                                <generateMsm>false</generateMsm>
                            </winConfig>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by 16637142795** [comment]
这是我的配置![image](https://github.com/user-attachments/assets/842f2b6f-41c4-454a-8aa9-ae2207a369e2)

**Comment by 16637142795** [comment]
![image](https://github.com/user-attachments/assets/45ac0c62-4ea9-41bc-b1df-940629b69165)

**Comment by 16637142795** [comment]
End windows explorer, repackage, done!

**Comment by fvarrui** [comment]
Yes, the executable icon is fine, but Windows Explorer has cached the old icon ... restarting the `explorer.exe` process should solve the problem.
Thanks @16637142795
