### ISSUE TITLE
Building for different OS with optimized JRE

### ISSUE THREAD

**Issue by afdia** [fvarrui/JavaPackager#43]
Hi, thanks for the great plugin!
I have one question though:

I'm currently building on Windows and my goal is to let this plugin analyze my code to get the minimal required modules and build a custom JRE which is bundled as an executable for Windows+Linux+MacOS (I don't need an installer).

I have got it running for Windows by using a JDK11 to build and the following config:
```
<configuration>
	<mainClass>test.Main</mainClass>
	<bundleJre>true</bundleJre>
	<generateInstaller>false</generateInstaller>
</configuration>
```

Now I'm trying to get the outputs for Linux+MacOS, but it doesnt work because the Java version I'm using is on Windows, so my guess was that if I configure something like the following:
```
<configuration>
	<mainClass>test.Main</mainClass>
	<bundleJre>true</bundleJre>
	<generateInstaller>false</generateInstaller>
	<jrePath>PATH_TO_LINUX_JAVA</jrePath>
	<platform>linux</platform>
</configuration>
```
should work, and it seems to create a correct output bundle.
Unfortunately the module analysis seems to be missing (so no optimized JRE is generated) which means the output zip has 200MB (the windows version with the optimized JRE has 40MB)

I have checked https://github.com/ElderResearch/JavaPackager/blob/master/src/main/java/fvarrui/maven/plugin/javapackager/PackageMojo.java and it seems that getRequiredModules() is only called when no JRE is specified which means it doesnt work for another OS right?

Is there a way to build optimized JREs for other OSes than the one the build is running? I haven't used jlink other than through this plugin, but according to https://stackoverflow.com/questions/47593409/create-java-runtime-image-on-one-platform-for-another-using-jlink it should be theoretically be possible to run it for another platform (if I have JDKs for all target OSes available).

I've found #13 which is talking about different platforms, but I guess its not about the module analysis part.

Thanks again for your help!

**Comment by fvarrui** [comment]
Hi @afdia,
thanks to you for trying JavaPackager!

> Hi, thanks for the great plugin!
> I have one question though:
> 
> I'm currently building on Windows and my goal is to let this plugin analyze my code to get the minimal required modules and build a custom JRE which is bundled as an executable for Windows+Linux+MacOS (I don't need an installer).
> 
> I have got it running for Windows by using a JDK11 to build and the following config:
> 
> ```
> <configuration>
> 	<mainClass>test.Main</mainClass>
> 	<bundleJre>true</bundleJre>
> 	<generateInstaller>false</generateInstaller>
> </configuration>
> ```
> 
> Now I'm trying to get the outputs for Linux+MacOS, but it doesnt work because the Java version I'm using is on Windows, so my guess was that if I configure something like the following:
> 
> ```
> <configuration>
> 	<mainClass>test.Main</mainClass>
> 	<bundleJre>true</bundleJre>
> 	<generateInstaller>false</generateInstaller>
> 	<jrePath>PATH_TO_LINUX_JAVA</jrePath>
> 	<platform>linux</platform>
> </configuration>
> ```
> 
> should work, and it seems to create a correct output bundle.
> Unfortunately the module analysis seems to be missing (so no optimized JRE is generated) which means the output zip has 200MB (the windows version with the optimized JRE has 40MB)
> 
> I have checked https://github.com/ElderResearch/JavaPackager/blob/master/src/main/java/fvarrui/maven/plugin/javapackager/PackageMojo.java and it seems that getRequiredModules() is only called when no JRE is specified which means it doesnt work for another OS right?

The `jrePath` option is for older versions of Java, such as 1.8, which don't include the `jink` tool, so it bundles the referenced folder as a Java runtime, without any optimization. It's better that you specify JRE than JDK.

> 
> Is there a way to build optimized JREs for other OSes than the one the build is running? I haven't used jlink other than through this plugin, but according to https://stackoverflow.com/questions/47593409/create-java-runtime-image-on-one-platform-for-another-using-jlink it should be theoretically be possible to run it for another platform (if I have JDKs for all target OSes available).

A possible workaround is having several JREs for different platforms in your SO, and so you can use `jrePath` in [multiple executions of the plugin](https://github.com/fvarrui/JavaPackager/blob/master/docs/plugin-configuration-samples.md#multiple-executions), with each configuration referencing the right JRE.

I didn't know that was possible, but **I'll do some research about it. It would be great to be able to generate JREs optimized for multiple platforms from the same OS.**

> 
> I've found #13 which is talking about different platforms, but I guess its not about the module analysis part.
> 
> Thanks again for your help!

Thanks for your comments!

**Comment by afdia** [comment]
I also planned 3 executions of your plugin (one per OS)

Thanks for the suggestion with the JRE. Of course the JRE alone is much better and now my linux build only has 50MB (Windows with full JRE has 45MB compared to the 40MB). As I'm using Swing and XML, I guess I need most modules anyway.

I still think it would be a nice feature to have the option of a reduced JRE for other OSes (therefore I leave the issue open), but for my current usecase, the few MB overhead are not that bad.

**Comment by fvarrui** [comment]
I'm glad to hear that! 😃 

As I told you, I'll try to generate an optimized JRE for another OS with `jlink`. I'll tell you something about it.

And yes, let's keep this issue opened till we find out if it's possible to do it.

**Comment by fvarrui** [comment]
Hi @afdia,
great news! 

I've managed to generate a customized JRE for GNU/Linux from Windows only by referencing a different JDK when using `jlink` ... and it works fine!

I'm going to include this new feature in v1.1.1. ... so, it'll be possible to specify which JDK to use in order to generate a customized JRE for other OSes.

Thanks!

**Comment by afdia** [comment]
That sounds great, thank you for your work!

**Comment by fvarrui** [comment]
Added `jdkPath` property in **1.2.0-SNAPSHOT**, which allows to bundle a customized JRE for different platforms.

[SNAPSHOT versions have to be installed manually](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin).

Please, try it and tell me if it works fine for you.
Thanks!

**Comment by fvarrui** [comment]
I realized that it's necessary to enhance zipball and tarball generation because of the execution permissions. So when you unzip/untar the generated artifact in GNU/Linux  or Mac OS, the binaries have the proper permissions.

**Comment by afdia** [comment]
Hi, thanks for your effort!
I have just tried it using Win10 and adoptopenjdk11 and the Windows build works.

If I try to build for Linux using adoptopenjdk11 for Linux, it throws an Exception:
`Command execution failed: D:\jdk11_LINUX\bin\jlink --module-path D:\jdk11_LINUX\jmods --add-modules java.base,java.compiler,java.datatransfer,java.desktop,java.logging,java.management,java.naming,java.security.sasl,java.sql,java.xml,java.xml.crypto,jdk.xml.dom --output D:\test\target\test\jre --no-header-files --no-man-pages --strip-debug --compress=2`

I guess it tries to execute jlink of the linux jdk which doesnt work on Windows. So I guess you have to call jlink from the jdk which is used for mvn install (in this case jdk11 for windows) and jmods of the target jdk (in this case linux). This matches the description of https://stackoverflow.com/questions/47593409/create-java-runtime-image-on-one-platform-for-another-using-jlink as far as I see

**Comment by afdia** [comment]
> I realized that it's necessary to enhance zipball and tarball generation because of the execution permissions. So when you unzip/untar the generated artifact in GNU/Linux or Mac OS, the binaries have the proper permissions.

I also had the issue when creating the 50MB linux bundle. It worked, but I had to change the bundled jre/bin/java to be executable before running the program if I remember correctly

**Comment by fvarrui** [comment]
Sorry! It was my fault ... please, try I again. Thanks!

**Comment by fvarrui** [comment]
> > I realized that it's necessary to enhance zipball and tarball generation because of the execution permissions. So when you unzip/untar the generated artifact in GNU/Linux or Mac OS, the binaries have the proper permissions.
> 
> I also had the issue when creating the 50MB linux bundle. It worked, but I had to change the bundled jre/bin/java to be executable before running the program if I remember correctly

Yeah! It's the same. I'll try to fix it asap.

**Comment by afdia** [comment]
> 
> 
> Sorry! It was my fault ... please, try I again. Thanks!

Thanks, now I am able to create the linux bundle using `<platform>linux</platform>` and `<jdkPath>D:\jdk11_LINUX</jdkPath>`. Currently I cannot test if it works because I dont have a Linux OS here, but the dir structure and log output both look good!

Btw: If I don't add `<platform>linux</platform>` it creates a "weird" bundle with a Windows exe but a bundled Linux JVM which doesn't really make sense. I'm not sure if such a combination can be detected (to throw an error or switch platform to linux), but maybe the documentation should mention that if `<jdkPath>` is used, its target OS must match the configured `<platform>` (because other combinations don't make sense), but maybe thats already clear enough.
(it's just something I noticed by accident, therefore I wanted to mention it)

**Comment by fvarrui** [comment]
> Thanks, now I am able to create the linux bundle using `<platform>linux</platform>` and `<jdkPath>D:\jdk11_LINUX</jdkPath>`. Currently I cannot test if it works because I dont have a Linux OS here, but the dir structure and log output both look good!

Please, tell me the results when you try it on Linux! It worked fine for me.

> 
> Btw: If I don't add `<platform>linux</platform>` it creates a "weird" bundle with a Windows exe but a bundled Linux JVM which doesn't really make sense. I'm not sure if such a combination can be detected (to throw an error or switch platform to linux), but maybe the documentation should mention that if `<jdkPath>` is used, its target OS must match the configured `<platform>` (because other combinations don't make sense), but maybe thats already clear enough.
> (it's just something I noticed by accident, therefore I wanted to mention it)

Yes, you are right, but I'm not sure how to verify if you are using a right JDK, and if it's a good idea to ignore `jdkPath` variable when current platform is the same as target platform, because someone maybe wants to use another JDK (different manufacturer or version) for the same platform (I'm not sure if this make sense, but I'm going to leave it by the moment). I'll include a note in documentation about it.

Thanks!!

**Comment by afdia** [comment]
I guess such a detection is either hard or impossible (because you cannot run code of the jdk to check and different jdks may look different such as adoptopenjdk, Amazon Corretto, ...), so I guess a note in the documentation is the best.
I would also not ignore jdkPath if the platform is the same, because it would add another special case and makes the general concept harder to understand.

I tried the reduced build and it works on linux, thanks for the change!

**Comment by fvarrui** [comment]
I’m happy to hear that!

Thanks so much for your support

**Comment by fvarrui** [comment]
> edit: I have checked AdoptOpenJDK for Windows+Linux and Amazon Corretto for Linux and all contain a file named "release" which contains the required information (e.g. OS_NAME="Windows" or OS_NAME="Linux") so in fact it would be possible to check if such a file exists and if it contains an OS_NAME to find the platform of the JVM.
> I'm not sure if its a stable solution (especially because it still may be missing from other distributions) but it may be an option.

I’ll do some research about it ... as you said, it could be an option. Thanks!!!

**Comment by willfurnell** [comment]
Hey @afdia and/or @fvarrui - I'm looking to do the same thing - build Windows, MacOS and Linux binaries all from a Windows box. What does your config look like to be able to do all of these at once - if I do a jdkPath in my config that will only work for one OS at a time?

**Comment by willfurnell** [comment]
Sorry, ignore me, I should've read the docs first! https://github.com/fvarrui/JavaPackager/blob/master/docs/maven/plugin-configuration-samples.md
