### ISSUE TITLE
打包时报错 org.codehaus.plexus.util.cli.CommandLineException

### ISSUE THREAD

**Issue by tianxing-ovo** [fvarrui/JavaPackager#434]
![image](https://github.com/user-attachments/assets/31e22adf-2d91-4a19-8ad2-7db39020d27f)

**Comment by fvarrui** [comment]
Hi @tianxing-ovo!
You have to install Inno Setup innorder to use iscc command

**Comment by tianxing-ovo** [comment]
@fvarrui 好的，谢谢
