### ISSUE TITLE
MacOS installed app via dmg doesn't start (java.lang.module.FindException)

### ISSUE THREAD

**Issue by streamingdv** [fvarrui/JavaPackager#437]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [ x] other

**Short description of the issue/suggestion:**

I'm trying to create a dmg file on macOS but I can't make it work. My Mac config looks like that

```
macConfig {
            appId = 'com.grill.psplay.PXPlay'
            icnsFile = file('src/main/resources/com/grill/psplay/image/PXPlay.icns')
            generateDmg = true
            generatePkg = false
            relocateJar = true
            macStartup = 'UNIVERSAL'

            codesignApp = false
        }
```

It works and the dmg file gets created successfully but my app doesn't start. I tried to investigate the issue and inside the ".app" file in the Contents/Resources/Java is the runnable jar and the libs folder with all dependencies. When I try to run it via

`java -jar PXPlay-1.2.0-runnable.jar`

it works completely fine. But when I try to run the "universalJavaApplicationStub" it just prints out

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.web not found
```

I'm not sure why this happens and if there is something else which I need to do or if this is the reason why my app doesn't start? My gradle is quite complex but here is the link to the full gradle file

https://gist.github.com/streamingdv/499d2b14268711fa625b697eb1dcd4b9

Do you have any inputs of what might be wrong? Unfortunately I'm a bit lost here

**What is the expected behavior?**

The installed app via the dmg file should start

**What is the current behavior?**

The dmg file gets created but the installed app doesn't start

- JavaPackager version: 1.7.5
- OS version: macOS
- JDK version: 21 zulu
- Build tool: 
	- [ ] Maven 
	- [x ] Gradle

**Comment by streamingdv** [comment]
Edit, fixed it the issue was the module-path. I changed it to

`--module-path=$APP_PACKAGE/Contents/Resources/Java/libs`

and it works. I just checked the 'Info.plist' and found out that I had this property and that it doesn't align correctly with the package content structure.

**Comment by fvarrui** [comment]
Great! I'm happy to hear that you found a solution. That was just what I was going to suggest.
