### ISSUE TITLE
ISCC

### ISSUE THREAD

**Issue by Hanzanka** [fvarrui/JavaPackager#44]
'iscc' is not regognzed as internal or external program. Any suggestions to fix this?

**Comment by fvarrui** [comment]
Hi @Hanzanka!
Have you added Inno Setup to PATH environment variable?

**Comment by Hanzanka** [comment]
I only installed inno to my computer. Can you tell me how to do that or do you know any websites that can help me with this? This may be stupid question, but i started to learn coding like 6months ago and now i have made my first javafx app and would like to build it.

**Comment by fvarrui** [comment]
Try this link: https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/. If you still have problems don’t hesitate in asking again

**Comment by Hanzanka** [comment]
Thank you, now i am able to build my project and learned a new thing!

**Comment by fvarrui** [comment]
Great! Thanks for using JavaPackager

**Comment by thamidu** [comment]
Just to let you know. If you are using intellij, just restart the program after setting the PATH. Otherwise the error will still comes up. Happend to me just now. :D

**Comment by fvarrui** [comment]
Thanks! 😄
