### ISSUE TITLE
Packaging JavaFX applications on a Windows host properly

### ISSUE THREAD

**Issue by badbadbadbadbad** [fvarrui/JavaPackager#447]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
I'm working on a JavaFX application with Maven, [tsundoku](https://github.com/badbadbadbadbad/tsundoku). I'm programming on Linux and want to build for Linux and Windows 11. This works; you can see my configuration for JavaPackager at the end of my pom.xml. For Windows, my (already working) goal is to make an .exe that has a JDK bundled along. The JDK's mentioned in the <jdkPath> are just standard, downloaded from Oracle.

I'm trying to take care of an annoyance that was reported in the JavaPackager issues before - namely, Windows Task Manager reports the process as Java(TM) Platform SE binary instead of my project's name. So, as suggested in the other threads on this I found, I try to build for Windows via Winrun4j or why, only to see that both require the building host to be Windows.

So I clone my project to my Windows 11 machine, get Maven running, and try to build. The build process succeeds (besides MSI installer stuff at the end beacuse I don't have iscc / candle installed, but I assume this doesn't matter because I don't want this functionality). However, trying to run the finished .exe doesn't open anything. I can see that tsundoku.exe runs as a background process in Task Manager, and it stays open until I force close it. This happens on my Windows host no matter if I try to build using Launch4j, Winrun4j, or why.

I assume there's some step I forgot to do to be able to build on Windows.

**Steps to reproduce the issue/enhancement:**

1. Clone my project on Windows
2. Change the <jdkPath> variables to point to a JDK (or maybe use your system's Java instead, which I assume should work?)
3. Package. Since this is JavaFX, I have to use the -Djavafx.platform=win flag when building on Linux, I assume this is still required on Windows (I tried with/without and both did not work).
4. Try to run the tsundoku.exe in the resulting snapshot for windows.

**What is the expected behavior?**
Program opens.

**What is the current behavior?**
Program does not open _visually_, but is apparently open as a background process in Task Manager.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.7.6
- OS version: Windows 11, most recent update (build fails). Xubuntu with Ubuntu 22.04.5 LTS (build works).
- JDK version: 21.0.4
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by badbadbadbadbad** [comment]
Well, that's quite embarassing. JavaFX doesn't work with variable fonts and I was still thinking about which fonts to use, so I specifically added the fonts folder to my .gitignore so I wouldn't constantly be updating the relatively large font files with git pushes. Of course, I didn't test to just run via Terminal locally because I forgot I did this in the first place and thought there should be no issues running the project from a fresh clone.

Added the font directory to my local build now, re-packaged, and it's working with winrun4j now, and I'm getting the behaviour I originally wanted - the correct process name in the Task Manager.

What's the correct thing to do with this issue now? Should I just close it, or do you want to delete it since this was clearly just a dumb error?

**Comment by fvarrui** [comment]
Hi @badbadbadbadbad!

> Well, that's quite embarassing. JavaFX doesn't work with variable fonts and I was still thinking about which fonts to use, so I specifically added the fonts folder to my .gitignore so I wouldn't constantly be updating the relatively large font files with git pushes. Of course, I didn't test to just run via Terminal locally because I forgot I did this in the first place and thought there should be no issues running the project from a fresh clone.

Don't worry, it's fine. 😄 

> 
> Added the font directory to my local build now, re-packaged, and it's working with winrun4j now, and I'm getting the behaviour I originally wanted - the correct process name in the Task Manager.

Great!

> 
> What's the correct thing to do with this issue now? Should I just close it, or do you want to delete it since this was clearly just a dumb error?

Maybe this issue could help others with a similar issue, so just closing it would be fine.

Thx for using JP and happy to help!

**Comment by fvarrui** [comment]
Oh! I almost forgot it ... keep in mind that you also can link to external fonts, like [Google Fonts](https://fonts.google.com/), using external URLs, so you don't have to include them into your app, but your app would need Internet access to properly download/show fonts.
