### ISSUE TITLE
JDeps fails on package

### ISSUE THREAD

**Issue by tajetaje** [fvarrui/JavaPackager#45]
[Maven log](https://gist.github.com/4a6128d673f2b0ee986217b4af5774fb)
[pom.xml](https://github.com/fvarrui/JavaPackager/files/5003954/pom.txt)
While the maven output indicates that activation is not found it is clearly in the libs directory as show below
<img width="1800" alt="explorer_E1vcgh6apj" src="https://user-images.githubusercontent.com/29828269/88978602-06d47f80-d28e-11ea-9cc3-81ea8a6a5331.png">
I've been tinkering with this for awhile now and at this point I'm not sure whether the root issue is with docx4j (the source of the dependency) or with JavaPackager, but I haven't seen any similar issues so my bet is it is an issue with JavaPackager. My hunch is that it may have a bit to do with the dependency scopes under docx4j all being set to compile, but I'm not sure.

EDIT: I'm 99.94% sure it doesn't matter but I do have some custom velocity templates to set the app as default.

**Comment by schneidermayer** [comment]
same here

**Comment by fvarrui** [comment]
Hi @tajetaje!
when I try to build your app, I got several compilation errors due to JavaFX libraries are missing:

```
[INFO] 100 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.115 s
[INFO] Finished at: 2020-08-01T11:08:50+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project DebateApp: Compilation failure: Compilation failure:
[ERROR] /C:/Users/fvarrui/GitHub/DebateApp/src/main/java/structures/AppSettings.java:[3,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/fvarrui/GitHub/DebateApp/src/main/java/structures/AppSettings.java:[4,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/fvarrui/GitHub/DebateApp/src/main/java/structures/AppSettings.java:[5,29] package javafx.beans.property does not exist
[ERROR] /C:/Users/fvarrui/GitHub/DebateApp/src/main/java/structures/DebateEvents.java:[3,26] package javafx.collections does not exist
[ERROR] /C:/Users/fvarrui/GitHub/DebateApp/src/main/java/structures/DebateEvents.java:[4,26] package javafx.collections does not exist
[ERROR] /C:/Users/fvarrui/GitHub/DebateApp/src/main/java/structures/AppSettings.java:[24,22] cannot find symbol
...
```

If you run `mvn dependency:tree` you can see all your project's dependencies and JavaFX libraries are in `runtime` scope,

```
C:\Users\fvarrui\GitHub\DebateApp>mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< tajetaje:DebateApp >-------------------------
[INFO] Building DebateApp 2.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ DebateApp ---
[INFO] tajetaje:DebateApp:jar:2.0.0
[INFO] +- org.jfxtras:jmetro:jar:11.6.12:compile
[INFO] |  +- org.openjfx:javafx-controls:jar:win:11.0.2:runtime
[INFO] |  +- org.openjfx:javafx-base:jar:win:11.0.2:runtime
[INFO] |  \- org.openjfx:javafx-graphics:jar:win:11.0.2:runtime
[INFO] +- org.controlsfx:controlsfx:jar:11.0.1:compile
[INFO] |  +- org.openjfx:javafx-base:jar:11.0.2:runtime
[INFO] |  +- org.openjfx:javafx-web:jar:11.0.2:runtime
[INFO] |  |  \- org.openjfx:javafx-web:jar:win:11.0.2:runtime
[INFO] |  +- org.openjfx:javafx-graphics:jar:11.0.2:runtime
[INFO] |  +- org.openjfx:javafx-controls:jar:11.0.2:runtime
[INFO] |  +- org.openjfx:javafx-swing:jar:11.0.2:runtime
[INFO] |  |  \- org.openjfx:javafx-swing:jar:win:11.0.2:runtime
[INFO] |  \- org.openjfx:javafx-media:jar:11.0.2:runtime
[INFO] |     \- org.openjfx:javafx-media:jar:win:11.0.2:runtime
[INFO] +- net.sf.jtidy:jtidy:jar:r938:compile
[INFO] +- org.docx4j:docx4j-JAXB-ReferenceImpl:jar:11.1.8:compile
[INFO] |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.2:compile
[INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.3.2:compile
[INFO] |  |  +- com.sun.istack:istack-commons-runtime:jar:3.0.8:compile
[INFO] |  |  +- org.jvnet.staxex:stax-ex:jar:1.8.1:compile
[INFO] |  |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.16:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.8.0-beta4:compile
[INFO] +- org.docx4j:docx4j-ImportXHTML:jar:8.0.0:compile
[INFO] |  \- org.docx4j:xhtmlrenderer:jar:3.0.0:compile
[INFO] |     \- com.lowagie:itext:jar:2.1.7:compile
[INFO] \- org.docx4j:docx4j-core:jar:11.1.8:compile
[INFO]    +- org.docx4j:docx4j-openxml-objects:jar:11.1.8:compile
[INFO]    +- org.docx4j:docx4j-openxml-objects-pml:jar:11.1.8:compile
[INFO]    +- org.docx4j:docx4j-openxml-objects-sml:jar:11.1.8:compile
[INFO]    +- org.plutext:jaxb-svg11:jar:1.0.2:compile
[INFO]    +- net.engio:mbassador:jar:1.3.2:compile
[INFO]    +- org.slf4j:jcl-over-slf4j:jar:1.7.26:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO]    +- org.apache.commons:commons-compress:jar:1.18:compile
[INFO]    +- commons-codec:commons-codec:jar:1.12:compile
[INFO]    +- commons-io:commons-io:jar:2.6:compile
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.8:compile
[INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO]    |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.3:compile
[INFO]    +- org.docx4j.org.apache:xalan-interpretive:jar:11.0.0:compile
[INFO]    |  \- org.docx4j.org.apache:xalan-serializer:jar:11.0.0:compile
[INFO]    +- net.arnx:wmf2svg:jar:0.9.8:compile
[INFO]    +- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO]    +- org.antlr:stringtemplate:jar:3.2.1:compile
[INFO]    |  \- antlr:antlr:jar:2.7.7:compile
[INFO]    +- org.checkerframework:checker-qual:jar:2.8.1:compile
[INFO]    \- com.google.errorprone:error_prone_annotations:jar:2.3.3:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.299 s
[INFO] Finished at: 2020-08-01T11:08:59+01:00
[INFO] ------------------------------------------------------------------------
```

so they are not included in compilation time and it fails. Thus, I've added these dependencies to your POM:

```xml
         <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>11.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-graphics</artifactId>
            <version>11.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-media</artifactId>
            <version>11.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>11.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>11.0.2</version>
        </dependency>
```
and now dependencies tree looks like this (JavaFX libraries are in `compile` scope):
```
C:\Users\fvarrui\GitHub\DebateApp>mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< tajetaje:DebateApp >-------------------------
[INFO] Building DebateApp 2.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ DebateApp ---
[INFO] tajetaje:DebateApp:jar:2.0.0
[INFO] +- org.openjfx:javafx-controls:jar:11.0.2:compile
[INFO] |  \- org.openjfx:javafx-controls:jar:win:11.0.2:compile
[INFO] +- org.openjfx:javafx-graphics:jar:11.0.2:compile
[INFO] |  +- org.openjfx:javafx-graphics:jar:win:11.0.2:compile
[INFO] |  \- org.openjfx:javafx-base:jar:11.0.2:compile
[INFO] +- org.openjfx:javafx-media:jar:11.0.2:compile
[INFO] |  \- org.openjfx:javafx-media:jar:win:11.0.2:compile
[INFO] +- org.openjfx:javafx-swing:jar:11.0.2:compile
[INFO] |  \- org.openjfx:javafx-swing:jar:win:11.0.2:compile
[INFO] +- org.openjfx:javafx-web:jar:11.0.2:compile
[INFO] |  \- org.openjfx:javafx-web:jar:win:11.0.2:compile
[INFO] +- org.jfxtras:jmetro:jar:11.6.12:compile
[INFO] |  \- org.openjfx:javafx-base:jar:win:11.0.2:compile
[INFO] +- org.controlsfx:controlsfx:jar:11.0.1:compile
[INFO] +- net.sf.jtidy:jtidy:jar:r938:compile
[INFO] +- org.docx4j:docx4j-JAXB-ReferenceImpl:jar:11.1.8:compile
[INFO] |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.2:compile
[INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.3.2:compile
[INFO] |  |  +- com.sun.istack:istack-commons-runtime:jar:3.0.8:compile
[INFO] |  |  +- org.jvnet.staxex:stax-ex:jar:1.8.1:compile
[INFO] |  |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.16:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.8.0-beta4:compile
[INFO] +- org.docx4j:docx4j-ImportXHTML:jar:8.0.0:compile
[INFO] |  \- org.docx4j:xhtmlrenderer:jar:3.0.0:compile
[INFO] |     \- com.lowagie:itext:jar:2.1.7:compile
[INFO] \- org.docx4j:docx4j-core:jar:11.1.8:compile
[INFO]    +- org.docx4j:docx4j-openxml-objects:jar:11.1.8:compile
[INFO]    +- org.docx4j:docx4j-openxml-objects-pml:jar:11.1.8:compile
[INFO]    +- org.docx4j:docx4j-openxml-objects-sml:jar:11.1.8:compile
[INFO]    +- org.plutext:jaxb-svg11:jar:1.0.2:compile
[INFO]    +- net.engio:mbassador:jar:1.3.2:compile
[INFO]    +- org.slf4j:jcl-over-slf4j:jar:1.7.26:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO]    +- org.apache.commons:commons-compress:jar:1.18:compile
[INFO]    +- commons-codec:commons-codec:jar:1.12:compile
[INFO]    +- commons-io:commons-io:jar:2.6:compile
[INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.8:compile
[INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO]    |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO]    +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.3:compile
[INFO]    +- org.docx4j.org.apache:xalan-interpretive:jar:11.0.0:compile
[INFO]    |  \- org.docx4j.org.apache:xalan-serializer:jar:11.0.0:compile
[INFO]    +- net.arnx:wmf2svg:jar:0.9.8:compile
[INFO]    +- org.antlr:antlr-runtime:jar:3.5.2:compile
[INFO]    +- org.antlr:stringtemplate:jar:3.2.1:compile
[INFO]    |  \- antlr:antlr:jar:2.7.7:compile
[INFO]    +- org.checkerframework:checker-qual:jar:2.8.1:compile
[INFO]    \- com.google.errorprone:error_prone_annotations:jar:2.3.3:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.529 s
[INFO] Finished at: 2020-08-01T11:23:56+01:00
[INFO] ------------------------------------------------------------------------
```

After doing this, finally I've managed to build your app, and realized that you did a workaround to this problem disabling JRE customization, so all modules are included (`ALL-MODULE-PATH`) ... good point!! ... but your generated installation artifacts are probably too fat due to a full JRE is being bundled.

```bash
[info]     Bundling JRE ... with C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot
[info]         Getting required modules ...
[info]         Required modules found: [ALL-MODULE-PATH]
[info]
[info]         Creating JRE with next modules included: ALL-MODULE-PATH
[info]         Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot\bin\jlink" --module-path "C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot\jmods" --add-modules ALL-MODULE-PATH --output C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\jre --no-header-files --no-man-pages --strip-debug --compress=2"
[info]         Removing folder [C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\jre\legal]
[info]     JRE bundled in C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\jre!
```

Are JavaFX libraries included with LibericaJDK? I'm using OpenJDK. 

Then, I enabled `customizedJre` property and I've managed to reproduce your issue.

```
[info]     Bundling JRE ... with C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot
[info]         Getting required modules ...
[info]             Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot\bin\jdeps" -q --multi-release 13 --ignore-missing-deps --print-module-deps C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\libs\*.jar C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp-2.0.0-runnable.jar"
[error]             Exception in thread "main" java.lang.module.FindException: Module jakarta.activation not found, required by org.jvnet.staxex
[error]                 at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
[error]                 at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
[error]                 at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
[error]                 at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
[error]                 at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
[error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[error]                 at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```

After researching a bit I found some issues which make me think that module dependencies are not well managed by docx4j or some of its transitive dependencies:

- https://github.com/eclipse-ee4j/jaxb-stax-ex/issues/22
- https://github.com/eclipse-ee4j/jaf/issues/38

and I changed some of your POM dependencies as follows:

```xml

        <dependency>
            <groupId>org.docx4j</groupId>
            <artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
            <version>8.2.1</version>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.activation</groupId>
                    <artifactId>jakarta.activation-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>jakarta.activation</artifactId>
            <version>2.0.0-RC3</version>
        </dependency>

        <dependency>
            <groupId>org.docx4j</groupId>
            <artifactId>docx4j-ImportXHTML</artifactId>
            <version>8.0.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.docx4j</groupId>
            <artifactId>docx4j-core</artifactId>
            <version>8.2.1</version>
        </dependency>
```
I had to downgrade `docx4j-core` and `docx4j-JAXB-ReferenceImpl` from 11.1.8 to 8.2.1, and replace `jakarta.activation:jakarta.aplication-api` (which has to be used only at compile time) with `com.sun.activation:jakarta.activation:2.0.0-RC3` (needed at runtime). 

I'm not sure if downgrading docx4j will be a problem for you. Give it a try, please!

I hope it helps!

Sorry if I've explained the problem with too much details, but I hope it could help others in the future!

**Comment by tajetaje** [comment]
> Hi @tajetaje!
> when I try to build your app, I got several compilation errors due to JavaFX libraries are missing:
> 
> ```
> [INFO] 100 errors
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
>
> ...
>
> ```
> 
> and now dependencies tree looks like this (JavaFX libraries are in `compile` scope):
> 
> ```
> C:\Users\fvarrui\GitHub\DebateApp>mvn dependency:tree
> [INFO] Scanning for projects...
> [INFO]
> [INFO] -------------------------< tajetaje:DebateApp >-------------------------
> [INFO] Building DebateApp 2.0.0
> [INFO] --------------------------------[ jar ]---------------------------------
> [INFO]
> [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ DebateApp ---
> [INFO] tajetaje:DebateApp:jar:2.0.0
> [INFO] +- org.openjfx:javafx-controls:jar:11.0.2:compile
> [INFO] |  \- org.openjfx:javafx-controls:jar:win:11.0.2:compile
> [INFO] +- org.openjfx:javafx-graphics:jar:11.0.2:compile
> [INFO] |  +- org.openjfx:javafx-graphics:jar:win:11.0.2:compile
> [INFO] |  \- org.openjfx:javafx-base:jar:11.0.2:compile
> [INFO] +- org.openjfx:javafx-media:jar:11.0.2:compile
> [INFO] |  \- org.openjfx:javafx-media:jar:win:11.0.2:compile
> [INFO] +- org.openjfx:javafx-swing:jar:11.0.2:compile
> [INFO] |  \- org.openjfx:javafx-swing:jar:win:11.0.2:compile
> [INFO] +- org.openjfx:javafx-web:jar:11.0.2:compile
> [INFO] |  \- org.openjfx:javafx-web:jar:win:11.0.2:compile
> [INFO] +- org.jfxtras:jmetro:jar:11.6.12:compile
> [INFO] |  \- org.openjfx:javafx-base:jar:win:11.0.2:compile
> [INFO] +- org.controlsfx:controlsfx:jar:11.0.1:compile
> [INFO] +- net.sf.jtidy:jtidy:jar:r938:compile
> [INFO] +- org.docx4j:docx4j-JAXB-ReferenceImpl:jar:11.1.8:compile
> [INFO] |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.2:compile
> [INFO] |  |  +- org.glassfish.jaxb:txw2:jar:2.3.2:compile
> [INFO] |  |  +- com.sun.istack:istack-commons-runtime:jar:3.0.8:compile
> [INFO] |  |  +- org.jvnet.staxex:stax-ex:jar:1.8.1:compile
> [INFO] |  |  +- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.16:compile
> [INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
> [INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
> [INFO] |  \- org.slf4j:slf4j-api:jar:1.8.0-beta4:compile
> [INFO] +- org.docx4j:docx4j-ImportXHTML:jar:8.0.0:compile
> [INFO] |  \- org.docx4j:xhtmlrenderer:jar:3.0.0:compile
> [INFO] |     \- com.lowagie:itext:jar:2.1.7:compile
> [INFO] \- org.docx4j:docx4j-core:jar:11.1.8:compile
> [INFO]    +- org.docx4j:docx4j-openxml-objects:jar:11.1.8:compile
> [INFO]    +- org.docx4j:docx4j-openxml-objects-pml:jar:11.1.8:compile
> [INFO]    +- org.docx4j:docx4j-openxml-objects-sml:jar:11.1.8:compile
> [INFO]    +- org.plutext:jaxb-svg11:jar:1.0.2:compile
> [INFO]    +- net.engio:mbassador:jar:1.3.2:compile
> [INFO]    +- org.slf4j:jcl-over-slf4j:jar:1.7.26:compile
> [INFO]    +- org.apache.commons:commons-lang3:jar:3.9:compile
> [INFO]    +- org.apache.commons:commons-compress:jar:1.18:compile
> [INFO]    +- commons-codec:commons-codec:jar:1.12:compile
> [INFO]    +- commons-io:commons-io:jar:2.6:compile
> [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.8:compile
> [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
> [INFO]    +- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
> [INFO]    +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
> [INFO]    |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
> [INFO]    +- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.3:compile
> [INFO]    +- org.docx4j.org.apache:xalan-interpretive:jar:11.0.0:compile
> [INFO]    |  \- org.docx4j.org.apache:xalan-serializer:jar:11.0.0:compile
> [INFO]    +- net.arnx:wmf2svg:jar:0.9.8:compile
> [INFO]    +- org.antlr:antlr-runtime:jar:3.5.2:compile
> [INFO]    +- org.antlr:stringtemplate:jar:3.2.1:compile
> [INFO]    |  \- antlr:antlr:jar:2.7.7:compile
> [INFO]    +- org.checkerframework:checker-qual:jar:2.8.1:compile
> [INFO]    \- com.google.errorprone:error_prone_annotations:jar:2.3.3:compile
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  2.529 s
> [INFO] Finished at: 2020-08-01T11:23:56+01:00
> [INFO] ------------------------------------------------------------------------
> ```
> 
> After doing this, finally I've managed to build your app, and realized that you did a workaround to this problem disabling JRE customization, so all modules are included (`ALL-MODULE-PATH`) ... good point!! ... but your generated installation artifacts are probably too fat due to a full JRE is being bundled.

Yeah, they did end up a bit large, but yeah you guessed right.

> ```shell
> [info]     Bundling JRE ... with C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot
> [info]         Getting required modules ...
> [info]         Required modules found: [ALL-MODULE-PATH]
> [info]
> [info]         Creating JRE with next modules included: ALL-MODULE-PATH
> [info]         Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot\bin\jlink" --module-path "C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot\jmods" --add-modules ALL-MODULE-PATH --output C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\jre --no-header-files --no-man-pages --strip-debug --compress=2"
> [info]         Removing folder [C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\jre\legal]
> [info]     JRE bundled in C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\jre!
> ```
> 
> Are JavaFX libraries included with LibericaJDK? I'm using OpenJDK.

yes Liberica JDK does include JavaFX (that’s why I use it).

> Then, I enabled `customizedJre` property and I've managed to reproduce your issue.
> 
> ```
> [info]     Bundling JRE ... with C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot
> [info]         Getting required modules ...
> [info]             Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-13.0.1.9-hotspot\bin\jdeps" -q --multi-release 13 --ignore-missing-deps --print-module-deps C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp\libs\*.jar C:\Users\fvarrui\GitHub\DebateApp\target\DebateApp-2.0.0-runnable.jar"
> [error]             Exception in thread "main" java.lang.module.FindException: Module jakarta.activation not found, required by org.jvnet.staxex
> [error]                 at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
> [error]                 at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
> [error]                 at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
> [error]                 at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
> [error]                 at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
> [error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
> [error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
> [error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
> [error]                 at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
> [error]                 at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
> ```
> 
> After researching a bit I found some issues which make me think that module dependencies are not well managed by docx4j or some of its transitive dependencies:

Yes that’s the conclusion I came to as well

> * [eclipse-ee4j/jaxb-stax-ex#22](https://github.com/eclipse-ee4j/jaxb-stax-ex/issues/22)
> * [eclipse-ee4j/jaf#38](https://github.com/eclipse-ee4j/jaf/issues/38)
> 
> and I changed some of your POM dependencies as follows:
> 
> ```
>         <dependency>
>             <groupId>org.docx4j</groupId>
>             <artifactId>docx4j-JAXB-ReferenceImpl</artifactId>
>             <version>8.2.1</version>
>             <exclusions>
>                 <exclusion>
>                     <groupId>jakarta.activation</groupId>
>                     <artifactId>jakarta.activation-api</artifactId>
>                 </exclusion>
>             </exclusions>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.sun.activation</groupId>
>             <artifactId>jakarta.activation</artifactId>
>             <version>2.0.0-RC3</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.docx4j</groupId>
>             <artifactId>docx4j-ImportXHTML</artifactId>
>             <version>8.0.0</version>
>         </dependency>
>         
>         <dependency>
>             <groupId>org.docx4j</groupId>
>             <artifactId>docx4j-core</artifactId>
>             <version>8.2.1</version>
>         </dependency>
> ```

Your maven magic is beyond me but much appreciated, I’ll test it later on today.

> I had to downgrade `docx4j-core` and `docx4j-JAXB-ReferenceImpl` from 11.1.8 to 8.2.1, and replace `jakarta.activation:jakarta.aplication-api` (which has to be used only at compile time) with `com.sun.activation:jakarta.activation:2.0.0-RC3` (needed at runtime).
> 
> I'm not sure if downgrading docx4j will be a problem for you. Give it a try, please!
> 
> I hope it helps!
> 
> Sorry if I've explained the problem with too much details, but I hope it could help others in the future!

Not at all, very helpful. I imagine the downgrade will work fine, I think I only upgraded to address another dependency error at the compile stage.

My one question is why does jdeps have such an issue with it when the compiler fetched dependencies just fine?

**Comment by tajetaje** [comment]
Aha! In the words of JavaPackager:

```

[info] Bundles created!
[info] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

```

**Comment by fvarrui** [comment]
> My one question is why does jdeps have such an issue with it when the compiler fetched dependencies just fine?

Compiler only checks direct dependencies, not transitive ones ... I mean, classes invoked directly from your code.

**Comment by fvarrui** [comment]
But the problem was not about the missing dependencies, but the wrong required module names.

**Comment by tajetaje** [comment]
Yeah, makes sense, I filed an [issue](https://github.com/plutext/docx4j-ImportXHTML/issues/63) over at docx4j.
