### ISSUE TITLE
Application installed with MSI does not run

### ISSUE THREAD

**Issue by rhaley-starfish** [fvarrui/JavaPackager#46]
Hello, 

First, FANTASTIC tool. I've been using java off and on for years and deploying with a JRE has always seemed to be black art. I'm working on a project to be deployed at a clients site and this tools is ever so close to fitting my needs very well. I've been able to create an MSI and the installed product seems to have all the application dependencies in the libs folder.

The only problem so far is the runnable jar doesn't seem to run. In my testing the installed application fails to run with no error message. I then attempted to run the "Runnable jar" file from the command line with no success. 

Here is my configuration file so far:

``` xml

<plugin>
	<groupId>io.github.fvarrui</groupId>
	<artifactId>javapackager</artifactId>
	<version>1.1.0</version>		
	<executions>					
		<execution>						
			<phase>package</phase>
			<goals>
				<goal>package</goal>
			</goals>
			<configuration>							
				<name>SmartCableTool</name>
				<mainClass>com.company1.app.SfdqGui</mainClass>
				<bundleJre>true</bundleJre>
				<customizedJre>true</customizedJre>
				<assetsDir></assetsDir>
				<organizationName>Client X</organizationName>
				<copyDependencies>true</copyDependencies>
				<winConfig>
					<headerType>gui</headerType>
					<companyName>${organizationName}</companyName>
					<fileVersion>1.0.0.0</fileVersion>
					<txtFileVersion>${project.version}</txtFileVersion>
					<productVersion>1.0.0.0</productVersion>
					<txtProductVersion>${version}</txtProductVersion>
					<fileDescription>${description}</fileDescription>
					<copyright>${organizationName} 2020</copyright>
					<productName>${name}</productName>
					<internalName>${name}</internalName>
					<originalFilename>${name}.exe</originalFilename>
					<!-- installer generation properties -->
					<disableDirPage>false</disableDirPage>
					<disableProgramGroupPage>false</disableProgramGroupPage>
					<disableFinishedPage>false</disableFinishedPage>
					<createDesktopIconTask>true</createDesktopIconTask>
					<generateSetup>false</generateSetup>
					<generateMsi>true</generateMsi>
				</winConfig>
			</configuration>
		</execution>
	</executions>
</plugin>

```

If I run my "with dependencies" the application executes fine:
``` powershell
PS C:\Users\rhaley.SPE\Sfdq_Java_App_39789\target> .\SmartCableTool-0.1.13-SNAPSHOT-jar-with-dependencies.jar
<application starts>
```
or
``` powershell
PS C:\Users\rhaley.SPE\Sfdq_Java_App_39789\target> java -jar .\SmartCableTool-0.1.13-SNAPSHOT-jar-with-dependencies.jar
<application starts>
```

But the same with the runnable jar:
```
PS C:\Users\rhaley.SPE\starfish\Sfdq_Java_App_39789\target> .\SmartCableTool-0.1.13-SNAPSHOT-runnable.jar
<nothing!>
PS C:\Users\rhaley.SPE\starfish\Sfdq_Java_App_39789\target> java -jar .\SmartCableTool-0.1.13-SNAPSHOT-runnable.jar
Error: Could not find or load main class com.company1.app.SfdqGui
Caused by: java.lang.ClassNotFoundException: com.company1.app.SfdqGui
PS C:\Users\rhaley.SPE\starfish\Sfdq_Java_App_39789\target>
```

I've converted the file SmartCableTool-0.1.13-SNAPSHOT-runnable.jar to a zip file and can confirm the file com\starfishmedical\sfdq\app\SfdqGui.class exists. Any idea what I've missed?

Regards,
Russ

**Comment by fvarrui** [comment]
Hi Russ,
thanks to you for helpìng to improve JavaPackager!

Shouldn't the main class be `com.starfishmedical.sfdq.app.SfdqGui` instead of `com.company1.app.SfdqGui`? (I don't know if you tried to anonymize your message, and your class name is right)

Although the failure is another, you don't have to directly run the executable JAR (`SmartCableTool-0.1.13-SNAPSHOT-runnable.jar`) from the `target` directory:
```bash
C:\Users\rhaley.SPE\starfish\Sfdq_Java_App_39789\target> java -jar .\SmartCableTool-0.1.13-SNAPSHOT-runnable.jar
```
because it will look for dependencies in the `libs` directory, which is not there, but in the generated `target\SmartCableTool` directory. This directory contains your application as it will be installed on the client. Anyway, you can copy or move the runnable JAR to this folder (`target\SmartCableTool`) and run it from there.

If a wrong class name is not the problem, you can change `headerType` property to `console` and it will print any message when running your EXE (`target\SmartCableTool\SmartCableTool.exe`). Maybe this will give us some clue.

**Comment by RussellHaley** [comment]
> Hi Russ,
> thanks to you for helpìng to improve JavaPackager!
> 
> Shouldn't the main class be `com.starfishmedical.sfdq.app.SfdqGui` instead of `com.company1.app.SfdqGui`? (I don't know if you tried to anonymize your message, and your class name is right)
Ha ha! You are correct on both accounts. The class name was incorrect in the pom file and I tried and failed completely to anonymize my message. I knew I was going to stuff that up.
> 
> Although the failure is another, you don't have to directly run the executable JAR (`SmartCableTool-0.1.13-SNAPSHOT-runnable.jar`) from the `target` directory:
> 
> ```shell
> C:\Users\rhaley.SPE\starfish\Sfdq_Java_App_39789\target> java -jar .\SmartCableTool-0.1.13-SNAPSHOT-runnable.jar
> ```
> 
> because it will look for dependencies in the `libs` directory, which is not there, but in the generated `target\SmartCableTool` directory. This directory contains your application as it will be installed on the client. Anyway, you can copy or move the runnable JAR to this folder (`target\SmartCableTool`) and run it from there.
> 
> If a wrong class name is not the problem, you can change `headerType` property to `console` and it will print any message when running your EXE (`target\SmartCableTool\SmartCableTool.exe`). Maybe this will give us some clue.

That's great advice. Perhaps that tidbit could be added to the headerType configuration description in docs/windows-specific-properties.md?

Thank you for your time, your patience in solving my self-inflicted errors is greatly appreciated.

**Comment by rhaley-starfish** [comment]
> Hi Russ,
> thanks to you for helpìng to improve JavaPackager!
> 
> Shouldn't the main class be `com.starfishmedical.sfdq.app.SfdqGui` instead of `com.company1.app.SfdqGui`? (I don't know if you tried to anonymize your message, and your class name is right)

Ha ha! You are correct on both accounts. The class name was incorrect in the pom file and I tried and failed completely to anonymize my message. I knew I was going to stuff that up.

 
> Although the failure is another, you don't have to directly run the executable JAR (`SmartCableTool-0.1.13-SNAPSHOT-runnable.jar`) from the `target` directory:
> 
> ```shell
> C:\Users\rhaley.SPE\starfish\Sfdq_Java_App_39789\target> java -jar .\SmartCableTool-0.1.13-SNAPSHOT-runnable.jar
> ```
> 
> because it will look for dependencies in the `libs` directory, which is not there, but in the generated `target\SmartCableTool` directory. This directory contains your application as it will be installed on the client. Anyway, you can copy or move the runnable JAR to this folder (`target\SmartCableTool`) and run it from there.
> 
> If a wrong class name is not the problem, you can change `headerType` property to `console` and it will print any message when running your EXE (`target\SmartCableTool\SmartCableTool.exe`). Maybe this will give us some clue.

That's great advice. Perhaps that tidbit could be added to the headerType configuration description in docs/windows-specific-properties.md?

Thank you for your time, your patience in solving my self-inflicted errors is greatly appreciated.
