### ISSUE TITLE
Module java.activation not found, required by java.xml.soap

### ISSUE THREAD

**Issue by fvarrui** [fvarrui/JavaPackager#55]
Hi, 
I am taking over the project instead of  HumanG33k.
When i try, i have an exception : Module java.activation not found, required by java.xml.soap

_Originally posted by @Trylam in https://github.com/fvarrui/JavaPackager/issues/41#issuecomment-700042337_

**Comment by fvarrui** [comment]
Hi @Trylam!
This problem is due to `jdeps` can't determine needed modules from dependencies. A work around could be to include all modules, but this embeds a full JRE in your app:

```xml
<customizedJre>false</customizedJre>
```

or maybe you can try to force the inclusion of this module:

```xml
<additionalModules>
    <additionalModule>java.activation</additionalModules>
</additionalModules>
```

Could you share all your project dependencies and full Maven output? 

Thanks!

**Comment by fvarrui** [comment]
Hi @Trylam! No news, good news? 😃

**Comment by Basler182** [comment]
Hi @fvarrui , 
Unfortunately I have a problem, which is probably related to this one!

`Module java.activation not found, required by org.jvnet.staxex `

Dependency Tree:
```
[INFO] +- org.hibernate:hibernate-core:jar:5.4.22.Final:compile
[INFO] |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
[INFO] |  +- javax.persistence:javax.persistence-api:jar:2.2:compile
[INFO] |  +- org.javassist:javassist:jar:3.24.0-GA:compile
[INFO] |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
[INFO] |  +- org.jboss:jandex:jar:2.1.3.Final:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  +- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO] |  +- org.dom4j:dom4j:jar:2.1.3:compile
[INFO] |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.0.Final:compile
[INFO] |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO] |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
[INFO] |     +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
[INFO] |     +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
[INFO] |     +- org.jvnet.staxex:stax-ex:jar:1.8:compile
[INFO] |     \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
```

So good thing first: Your workaround without the customized JRE runs totally fine, but the force inclusion doesn't work.  As you can imagine, it would be great for me not to miss out on the great advantages of custom jre. Anyhow thanks a lot for your great project!

**Comment by fvarrui** [comment]
Hi @Basler182!

I've managed to reproduce your issue adding the next dependency:
```xml
<dependency>
    <groupId>org.jvnet.staxex</groupId>
    <artifactId>stax-ex</artifactId>
    <version>1.8</version>
</dependency>
```
I think that your problem is related to this issue: https://github.com/eclipse-ee4j/jaxb-ri/issues/1236. It seems that `javax.activation:javax.activation-api:jar:1.2.0` is not yet modularized, so when `jdeps` analyze required modules can't find `java.activation`.

**Comment by Basler182** [comment]
Unlucky its the dependency of a dependency. I already tried to increment Hibernate version, but it still refers to not modularized version of java.activation. I guess I am not able to fix it so,, since force adding it didn't work as well.  Thank you, for your quick help and reply @fvarrui !

**Comment by fvarrui** [comment]
Please @Trylam, try [v1.4.0](https://search.maven.org/artifact/io.github.fvarrui/javapackager/1.4.0/jar) and if the problem persists we'll reopen this issue.
Thanks!
