### ISSUE TITLE
Gradle Task timing out in macOs

### ISSUE THREAD

**Issue by SDAChess** [fvarrui/JavaPackager#57]
The gradle packageMyApp task seems to time out on macOS. I only used it with Github actions but Linux and Windows are working fine. I'm investigating the bug at the moment and if I find a solution I'll link you a pull request 

![image](https://user-images.githubusercontent.com/44714756/94620456-f69d4880-02ae-11eb-89c6-ccb95b6cfc9c.png)

**Comment by fvarrui** [comment]
Hi Simon!
Please, I'd need more info: your environment (OS, JDK), your `build.gradle` and full `./gradlew packageMyTask` output.

JavaPackager works fine for me on macOS 10.12 ... so I need to reproduce your issue in order to solve it.

Thanks for your help!

**Comment by SDAChess** [comment]
The specifications of the os are the [folowing](https://github.com/actions/virtual-environments/blob/macos-10.15/20200918.1/images/macos/macos-10.15-Readme.md). Using java JDK 11.0.2.

See the attached file for the complete gradle log.

Thank you very much!
[gradle.log](https://github.com/fvarrui/JavaPackager/files/5303916/gradle.log)

**Comment by fvarrui** [comment]
It seems that you're doing things in the right way ... also, I've seen that the artifacts are being generated, despite this issue.

I'm using Gradle 6.3 ... I'm not sure if the problem is related to this.

I'll keep investigating!

**Comment by SDAChess** [comment]
I can try to update to version 6.3 of Gradle on my end see if it fixes anything... I'll keep you updated.

**Comment by SDAChess** [comment]
Update : Running Gradle 6.3 doesn't seems to have fixed the issue. I'm waiting on a friend to receive his mac to try out locally instead of using Github pipelines. Will report after having done this

**Comment by fvarrui** [comment]
Hi @SDAChess!
Have you been able to try it or find out something else about it?

**Comment by fvarrui** [comment]
Hi @SDAChess!
Try v1.4.0 and if the problem persists we'll reopen this issue.

[Here](https://github.com/keastrid/astroimagej/blob/master/.github/workflows/macBuild.yml) you can find an example of using GitHub Actions to generate installation artifacts for Mac OS, which is working fine. I hope it helps!
