### ISSUE TITLE
Failed to execute goal io.github.fvarrui:javapackager:1.1.0:package (default-cli) on project ExeBuilder: The parameters 'mainClass' for goal io.github.fvarrui:javapackager:1.1.0:package are missing or invalid

### ISSUE THREAD

**Issue by yan1989** [fvarrui/JavaPackager#60]
Failed to execute goal io.github.fvarrui:javapackager:1.1.0:package (default-cli) on project ExeBuilder: The parameters 'mainClass' for goal io.github.fvarrui:javapackager:1.1.0:package are missing or invalid

**Comment by fvarrui** [comment]
Hi @yan1989!
Please, can you share your `pom.xml` and full Maven output?
Thanks

**Comment by fvarrui** [comment]
Try v1.4.0 and if the problem persist, we'll reopen this issue.
