### ISSUE TITLE
NullPointerException is thrown when bundleJre=true and copyDependencies=false

### ISSUE THREAD

**Issue by kascoder** [fvarrui/JavaPackager#62]

**Comment by fvarrui** [comment]
Hi @kascoder!
I've managed to reproduce your issue.

I think it's fixed in **v.1.3.1-SNAPSHOT**, which has [to be installed manually to your repo](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin), till I release it to Maven Central.

Please, could you test it?

Thanks!

**Comment by kascoder** [comment]
Hi @fvarrui 
Yes, the issue was resolved after your updates
Thank you!

**Comment by fvarrui** [comment]
Great!! I’ll release v1.3.1 asap
