### ISSUE TITLE
Option to read launch parameters from a separate file.

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#66]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
A separate file in the application resources from which vmArgs will be read at launch to facilitate users changing them via the program itself.

**What is the current behavior?**
Currently, launch args appear to be embedded within the generated .exe and Info.plist files. Info.plist is modifiable, except when installed via the generated .pkg (permissions issue). 

I am not familiar enough with Linux to determine if this is needed there.

**What is the motivation / use case for changing the behavior?**
For programs that wish to allow users to modify the amount of memory used, having a separate file (eg ${name}.cfg) from which the arguments are read is useful, as it allows the program to edit arguments, and lets them place the functionality behind a friendly GUI for users.

**Please tell us about your environment:**

- JavaPackager version: 1.4.1-SNAPSHOT
- OS version: Windows
- JDK version: 14
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by keastrid** [comment]
[Launch4j has this functionality for Windows, but prevents overrides](http://launch4j.sourceforge.net/docs.html#Additional_jvm_options).

**Comment by fvarrui** [comment]
Hi @keastrid!

Right now JavaPackager generates a BASH script to start the application in GNU/Linux with the VM arguments hardcoded into it ... also, this script has the runnable Jar file concatenated ... so, it's not an editable file. But I think it's easy to make that this script reads the VM args from an external file (e.g. ${name}.cfg).

I'd like to find a similar solution for all platforms (same external file), but this will be a little more complicated.

**Comment by keastrid** [comment]
The same file would be ideal, not sure how to handle it though.

**Comment by keastrid** [comment]
Thinking about it more, Mac's applicationStub reads in from Info.plist, and as it's just a bash script it could be redirected to another file, and I imagine a similar situation on Linux.
Since launch4j already allows for a separate file, it might not be too far off from a solution.

**Comment by fvarrui** [comment]
I would't like to touch `universalJavaApplicationStub` as it's an imported file from [another project](https://github.com/tofi86/universalJavaApplicationStub). But I think that we can apply changes to it with a patch file (in order to automate in case this file is updated). And another question: I'm not sure if a user can edit the `Info.plist` file, since if the application is signed, I think that any change to this file prevents the system from running this app.

However, in GNU/Linux we have full control over the startup script. I think we can use the same file as on Windows.

**Comment by keastrid** [comment]
Patching the stub works. I wasn't suggesting modifying `Info.plist`, but patching it to look for VMArgs in another file. I believe this is the right line (though probably wrong), https://github.com/tofi86/universalJavaApplicationStub/blob/ab5c2251e489cf200ade9d3ed465fb4f1ca83556/src/universalJavaApplicationStub#L209

**Comment by fvarrui** [comment]
Hi @keastrid!

I think it's done. You can try it with the same file as in Windows ... now VM args are read from `${name}.l4j.ini` file on GNU/Linux and MacOS. It has to be stored in `Resources` folder on MacOS and next to binary on GNU/Linux. The options read from the file are added to those in `Info.plist`.

Please, give it a test!

**Comment by keastrid** [comment]
What is `binary` on Linux? I don't see it in the tarball.
Looks like it works on Windows.
While this might not be the best place to ask, do you know how to give write permission for `${name}.l4j.ini` on MacOS? I can't seem to find anything on how - is this a permission that needs to be set in `Info.plist` or during the generation?

Thank you for all your help! (And sorry for all the issues)

**Comment by fvarrui** [comment]
> What is `binary` on Linux? I don't see it in the tarball.

Sorry, I mean the executable.

> Looks like it works on Windows.
> While this might not be the best place to ask, do you know how to give write permission for `${name}.l4j.ini` on MacOS? I can't seem to find anything on how - is this a permission that needs to be set in `Info.plist` or during the generation?

As it's an additional resource, it has to be created by developers, who has to set writing permissions to that file. To set writing permissions on MacOS: `chmod +w ${name}.l4j.ini`.

If packaging an app for Linux or MacOS from Windows, permissions has to be set when zipping the app, because this kind of permissions doesn't exist on Windows.

> 
> Thank you for all your help! (And sorry for all the issues)

Thanks to you for helping to improve JavaPackager!!!

**Comment by keastrid** [comment]
> As it's an additional resource, it has to be created by developers, who has to set writing permissions to that file. To set writing permissions on MacOS: `chmod +w ${name}.l4j.ini`.

Having tried that, I think somehow when installing via the .pkg (to Applications) the permission is lost. When using just the .app form, even though Finder shows it as not having write perms, it can still be modified by the program.

**Comment by keastrid** [comment]
Turns out .dmg installs don't have the permissions problem, so closing this as it is now implemented.
Thank you for all the help!
