### ISSUE TITLE
Setup always asks for administrator privileges

### ISSUE THREAD

**Issue by Manerr** [fvarrui/JavaPackager#75]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
The installation will always be launched with the request for administrator privileges.

**Steps to reproduce the issue/enhancement:**

1. [First Step]
Set administratorRequired to false
2. [Second Step]
Build the setup file
3. [Third Step]
Run the setup file

**What is the expected behavior?**
The installation popup opens with the choice of language, without the request for administrator's privileges.

**What is the current behavior?**
The popup request for administrator privileges appears.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**  
![Screenshot](https://i.imgur.com/OkdOMtX.png)

**Please tell us about your environment:**
- JavaPackager version: 1.4.1
- OS version: Windows 10 1909
- JDK version: jdk1.8.0_271
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)  

I copy the [iss.vtl](https://github.com/fvarrui/JavaPackager/blob/master/src/main/resources/windows/iss.vtl) file and I change:
`PrivilegesRequired=admin` to `PrivilegesRequired=lowest` and that solve the problem.  
Adding `PrivilegesRequiredOverridesAllowed=commandline dialog` also solves the problem because the user has the choice of the installation privileges with a popup window. It might be interesting to add support for it.
> see [PrivilegesRequired](https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequired) and [PrivilegesRequiredOverridesAllowed](https://jrsoftware.org/ishelp/index.php?topic=setup_privilegesrequiredoverridesallowed)  

We also need to change installation folder, start menu shortcut folder and desktop folder:
`DefaultDirName={commonpf}\{#MyAppFolder}` 
Change `commonpf` to `autopf`  
The installation folder will automatically change depending on permissions. (To not try to write in C:\Program Files\).

We also need to change the location of the shortcut in the Start Menu: 
`Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"`
Change `commonprograms` to `autoprograms`

And for the desktop: 
`Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon`
Change `commondesktop` to `autodesktop`

These three changes use the `auto_` constants which change according to the setup privileges.
![Screenshot](https://i.imgur.com/PaATb8j.jpg)
> see [consts](https://jrsoftware.org/ishelp/index.php?topic=consts)

**Comment by Manerr** [comment]
I forgot, we also need to change `DefaultDirName={commonpf}\{#MyAppFolder}` to `DefaultDirName={autopf}\{#MyAppFolder}`  
The installation folder will automatically change depending on permissions. (To not try to write in C:\Program Files\).

We also need to change the location of the shortcut in the Start Menu:
`Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"` to `Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"`

And for the desktop:
`Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon` to `Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon`

![Screenshot](https://i.imgur.com/PaATb8j.jpg)
see [consts](https://jrsoftware.org/ishelp/index.php?topic=consts)

**Comment by fvarrui** [comment]
Hi @Manerr!

Thanks for your suggestions. I think that it's more an enhancement than a bug, and I like the idea of using `auto` constants instead of  `common`.

To address this issue before we find a suitable solution you can use a customized `iss.vtl` template. I'm not sure if this is what you did, but you only have to create your own template in `${project.basedir}/assets/windows/iss.vtl`, including your changes, so JavaPackager will use this instead of the built-in template, and you don't have to change the current plugin implementation. You can also add your own variables using the `extra` property.

I wouldn't like to change the default behaviour of JavaPackager, but what do you think if we add a new property (`winConfig.setupMode`)? This property could have 3 possible values: 
- **installForAllUsers** (default value): 
```ini
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=commandline
```
- **installForCurrentUser**
```ini
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
```
- **askTheUser**
```ini
PrivilegesRequiredOverridesAllowed=commandline dialog
```

Thanks again!

**Comment by Manerr** [comment]
I hesitated between bug and new feature, the administratorRequired option made me doubt. I used the template and it works perfectly.
Otherwise the idea of adding a new property seems like a good idea and will simplify the use.
Thank you for your project!

**Comment by fvarrui** [comment]
`administratorRequired` property only affects to the app's executable. I'll implement this change asap.

Thanks for helping to improve JavaPackager!

**Comment by fvarrui** [comment]
I've just made this change ... You can try v1.4.2-SNAPSHOT!

If it works fine for you, I'll release it on Maven Central as v1.4.2.

**Comment by Manerr** [comment]
It's perfect, it works for me
