### ISSUE TITLE
launch4j-maven-plugin jre node add minVersion config

### ISSUE THREAD

**Issue by JonathanHsia** [fvarrui/JavaPackager#77]
- [launch4j-maven-plugin jre node add **minVersion** config ] feature request

**Short description of the issue/suggestion:**
after add this config **minVersion** like this 
![image](https://user-images.githubusercontent.com/10798612/99607765-6aee9f80-2a47-11eb-903b-d5f410d7aad3.png)
build window exe file and config **bundleJre** **true** or **false**,on you desktop system have  jre environment with jre version greater than or equal to config jre verion and you remove local jrePath,it also can run and used system jre environment.
so add this config get more compatibility

**Comment by fvarrui** [comment]
Hi @JonathanHsia!
I've just added this new feature in v1.4.2-SNAPSHOT. Could you try it, please?

**Comment by JonathanHsia** [comment]
> Hi @JonathanHsia!
> I've just added this new feature in v1.4.2-SNAPSHOT. Could you try it, please?

ok i`d try,tell you result later

**Comment by JonathanHsia** [comment]
if i config 
```xml
<bundleJre>false</bundleJre>
<jreMinVersion>1.8.0</jreMinVersion>
```
on my windows machine,the build exe file will not run, 
i`m not config JAVA_HOME on System Envirment Variable.

i edit source code to
```java
       if (!StringUtils.isBlank(jreMinVersion)) {
            jreElements.add(element("minVersion", jreMinVersion));
        }
        if (bundleJre) {
            jreElements.add(element("path", jreDirectoryName));
        } else {
            jreElements.add(element("path", "%JAVA_HOME%"));
        }
```
it run succss

so i think no matter for bundleJre true of false,on windows platform jreMinVersion should not empty

**Comment by fvarrui** [comment]
Yes! You are right ... I misunderstand Launch4j documentation
![image](https://user-images.githubusercontent.com/4354486/99992878-d4a3dc00-2dae-11eb-80cb-e885428aa9a8.png)
I'll apply your suggested change.

**Comment by fvarrui** [comment]
Change applied!

**Comment by fvarrui** [comment]
v1.4.2 released to Maven Central.
