### ISSUE TITLE
Support for specifying a different Module Dependence Analysis Option for building customized JRE

### ISSUE THREAD

**Issue by mlopezFC** [fvarrui/JavaPackager#8]
It should be possible to specify another [Module Dependence Analysis Option](https://docs.oracle.com/en/java/javase/13/docs/specs/man/jdeps.html#module-dependence-analysis-options), different from `--list-deps`

**Comment by fvarrui** [comment]
[v0.8.5](https://github.com/fvarrui/JavaPackager/releases/tag/v0.8.5) has been released with your fixes.
