### ISSUE TITLE
Package success but nothing happens when running executable

### ISSUE THREAD

**Issue by yiding-he** [fvarrui/JavaPackager#81]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Package success, but nothing happens when running executable.

**Steps to reproduce the issue/enhancement:**
1. extract sample project [jdk15-javapackager-test.zip](https://github.com/fvarrui/JavaPackager/files/5670859/jdk15-javapackager-test.zip);
2. open cmd window and go to project directory;
2. run `mvn package` to build executable with javapackage plugin;
3. run `target\example\example.exe` and nothing shows.

**What is the expected behavior?**
Print string "Hello, javapackager!"

**What is the current behavior?**
No output.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
![cmd_dkzklFdnVH](https://user-images.githubusercontent.com/900606/101733222-776f9080-3af9-11eb-9bb1-fb7d3e5a38cf.png)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- JavaPackager version: 1.4.2
- OS version: Windows 10 20H2
- JDK version: 15
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @yiding-he!
On windows, if you want your app to print something to the console, you must set `winConfig.headerType = console`.
