### ISSUE TITLE
macOS useSystemMenuBarProperty().set(true) is overridden by package phase when opening .app

### ISSUE THREAD

**Issue by danielemaddaluno** [fvarrui/JavaPackager#85]
I'm submitting a…

- [x] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
First of all, thank you so much for this project! I was looking for something like this for so long.
So, the problem is that on macOS generally, to have a better "look and feel" and something to which mac users are most used to, I use inside the initialization code of my controllers something like that:

```
@FXML
protected void initialize() {
   if (OSValidator.isMac()) {
      menuBar.useSystemMenuBarProperty().set(true);
      // Used to remove menubar space
      AnchorPane.setTopAnchor(anchorPane, 0.0);
      menuBar.setVisible(false);
   }
}
```
On windows I mantain the javafx menu, so it's not a problem.
On mac I would like to put my menu as a system menu (as shown in the code above).

**Steps to reproduce the issue/enhancement:**
To reproduce the problem I have created a simple repository [justmenu](https://github.com/danielemaddaluno/justmenu).
You can simply import it and run the `mvn package` on it.

**What is the expected behavior?**
The expected behaviour should be something similar to this (which is what I get when I run the project from inside the eclipse IDE):

![JustMenuOnMacExpected (the one that I get running from eclipse)](https://user-images.githubusercontent.com/1886810/104436199-972d2500-558d-11eb-9b15-03cd77d23d02.png)

As it can be seen the menu is moved on the menubar.

**What is the current behavior?**
The current behaviour, after running a `package` with maven, is this one.
![JustMenuOnMacAfterRunningAppGeneratedWithPackage](https://user-images.githubusercontent.com/1886810/104436359-cba0e100-558d-11eb-93a6-1f649b4e0b54.png)
As it can be seen the menu collapse in just one item, even if by code i have specified the `menuBar.useSystemMenuBarProperty().set(true)`.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
Yes, look at expected vs current behaviour images above (on these images focus on the mac system menu bar on top).

**What is the motivation / use case for changing the behavior?**
I would appreciate to mantain the mac look and feel interaction with the app menu.

**Please tell us about your environment:**

- JavaPackager version: 1.4.2
- OS version: macOS Big Sur 11.0.1
- JDK version: Zulu: 15.28.51, 15.0.1+9, JDK FX
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
On windows all seems ok because i simply use the menu from javafx as it comes like this:
![JustMenuOnWin](https://user-images.githubusercontent.com/1886810/104436748-40741b00-558e-11eb-9c55-90eb4baadb57.png)

I'm not really inside of plugin programming. But up to java 1.8 I used to use this plugin [com.zenjava.javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) and with this, after the creation of the '.app' bundle, I didn't had this problem:
- the "java" menuitem was replaced similarly to "Javapackager" with "AppName" title
- and the other menu items were correctly put on the systembar

Maybe this can help to find an easy path to follow... ([link1](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/976875eca2572118adbf620261de16c1709c4175/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L499), [link2](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/976875eca2572118adbf620261de16c1709c4175/src/main/java/com/zenjava/javafx/maven/plugin/NativeMojo.java#L597)) but as I told, I don't really know how to help, I'm just trying to add some context and I hope it will help you better understand how to solve the issue.
Thank you.

**Comment by fvarrui** [comment]
Hi @danielemaddaluno!

Thanks for your words!

> First of all, thank you so much for this project! I was looking for something like this for so long.

I've been looking into your problem and it's related with an old version of `universalJavaApplicationStub` (<v3.1.0), the script used to run Java apps on MacOS. It has been upgraded in JavaPackager v1.4.3-SNAPSHOT ... you have to install it [manually](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin) in your local repo.

Please, test it and tell me if it works fine for you!

**Comment by danielemaddaluno** [comment]
Just tested with JavaPackager v1.4.3-SNAPSHOT!
It works like a charm! 😃
Thank you again!

**Comment by fvarrui** [comment]
Great! 😃 

I'll release v1.4.3-SNAPSHOT to Maven Central as v1.5.0, due to it'll include a new feature requested in other issue, so I'll increase the minor version number.

Thanks for your contribution!

**Comment by fvarrui** [comment]
v1.5.0 released to Maven Central
