### ISSUE TITLE
Getting "Service exited with abnormal code: 1" - on Mac

### ISSUE THREAD

**Issue by catalean** [fvarrui/JavaPackager#86]
Hi there,

That's all I can see in the System Log on my Mac.

com.apple.xpc.launchd[1] (<my main class>.24316[2450]): Service exited with abnormal code: 1

I was running this before without having Xcode installed, from what I can tell the only thing I changed in the meantime was having Xcode installed.  Now I tried with both the version 0.9.7 i still was using and also with the newest 1.5.0 - with both I get the same result...

The question is how I can find out what exactly that exit code means...any idea?

many thx,
Cata

**Comment by fvarrui** [comment]
Hi @catalean!
Could you give me more information? When does this happen? While running the generated application or during the build process? Can you share your logs? Are you using Maven or Gradle? Which JDK version?

I have no idea but if you provide me with more information it'd be very helpful.

Thanks!

**Comment by catalean** [comment]
Hi,

Java 8 I'm using with Maven, and the build process works just fine, I get now both a .dmg and a .pkg. After installing the app using the .dmg, I start the app...and the app doesn't start. I checked the system log, and that message i posted is the only message I see regarding the failed startup.

What log do you need, the build log?

thx

**Comment by fvarrui** [comment]
> Java 8 I'm using with Maven, and the build process works just fine, I get now both a .dmg and a .pkg. After installing the app using the .dmg, I start the app...and the app doesn't start. I checked the system log, and that message i posted is the only message I see regarding the failed startup.

Try to run the app's startup script (`universalJavaApplicationStub`) directly from a terminal... this could throws some light.

> What log do you need, the build log?

Yes, please. And the plugin configuration, if it's possible.

Thanks!!

**Comment by catalean** [comment]
Thx for the hint, running the app's startup script told me now that my main class was not found. My bad, was moving the main class to another package, and missed updating the plugin config :-)

Thx for your help.

**Comment by fvarrui** [comment]
Great!! Thanks to you for using JavaPackager
