### ISSUE TITLE
bundleJre does not check if the JRE path for Mac distributions already contains "Contents/Home" before appending it

### ISSUE THREAD

**Issue by keastrid** [fvarrui/JavaPackager#88]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
https://github.com/fvarrui/JavaPackager/blob/13dca5db54dd166a2f875268c6b08df72116e7d8/src/main/java/io/github/fvarrui/javapackager/packagers/Packager.java#L232-L234

This causes issues for systems that wish to dynamically generate the Gradle tasks for building multiple distributions by finding the folder of the jre/jdk that holds the `bin` folder (could be `release` since packager looks for that). Example: https://github.com/keastrid/astroimagej/blob/51e4155dbf94aaa45196cb09b47cf9ede0de4dd3/build.gradle#L278-L343

The exception also does not specify the `specificJreFolder` that evaluates, and only prints the supplied `jrePath`, which made this more difficult to debug. 

**Steps to reproduce the issue/enhancement:**

1. Give a jrePath for a mac distribution to path to the folder containing `bin`
2. Run that task

**What is the expected behavior?**
`Contents/Home` is checked for at the tail of the `jrePath` first before appending it again.

**What is the current behavior?**
It does not check that the path is valid, it simply assumes it isn't and attempts to fix it.

**What is the motivation / use case for changing the behavior?**
Dynamically creating distribution build tasks.

**Please tell us about your environment:**

- JavaPackager version:1.5.0
- OS version: Windows
- JDK version: 15
- Build tool: 
	- [ ] Maven 
	- [x] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @keastrid!
Do you think that the next change fixes your issue?

https://github.com/fvarrui/JavaPackager/blob/a9e048abe5a93a50464637e10749aea40f11d75f/src/main/java/io/github/fvarrui/javapackager/packagers/Packager.java#L231-L234

Now it only fixes the specified `jrePath` if `release` file doesn't exist, and returns the right jrePath in the throwed exception.

https://github.com/fvarrui/JavaPackager/blob/a9e048abe5a93a50464637e10749aea40f11d75f/src/main/java/io/github/fvarrui/javapackager/packagers/Packager.java#L236-L239

**Comment by fvarrui** [comment]
If so ... you can try v1.5.1-SNAPSHOT.
Thanks!

**Comment by keastrid** [comment]
Seems to work, thanks!
