### ISSUE TITLE
Add registry option for Inno Setup

### ISSUE THREAD

**Issue by NMNaufaldo** [fvarrui/JavaPackager#91]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
Add registry option for Inno Setup on Windows platform 

**Steps to reproduce the issue/enhancement:**

1. In generated InnoSetup file *.iss, there is an option for registering a registry for windows 

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
[Registry]
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "My App Name"; ValueData: "{app}\{#MyAppExeName}"; Flags: uninsdeletevalue

**What is the motivation / use case for changing the behavior?**
This registry is required, for example, make the software automatically run when the user turns on the computer

**Please tell us about your environment:**

- JavaPackager version: 3.8.1
- OS version: Windows 10
- JDK version: 15
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @NMNaufaldo!

You can create [your own customized VTL template](https://github.com/fvarrui/JavaPackager#velocity-templates) to generate a Setup installer. You only have to copy the current template to `assets/windows/iss.vtl` and add this:

```ini
[Registry]
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "My App Name"; ValueData: "{app}{#MyAppExeName}"; Flags: uninsdeletevalue
```

I'm not sure yet about this, but I've been thinking of including an option to add a post-install script to do all of these stuff (not only to write values on the Windows registry), allowing to include scripts for each platform, no only Windows. What do you think?

**Comment by NMNaufaldo** [comment]
> Hi @NMNaufaldo!
> 
> You can create [your own customized VTL template](https://github.com/fvarrui/JavaPackager#velocity-templates) to generate a Setup installer. You only have to copy the current template to `assets/windows/iss.vtl` and add this:
> 
> ```ini
> [Registry]
> Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "My App Name"; ValueData: "{app}{#MyAppExeName}"; Flags: uninsdeletevalue
> ```
> 
> I'm not sure yet about this, but I've been thinking of including an option to add a post-install script to do all of these stuff (not only to write values on the Windows registry), allowing to include scripts for each platform, no only Windows. What do you think?

**Comment by NMNaufaldo** [comment]
I was doing what you suggest before, edit the generated `*.iss` template file and add the registry. But what I want, all of this is generated automatically based on a POM file. Every time I run `mvn package`, I will edit the generated `*.iss` file again.

The idea for "including an option to add a post-install script for each platform" is great

**Comment by fvarrui** [comment]
Sorry, maybe I didn't explain it right.

You have to make a copy of [this file](https://github.com/fvarrui/JavaPackager/blob/master/src/main/resources/windows/iss.vtl) to `${basedir}/myassets/windows/iss.vtl` (for example), and then add these lines to the end:

```ini
[Registry]
Root: HKCU; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "My App Name"; ValueData: "{app}{#MyAppExeName}"; Flags: uninsdeletevalue
```

> You don't have to modify the generated one (`${basedir}/target/assets/${name}.iss}`), because it will be overwritten every time you package your app.

And finally add this option to your plugin configuration:

```xml
<assetsDir>${basedir}/myassets</assetsDir>
```

So, the plugin will use your template, instead of the original one.

**Comment by NMNaufaldo** [comment]
This is working, thank you. But I still hope there is an option for doing that on Maven or Gradle file

**Comment by fvarrui** [comment]
Ok, we can add next option to JavaPackager:

```xml
<winConfig>
    <registry>
        <entry>
            <key>HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run</key>
            <valueName>My App Name</valueName>
            <valueType>string</valueType>
            <valueData>{app}{#MyAppExeName}</valueData>
        </entry>
    </registry>
</winConfig>
```

**Comment by NMNaufaldo** [comment]
How about `Flags`? I have no idea what this `Flags` does

**Comment by fvarrui** [comment]
As it's explained in [Inno Setup docs](https://jrsoftware.org/ishelp/index.php?topic=registrysection):

> **uninsdeletevalue**
> Delete the value when the program is uninstalled.

I'd add this flag by default.

**Comment by fvarrui** [comment]
Hi @NMNaufaldo!

This feature is available in [issue-91](https://github.com/fvarrui/JavaPackager/tree/issue-91) branch. 

Docs are [here](https://github.com/fvarrui/JavaPackager/blob/issue-91/docs/windows-specific-properties.md#add-values-to-the-windows-registry).

You have to [install JavaPackager manually](https://github.com/fvarrui/JavaPackager#how-to-build-and-install-the-plugin) to your local repo.

If it works fine for you, I'll release it to Maven Central asap.

**Comment by NMNaufaldo** [comment]
Wow thanks, I will try this feature ASAP 😃

**Comment by NMNaufaldo** [comment]
I already try and it works perfectly, thank you so much 😃 

I will close this issue

**Comment by fvarrui** [comment]
Great!
