### ISSUE TITLE
Use GraalVM instead Java SDK

### ISSUE THREAD

**Issue by NMNaufaldo** [fvarrui/JavaPackager#98]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
Recently I use GraalVM + Gluon to create a JavaFX application. And the installer size is smaller compared to regular Java SDK (about 50 - 60% smaller). I don't know if this feature is possible or not to implement on this repo.

**What is the expected behavior?**
Create smaller installer

**What is the current behavior?**
When we create an installer with Java 11+, the installer size about 33 Mb.

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**
No

**What is the motivation / use case for changing the behavior?**
Create smaller installer

**Please tell us about your environment:**

- JavaPackager version: 1.5.1
- OS version: Windows 10
- JDK version: 11
- Build tool: 
	- [x ] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
JavaPackager uses the JDK that you have set on your system (AdoptOpenJDK, Amazon, Azul Zulu, BellSoft Liberica, GraalVM, ...).

> Recently I use GraalVM + Gluon to create a JavaFX application. And the installer size is smaller compared to regular Java SDK (about 50 - 60% smaller). I don't know if this feature is possible or not to implement on this repo.

How did you build your installer?

I'm not sure what action is needed in JavaPackager to support GraalVM.

I've tried to package an app using GraalVM and `jlink` fails ([there's an issue opened about this](https://github.com/oracle/graal/issues/3090)):
```bash
[INFO]         Creating JRE with next modules included: java.base,java.desktop
[INFO]         Using C:\Program Files\GraalVM\graalvm-ce-java11-21.0.0\jmods modules directory
[INFO]         Executing command: cmd.exe /s /c ""C:\Program Files\GraalVM\graalvm-ce-java11-21.0.0\bin\jlink" --module-path "C:\Program Files\GraalVM\graalvm-ce-java11-21.0.0\jmods" --add-modules java.base,java.desktop --output C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre --no-header-files --no-man-pages --strip-debug --compress=2"
[INFO]         Error: java.io.IOException: Invalid JMOD file: C:\Program Files\GraalVM\graalvm-ce-java11-21.0.0\jmods\java.base.jmod
```

**Comment by NMNaufaldo** [comment]
There is a [maven plugin](https://github.com/gluonhq/client-maven-plugin) for this. I just run `mvn client:build` and it will generate a native image for windows [HelloGluon.exe](https://ibb.co/xDscjJj)

When I run `mvn package` I get same error. Yeah I think this is because `jlink`

**Comment by fvarrui** [comment]
I've also added option `--vm=client` to reduce the generated JRE's size when calling `jlink` ... it's available in issue-93 branch. Maybe it helps to get a more optimal JRE.

Give some feedback, thanks!

**Comment by fvarrui** [comment]
I'll continue analyzing the distributable created by **client-maven-plugin** and try to find out what else could be removed from the JRE

**Comment by fvarrui** [comment]
> I've also added option `--vm=client` to reduce the generated JRE's size when calling `jlink` ... it's available in issue-93 branch. Maybe it helps to get a more optimal JRE.
> 
> Give some feedback, thanks!

I've removed this, as this option doesn't work for any JDK.

**Comment by fvarrui** [comment]
Hi @NMNaufaldo!

> I've also added option `--vm=client` to reduce the generated JRE's size when calling `jlink` ... it's available in issue-93 branch. Maybe it helps to get a more optimal JRE.

I've finally removed this option, as it doesn't work for any JDK.

I'm going to close this issue as it's more a matter of GraalVM than JavaPackager.

**Comment by NMNaufaldo** [comment]
Ok
