### ISSUE TITLE
Is there a way to disable code signing under macOS ?

### ISSUE THREAD

**Issue by avrilmaomao** [fvarrui/JavaPackager#99]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
We have some custom operations after the app bundle was generated. After that, we will code sign the app bundle and notarize it.  
We just need  the unsigned app bundle, can you add an option to disable the code signing process?

**Comment by fvarrui** [comment]
Yes, I can ... no problem.

I've planned to split the goal **package** into several goals (or Gradle tasks) (e.g., `create-app`, `create-setup`, `create-dmg`, `create-pkg`, `sign-app`, ...), so you can configure your own packaging workflow, but I still haven't had time 😅.

**Comment by fvarrui** [comment]
Your requested feature is implemented in [issue-99 branch](https://github.com/fvarrui/JavaPackager/tree/issue-99) (v.1.6.0-SNAPSHOT).

You have to install it manually to your local repo.

Please, give me some feedback when you try it!

**Comment by avrilmaomao** [comment]
Works as expected.
The package procecess builds the app bundle without the code signing process.

**Comment by avrilmaomao** [comment]
Also tried set codesignApp to true, works normal too.

**Comment by avrilmaomao** [comment]
> Yes, I can ... no problem.
> 
> I've planned to split the goal **package** into several goals (or Gradle tasks) (e.g., `create-app`, `create-setup`, `create-dmg`, `create-pkg`, `sign-app`, ...), so you can configure your own packaging workflow, but I still haven't had time 😅.

Thanks. Just take your time, so far ,it's good enough to use.
The real  difficulties of packaging Java apps under Mac  are perhaps dealing with all kinds of  erros and restrictions during code signing and nortarizationg process.

**Comment by fvarrui** [comment]
Thanks to you for helping to improve JavaPackager!
